# Try and add more data to topic_summary to give more context

In [2]:
import pandas as pd
import numpy as np
import ast

In [3]:
# Topic summary (Final DataFrame)
topic_summary = pd.read_csv("/Users/shantibrodnick/Downloads/topic_summary.csv")

# Raw clinical trials data with keywords in a list for each study
clinical_trials = pd.read_csv("/Users/shantibrodnick/Downloads/510Capstone/GenderDisparityinResearch/notebooks/Article_Data_APIs/key_clinical_trials.csv")

# Raw pubmed data with keywords in a list for each study
pubmed = pd.read_csv("/Users/shantibrodnick/Downloads/510Capstone/GenderDisparityinResearch/notebooks/Article_Data_APIs/key_pubmed.csv")

# Raw reddit data with keywords in a list for each post
reddit = pd.read_csv("/Users/shantibrodnick/Downloads/reddit_data_keywords.csv")

In [ ]:
#clinical_trials.info() # 101,542 rows
pubmed.info() # 2,235,186 rows 
#reddit.info() # 68,849 rows

NameError: name 'pubmed' is not defined

In [5]:
# No duplicates
print(clinical_trials['nct_number'].duplicated().sum())
print(pubmed[['doi', 'title']].duplicated().sum())
print(reddit[['created_utc', 'title']].duplicated().sum())

0
0
0

### Clinical Trials Cleaning For Final Topic Summary

In [6]:
clinical_trials.head(1)
## What to keep?
# nct_number (what makes a study unique)
# sponsor
# collaborators
# enrollement
# study type
# funder type
# keyword
# start year
# study status

,Unnamed: 0,nct_number,pom,title,sponsor,collaborators,sex,age,enrollment,summary,funder_type,study_type,start_date,completion_date,keyword,start_year,completion_year,study_status
0,0,NCT03426488,"Number of deaths, Follow up at least 20 years|...",Northern Sweden Health and Disease Study,Umeå University,NaN,ALL,"CHILD, ADULT, OLDER_ADULT",120000.0,NSHDS (Northern Sweden Health and Disease Stud...,OTHER,OBSERVATIONAL,1986-01-01,2026-01-01,['mammography'],1986,2026.0,UNKNOWN

In [7]:
ct = clinical_trials[['nct_number', 'sponsor', 'collaborators', 'enrollment', 'study_type', 'funder_type', 'keyword', 'start_year', 'study_status']]

In [ ]:
ct.head()

,nct_number,sponsor,collaborators,enrollment,study_type,funder_type,keyword,start_year,study_status
0,NCT03426488,Umeå University,NaN,120000.0,OBSERVATIONAL,OTHER,['mammography'],1986,UNKNOWN
1,NCT00005286,University of New Mexico,"National Heart, Lung, and Blood Institute (NHLBI)",NaN,OBSERVATIONAL,OTHER,['sleep disturbance'],1986,TERMINATED
2,NCT00005303,"National Heart, Lung, and Blood Institute (NHLBI)",NaN,NaN,OBSERVATIONAL,NIH,"['sexually transmitted infection', 'STI']",1986,COMPLETED
3,NCT00001210,National Cancer Institute (NCI),NaN,60.0,OBSERVATIONAL,NIH,"['sexually transmitted infection', 'STI']",1986,COMPLETED
4,NCT00001212,National Institute of Diabetes and Digestive a...,NaN,45.0,INTERVENTIONAL,NIH,['pregnancy test'],1986,COMPLETED
...,...,...,...,...,...,...,...,...,...
101537,NCT00005301,"National Heart, Lung, and Blood Institute (NHLBI)",NaN,NaN,OBSERVATIONAL,NIH,"['sexually transmitted infection', 'STI']",1984,COMPLETED
101538,NCT00000120,National Eye Institute (NEI),NaN,NaN,INTERVENTIONAL,NIH,"['sexually transmitted infection', 'STI']",1985,COMPLETED
101539,NCT00443716,Mayo Clinic,NaN,60.0,INTERVENTIONAL,OTHER,['menopause hormone therapy'],1985,COMPLETED
101540,NCT00001205,National Institute of Allergy and Infectious D...,NaN,500.0,OBSERVATIONAL,NIH,['headache'],1985,RECRUITING
101541,NCT00005184,"National Heart, Lung, and Blood Institute (NHLBI)",NaN,NaN,OBSERVATIONAL,NIH,['hypothyroidism'],1985,COMPLETED

#### Column EDA/Understanding

In [ ]:
# SPONSOR
print(ct['sponsor'].value_counts().head())
print(ct['sponsor'].nunique()) # 15,985 different sponsors
print(ct['sponsor'].isna().sum()) # No NA

sponsor
GlaxoSmithKline                                                  986
Cairo University                                                 859
National Institute of Allergy and Infectious Diseases (NIAID)    811
Pfizer                                                           744
Assiut University                                                744
                                                                ...
Rgene Corporation                                                  1
Fecundis Lab SL                                                    1
AFT Pharmaceuticals, Ltd.                                          1
Olivia Newton-John Cancer Research Institute                       1
Stefan Hagel                                                       1
Name: count, Length: 15985, dtype: int64
15985
0

In [ ]:
# STUDY STATUS
print(ct['study_status'].value_counts().head())
print(ct['study_status'].nunique()) # 11 different statuses
print(ct['study_status'].isna().sum()) # No NA

study_status
COMPLETED                  55429
UNKNOWN                    14590
RECRUITING                 12604
NOT_YET_RECRUITING          5653
TERMINATED                  5446
ACTIVE_NOT_RECRUITING       4019
WITHDRAWN                   2478
ENROLLING_BY_INVITATION     1023
SUSPENDED                    290
NO_LONGER_AVAILABLE            5
APPROVED_FOR_MARKETING         5
Name: count, dtype: int64
11
0

In [ ]:
# COLLABORATORS
print(ct['collaborators'].value_counts().head())
print(ct['collaborators'].nunique()) # 19,454
print(ct['collaborators'].isna().sum()) # 66,481 NAs

collaborators
National Cancer Institute (NCI)                                                                                                                               1224
National Institute of Mental Health (NIMH)                                                                                                                     378
National Heart, Lung, and Blood Institute (NHLBI)                                                                                                              318
National Institute on Drug Abuse (NIDA)                                                                                                                        317
Eunice Kennedy Shriver National Institute of Child Health and Human Development (NICHD)                                                                        314
                                                                                                                                                              ...
National Institute of Mental Health (NIMH)|The Lewy Body Dementia Association (LBDA)|National Institute on Aging (NIA)|National Institutes of Health (NIH)       1
Materialise                                                                                                                                                      1
Banner Alzheimer's Institute                                                                                                                                     1
Rivanna Medical, Inc.                                                                                                                                            1
The Swedish Society of Medicine|The Swedish Breast Cancer Association (BRO)|Swedish Breast Cancer Group                                                          1
Name: count, Length: 19454, dtype: int64
19454
66481

In [ ]:
# ENROLLMENT
print(ct['enrollment'].value_counts().head())
print(ct['enrollment'].nunique()) # 3781
print(ct['enrollment'].isna().sum()) # 304 NAs

enrollment
60.0        3846
100.0       3137
30.0        2937
40.0        2899
50.0        2561
            ...
9666.0         1
12647.0        1
35002.0        1
133065.0       1
7087.0         1
Name: count, Length: 3781, dtype: int64
3781
304

In [ ]:
# FUNDER TYPE
print(ct['funder_type'].value_counts().head())
print(ct['funder_type'].nunique()) # 8
print(ct['funder_type'].isna().sum()) # No NAs

funder_type
OTHER        75281
INDUSTRY     19133
OTHER_GOV     2966
NIH           2403
FED            890
NETWORK        755
INDIV          101
UNKNOWN         13
Name: count, dtype: int64
8
0

In [ ]:
# STUDY TYPE
print(ct['study_type'].value_counts().head())
print(ct['study_type'].nunique()) # 3
print(ct['study_type'].isna().sum()) # No NAs

'''
Interventional: Researchers test a drug, device, or behavior in patients to see how it affects health outcomes.
Observational: Researchers watch people and track health results without making any changes or giving special treatments.
Expanded Access: Patients with serious or life-threatening conditions get unapproved drugs when no other treatments work.
'''

study_type
INTERVENTIONAL     80045
OBSERVATIONAL      21487
EXPANDED_ACCESS       10
Name: count, dtype: int64
3
0

'\nInterventional: Researchers test a drug, device, or behavior in patients to see how it affects health outcomes.\nObservational: Researchers watch people and track health results without making any changes or giving special treatments.\nExpanded Access: Patients with serious or life-threatening conditions get unapproved drugs when no other treatments work.\n'

In [15]:
# START YEAR
# Top 10 Most Common
ct['start_year'].value_counts().head(10)

start_year
2025    8119
2024    7684
2023    7343
2022    7133
2021    7123
2019    5925
2020    5826
2026    5706
2018    5159
2017    4781
Name: count, dtype: int64

### PubMed Cleaning For Final Topic Summary

In [16]:
pubmed.head(1)

,Unnamed: 0,title,doi,abstract,journal,date,authors,year,keyword
0,0,IV. Prolapsus of the Rectum in Children.,10.1097/00000658-190001000-00028,NaN,Annals of surgery,1900-03-01,['C GCumston'],1900.0,['hemorrhoids']

In [17]:
pm = pubmed[['title', 'doi', 'journal', 'authors', 'year', 'keyword']]

In [18]:
# Create a column that is counting the amount of authors in a study
# Change the string to a list of strings
pm['authors'] = pm['authors'].str.split(', ')
# Count the length of the list to get the number of authors
pm['author_count'] = pm['authors'].str.len()

In [19]:
#pm['doi'] == '10.2903/j.efsa.2026.10175'
pm.loc[pm['doi'] == '10.2903/j.efsa.2026.10175']

,title,doi,journal,authors,year,keyword,author_count
2235141,Safety evaluation of the food enzyme triacylgl...,10.2903/j.efsa.2026.10175,EFSA journal. European Food Safety Authority,"[['NoneNone', 'HolgerZorn', 'José Manuel Barat...",2026.0,['allergic'],21

In [ ]:
# JOURNAL
print(pm['journal'].value_counts().head())
print(pm['journal'].nunique()) # 17,672 different journals
print(pm['journal'].isna().sum()) # 1,143 NAs

journal
PloS one                                22234
Cureus                                  14786
AIDS (London, England)                  13820
Diseases of the colon and rectum        13592
Lancet (London, England)                11990
                                        ...
Computing in cardiology                     1
Frontiers in lupus                          1
Feminist legal studies                      1
Blood immunology & cellular therapy         1
Companion animal health and genetics        1
Name: count, Length: 17672, dtype: int64
17672
1143

### Reddit Cleaning For Final Topic Summary

In [21]:
reddit.head(2)

,Unnamed: 0,created_utc,num_comments,over_18,score,selftext,title,ups,created,total_awards_received,upvote_ratio,updated_on,matched_topics,created_dt
0,3,1298048845,0,False,3,i do not understand why this isnt a hugely pop...,why isn't this more popular,3.0,1.298049e+09,NaN,NaN,NaN,[],2011-02-18 17:07:25
1,4,1308012115,0,False,2,regarding this post thank you in advance and w...,does anyone know of a more affordable way to g...,2.0,1.308016e+09,NaN,NaN,NaN,[],2011-06-14 00:41:55

In [22]:
r = reddit[['created_utc', 'num_comments', 'score', 'ups', 'total_awards_received', 'upvote_ratio', 'created_dt', 'matched_topics']]

In [23]:
# Replace [] in matched_topics with NA
r['matched_topics'] = r['matched_topics'].replace('[]', np.nan)

In [24]:
r['matched_topics'].isna().sum()

np.int64(16026)

In [25]:
# Remove NAs from topics
r = r.dropna(subset=['matched_topics'])

In [26]:
# Add commas between the topics in matched_topics column
r['topics'] = r['matched_topics'].str.replace(r"'\s+'","', '", regex = True)

In [27]:
r = r.drop(columns=['matched_topics'])

In [ ]:
r.head()

,created_utc,num_comments,score,ups,total_awards_received,upvote_ratio,created_dt,topics
4,1358258175,3,1,1.0,NaN,NaN,2013-01-15 13:56:15,"['abnormal_bleeding', 'oral_contraceptives']"
5,1374453111,0,1,1.0,NaN,NaN,2013-07-22 00:31:51,"['menstrual_cycle', 'dysmenorrhea', 'iron_anem..."
6,1376536030,0,1,1.0,NaN,NaN,2013-08-15 03:07:10,['menstrual_cycle']
7,1377062421,0,1,1.0,NaN,NaN,2013-08-21 05:20:21,['menstrual_cycle']
8,1377896807,0,2,2.0,NaN,NaN,2013-08-30 21:06:47,"['heavy_bleeding', 'tampon_safety']"
...,...,...,...,...,...,...,...,...
68844,1767216903,1,1,1.0,0.0,1.0,2025-12-31 21:35:03,['uti']
68845,1767217437,2,6,1.0,0.0,1.0,2025-12-31 21:43:57,"['menstrual_cycle', 'fatigue_sleep']"
68846,1767222797,2,1,1.0,0.0,1.0,2025-12-31 23:13:17,"['menstrual_cycle', 'yeast_infection', 'sti_std']"
68847,1767223888,3,1,1.0,0.0,1.0,2025-12-31 23:31:28,"['menstrual_cycle', 'pms_pmdd', 'fatigue_sleep']"
68848,1767224209,0,1,1.0,0.0,1.0,2025-12-31 23:36:49,"['menstrual_cycle', 'heavy_bleeding', 'uti']"

In [29]:
# Create year column
r['year'] = pd.to_datetime(r['created_dt'])
r['year'] = r['year'].dt.year
r = r.drop(columns='created_dt')

In [ ]:
r.head()

,created_utc,num_comments,score,ups,total_awards_received,upvote_ratio,topics,year
4,1358258175,3,1,1.0,NaN,NaN,"['abnormal_bleeding', 'oral_contraceptives']",2013
5,1374453111,0,1,1.0,NaN,NaN,"['menstrual_cycle', 'dysmenorrhea', 'iron_anem...",2013
6,1376536030,0,1,1.0,NaN,NaN,['menstrual_cycle'],2013
7,1377062421,0,1,1.0,NaN,NaN,['menstrual_cycle'],2013
8,1377896807,0,2,2.0,NaN,NaN,"['heavy_bleeding', 'tampon_safety']",2013
...,...,...,...,...,...,...,...,...
68844,1767216903,1,1,1.0,0.0,1.0,['uti'],2025
68845,1767217437,2,6,1.0,0.0,1.0,"['menstrual_cycle', 'fatigue_sleep']",2025
68846,1767222797,2,1,1.0,0.0,1.0,"['menstrual_cycle', 'yeast_infection', 'sti_std']",2025
68847,1767223888,3,1,1.0,0.0,1.0,"['menstrual_cycle', 'pms_pmdd', 'fatigue_sleep']",2025
68848,1767224209,0,1,1.0,0.0,1.0,"['menstrual_cycle', 'heavy_bleeding', 'uti']",2025

### Match Keyword with Topic

In [31]:
keywords_to_topic = {
    "menstrual_cycle": "menstrual cycle",
   "irregular_periods": "irregular menstruation",
   "heavy_bleeding": "menorrhagia, heavy menstrual bleeding",
   "abnormal_bleeding": "abnormal uterine bleeding, breakthrough bleeding, intermenstrual bleeding",
   "dysmenorrhea": "dysmenorrhea, period cramps",
   "amenorrhea": "amenorrhea",
   "oral_contraceptives": "combined oral contraceptives, progestin-only pill",
   "iud": "IUD, intrauterine device, copper IUD, levonorgestrel IUD",
   "contraceptive_side_effects": "contraceptive side effects, birth control and mood, birth control and libido",
   "tubal_ligation": "tubal ligation",
   "yeast_infection": "vulvovaginal candidiasis, recurrent yeast infection",
   "bacterial_vaginosis": "bacterial vaginosis",
   "uti": "urinary tract infection, UTI",
   "boric_acid": "boric acid vaginal suppository",
   "vaginal_ph_microbiome": "vaginal pH, vaginal microbiome",
   "probiotics": "probiotics vaginal health",
   "pelvic_pain": "pelvic pain",
   "ovarian_cyst": "ovarian cyst",
   "ovarian_torsion": "ovarian torsion",
   "endometriosis": "endometriosis",
   "adenomyosis": "adenomyosis",
   "pelvic_floor": "pelvic floor dysfunction, pelvic floor physical therapy",
   "vulvodynia": "vulvodynia",
   "interstitial_cystitis": "interstitial cystitis",
   "bartholin_cyst": "bartholin cyst",
   "breast_lump": "breast lump",
   "fibroadenoma": "fibroadenoma",
   "breast_pain": "breast pain, mastalgia, nipple pain",
   "breast_cancer_screening": "breast cancer screening, mammography, breast ultrasound, breast lump",
   "pcos": "PCOS, polycystic ovary syndrome",
   "hormonal_acne": "hormonal acne",
   "hirsutism": "hirsutism",
   "thyroid": "thyroid dysfunction, hypothyroidism, Hashimoto's thyroiditis",
   "menopause": "perimenopause, menopause hormone therapy, HRT",
   "hot_flashes_night_sweats": "hot flashes, night sweats",
   "sti_std": "sexually transmitted infection, STI",
   "painful_sex": "painful intercourse, dyspareunia",
   "libido": "libido, sexual desire",
   "unprotected_sex": "unprotected sex",
   "pregnancy_test": "pregnancy test",
   "abortion": "medical abortion, misoprostol, mifepristone",
   "abortion_policy": "abortion access",
   "hair_loss": "hair loss, alopecia",
   "iron_anemia": "iron deficiency anemia, ferritin",
   "bloating": "bloating",
   "hemorrhoids": "hemorrhoids",
   "nausea": "nausea",
   "fatigue_sleep": "fatigue, sleep disturbance",
   "heart_palpitations": "heart palpitations",
   "headache_migraine": "headache, migraine",
   "allergic_reaction": "allergic",
}

In [32]:
# split dictionary to separate keywords
keyword_to_topic = {}
for topic, kw_s in keywords_to_topic.items():
    for kw in kw_s.split(","):
        keyword_to_topic[kw.strip().lower()] = topic

In [33]:
topics_to_group = {
   "bartholin_cyst": "bartholin_cyst",
   "ovarian_torsion": "ovarian_torsion",
   "ovarian_cyst": "ovarian_cyst",
   "endometriosis": "endometriosis",
   "adenomyosis": "adenomyosis",
   "fibroadenoma": "fibroadenoma",
   "breast_lump": "breast_cancer",
   "breast_cancer_screening": "breast_cancer",
   "interstitial_cystitis": "interstitial_cystitis",
   "tubal_ligation": "tubal_ligation",
   "abortion_policy": "abortion_policy",
   "abortion": "abortion",
   "uti": "uti",
   "bacterial_vaginosis": "bacterial_vaginosis",
   "yeast_infection": "yeast_infection",
   "sti_std": "sti_std",
   "pcos": "pcos",
   "thyroid": "thyroid",
   "menopause": "menopause",
   "vulvodynia": "vulvodynia",
   "iud": "iud",
   "oral_contraceptives": "oral_contraceptives",
   "contraceptive_side_effects": "contraceptive_side_effects",
   "pregnancy_test": "pregnancy_test",
   "boric_acid": "boric_acid",
   "probiotics": "probiotics",
   "vaginal_ph_microbiome": "vaginal_ph_microbiome",
   "dysmenorrhea": "dysmenorrhea",
   "amenorrhea": "amenorrhea",
   "heavy_bleeding": "heavy_bleeding",
   "abnormal_bleeding": "abnormal_bleeding",
   "irregular_periods": "irregular_periods",
   "unprotected_sex": "unprotected_sex",
   "pelvic_pain": "pelvic_floor",
   "pelvic_floor": "pelvic_floor",
   "painful_sex": "painful_sex",
   "breast_pain": "breast_pain",
   "libido": "libido",
   "hirsutism": "hirsutism",
   "hair_loss": "hair_loss",
   "iron_anemia": "iron_anemia",
   "menstrual_cycle": "menstrual_cycle",
   "hormonal_acne": "hormonal_acne",
   "bloating": "bloating",
   "nausea": "nausea",
   "fatigue_sleep": "fatigue_sleep",
   "headache_migraine": "headache_migraine",
   "allergic_reaction": "allergic_reaction",
   "heart_palpitations": "heart_palpitations",
   "hemorrhoids": "hemorrhoids",
   "hot_flashes_night_sweats": "hot_flashes_night_sweats"
}

In [34]:
topics_to_group_reddit = {
    "bartholin_cyst": "bartholin_cyst",
    "ovarian_torsion": "ovarian_torsion",
    "ovarian_cyst": "ovarian_cyst",
    "endometriosis": "endometriosis",
    "adenomyosis": "adenomyosis",
    "fibroadenoma": "fibroadenoma",
    "breast_lump": "breast_cancer",
    "breast_cancer_screening": "breast_cancer",
    "interstitial_cystitis": "interstitial_cystitis",
    "tubal_ligation": "tubal_ligation",
    "abortion_policy": "abortion_policy",
    "abortion": "abortion",

    "uti": "uti",
    "bacterial_vaginosis": "bacterial_vaginosis",
    "yeast_infection": "yeast_infection",
    "sti_std": "sti_std",

    "pcos": "pcos",
    "thyroid": "thyroid",
    "menopause": "menopause",
    "vulvodynia": "vulvodynia",

    "iud": "iud",
    "implant_shot_ring_patch": "implant_shot_ring_patch",
    "oral_contraceptives": "oral_contraceptives",
    "contraceptive_side_effects": "contraceptive_side_effects",

    "pregnancy_test": "pregnancy_test",

    "boric_acid": "boric_acid",
    "probiotics": "probiotics",
    "vaginal_ph_microbiome": "vaginal_ph_microbiome",
    "tampon_safety": "feminine_products",
    "menstrual_cup": "feminine_products",
    "period_tracking_apps": "period_tracking_apps",
    "covid_vaccine": "covid_vaccine",
    "dysmenorrhea": "dysmenorrhea",
    "amenorrhea": "amenorrhea",

    "heavy_bleeding": "heavy_bleeding",
    "abnormal_bleeding": "abnormal_bleeding",
    "irregular_periods": "irregular_periods",
    "pms_pmdd": "pms_pmdd",
    "unprotected_sex": "unprotected_sex",

    "pelvic_pain": "pelvic_floor",
    "pelvic_floor": "pelvic_floor",

    "painful_sex": "painful_sex",
    "breast_pain": "breast_pain",
    "libido": "libido",
    "hirsutism": "hirsutism",
    "hair_loss": "hair_loss",
    "iron_anemia": "iron_anemia",
    "menstrual_cycle": "menstrual_cycle",
    "hormonal_acne": "hormonal_acne",
    "bloating": "bloating",
    "nausea": "nausea",
    "fatigue_sleep": "fatigue_sleep",
    "headache_migraine": "headache_migraine",
    "allergic_reaction": "allergic_reaction",
    "heart_palpitations": "heart_palpitations",
    "hemorrhoids": "hemorrhoids",
    "hot_flashes_night_sweats": "hot_flashes_night_sweats",
}

In [35]:
group_priority =  ["bartholin_cyst", "ovarian_torsion", "ovarian_cyst", "endometriosis",
   "adenomyosis", "fibroadenoma", "breast_cancer", "interstitial_cystitis",
   "tubal_ligation", "abortion_policy", "abortion", "uti",
   "bacterial_vaginosis", "yeast_infection", "sti_std", "pcos", "thyroid",
   "menopause", "vulvodynia", "iud", "implant_shot_ring_patch",
   "oral_contraceptives", "contraceptive_side_effects", "pregnancy_test",
   "boric_acid", "probiotics", "vaginal_ph_microbiome", "feminine_products",
   "period_tracking_apps", "covid_vaccine", "dysmenorrhea", "amenorrhea",
   "heavy_bleeding", "abnormal_bleeding", "irregular_periods", "pms_pmdd",
   "unprotected_sex", "pelvic_floor", "painful_sex", "breast_pain",
   "libido", "hirsutism", "hair_loss", "iron_anemia", "menstrual_cycle",
   "hormonal_acne", "bloating", "nausea", "fatigue_sleep",
   "headache_migraine", "allergic_reaction", "heart_palpitations",
   "hemorrhoids", "hot_flashes_night_sweats"]

In [36]:
# Rank the groups: Which one is more important when assigning to a group?
group_rank = {g: i for i, g in enumerate(group_priority)}

In [37]:
# function to turn clinical trials and pubmed data keywords to the main group
def assign_group(df, keyword_col="keyword"):
    df = df.copy()

    def get_group(raw):
        keyw_list = ast.literal_eval(raw)
        topics = [keyword_to_topic[k.strip().lower()] for k in keyw_list]
        groups = {topics_to_group[t] for t in topics}
        final_group = min(groups, key=lambda g:group_rank[g])
        return final_group

    df['assigned_group'] = df[keyword_col].apply(get_group)
    return df

In [38]:
# function to turn the reddit data from topic to main group
def assign_group_reddit(df, topic_col="topics"):
    df = df.copy()

    def get_group(raw):
        keyw_list = ast.literal_eval(raw)
        groups = [topics_to_group_reddit[k.strip().lower()] for k in keyw_list]
        final_group = min(groups, key=lambda g:group_rank[g])
        return final_group

    df['assigned_group'] = df[topic_col].apply(get_group)
    return df

In [ ]:
result_ct = assign_group(ct)
result_ct = result_ct.drop(columns='keyword')
result_ct.head()

,nct_number,sponsor,collaborators,enrollment,study_type,funder_type,start_year,study_status,assigned_group
0,NCT03426488,Umeå University,NaN,120000.0,OBSERVATIONAL,OTHER,1986,UNKNOWN,breast_cancer
1,NCT00005286,University of New Mexico,"National Heart, Lung, and Blood Institute (NHLBI)",NaN,OBSERVATIONAL,OTHER,1986,TERMINATED,fatigue_sleep
2,NCT00005303,"National Heart, Lung, and Blood Institute (NHLBI)",NaN,NaN,OBSERVATIONAL,NIH,1986,COMPLETED,sti_std
3,NCT00001210,National Cancer Institute (NCI),NaN,60.0,OBSERVATIONAL,NIH,1986,COMPLETED,sti_std
4,NCT00001212,National Institute of Diabetes and Digestive a...,NaN,45.0,INTERVENTIONAL,NIH,1986,COMPLETED,pregnancy_test
...,...,...,...,...,...,...,...,...,...
101537,NCT00005301,"National Heart, Lung, and Blood Institute (NHLBI)",NaN,NaN,OBSERVATIONAL,NIH,1984,COMPLETED,sti_std
101538,NCT00000120,National Eye Institute (NEI),NaN,NaN,INTERVENTIONAL,NIH,1985,COMPLETED,sti_std
101539,NCT00443716,Mayo Clinic,NaN,60.0,INTERVENTIONAL,OTHER,1985,COMPLETED,menopause
101540,NCT00001205,National Institute of Allergy and Infectious D...,NaN,500.0,OBSERVATIONAL,NIH,1985,RECRUITING,headache_migraine
101541,NCT00005184,"National Heart, Lung, and Blood Institute (NHLBI)",NaN,NaN,OBSERVATIONAL,NIH,1985,COMPLETED,thyroid

In [ ]:
result_pm = assign_group(pm)
result_pm = result_pm.drop(columns='keyword')
result_pm.head()

,title,doi,journal,authors,year,author_count,assigned_group
0,IV. Prolapsus of the Rectum in Children.,10.1097/00000658-190001000-00028,Annals of surgery,[['C GCumston']],1900.0,1,hemorrhoids
1,HEMIANOPSIA IN MIGRAINE.,10.1126/science.11.279.713-a,"Science (New York, N.Y.)",[['J MBaldwin']],1900.0,1,headache_migraine
2,An attempt to estimate fatigue of the cerebral...,10.1113/jphysiol.1901.sp000832,The Journal of physiology,[['A GLevy']],1901.0,1,fatigue_sleep
3,VII. Report of a Case of Recovery after Abdomi...,10.1097/00000658-190101000-00030,Annals of surgery,[['FMartin']],1901.0,1,hemorrhoids
4,A further research into fatigue of the central...,10.1113/jphysiol.1902.sp000895,The Journal of physiology,[['A GLevy']],1902.0,1,fatigue_sleep
...,...,...,...,...,...,...,...
2235181,Serotonin Degradation and Lipid Metabolism Reg...,10.1111/all.70399,Allergy,"[['Sabrinade Souza Ferreira', 'LisaHolla', 'So...",2026.0,14,allergic_reaction
2235182,Investigating the Potential Pharmacological Me...,10.2174/0113862073449045260321213418,Combinatorial chemistry & high throughput scre...,"[['ZehuaLin', 'AikebaierTuohuti', 'XiupingYang...",2026.0,6,allergic_reaction
2235183,Bridging environmental pollution and immune dy...,10.1080/21505594.2026.2690759,Virulence,"[['XuZhang', 'KeLiu', 'ZhiqiangZhang', 'XinyuH...",2026.0,8,allergic_reaction
2235184,Using new approach methodologies (NAMs) to inv...,10.1038/s41598-026-60082-z,Scientific reports,"[['Yu-YingChen', 'Bour-JrWang', 'Yung-HsuanChe...",2026.0,6,allergic_reaction
2235185,Penicillin allergy assessment pathway to impro...,10.3310/BEYF6487,NaN,"[['Jonathan ATSandoe', 'JennyBoards', 'Christo...",2026.0,12,allergic_reaction

In [ ]:
result_reddit = assign_group_reddit(r)
result_reddit = result_reddit.drop(columns='topics')
result_reddit.head()

,created_utc,num_comments,score,ups,total_awards_received,upvote_ratio,year,assigned_group
4,1358258175,3,1,1.0,NaN,NaN,2013,oral_contraceptives
5,1374453111,0,1,1.0,NaN,NaN,2013,dysmenorrhea
6,1376536030,0,1,1.0,NaN,NaN,2013,menstrual_cycle
7,1377062421,0,1,1.0,NaN,NaN,2013,menstrual_cycle
8,1377896807,0,2,2.0,NaN,NaN,2013,feminine_products
...,...,...,...,...,...,...,...,...
68844,1767216903,1,1,1.0,0.0,1.0,2025,uti
68845,1767217437,2,6,1.0,0.0,1.0,2025,menstrual_cycle
68846,1767222797,2,1,1.0,0.0,1.0,2025,yeast_infection
68847,1767223888,3,1,1.0,0.0,1.0,2025,pms_pmdd
68848,1767224209,0,1,1.0,0.0,1.0,2025,uti

In [ ]:
# make sure counts match the original topic_summary in our warehouse
print(result_reddit['assigned_group'].value_counts().head())
print(result_pm['assigned_group'].value_counts().head())
print(result_ct['assigned_group'].value_counts().head())

assigned_group
menstrual_cycle               5283
uti                           5089
ovarian_cyst                  4096
yeast_infection               3459
oral_contraceptives           3178
iud                           3055
dysmenorrhea                  2815
sti_std                       2595
bacterial_vaginosis           2574
endometriosis                 1984
pcos                          1696
feminine_products             1541
abortion                      1399
breast_cancer                 1342
implant_shot_ring_patch       1307
abnormal_bleeding             1229
pregnancy_test                 825
menopause                      818
thyroid                        796
pelvic_floor                   519
heavy_bleeding                 496
pms_pmdd                       480
libido                         462
period_tracking_apps           417
irregular_periods              398
nausea                         369
bartholin_cyst                 362
amenorrhea                     347
bloating                       330
tubal_ligation                 315
allergic_reaction              310
fatigue_sleep                  301
breast_pain                    290
probiotics                     253
fibroadenoma                   235
iron_anemia                    230
ovarian_torsion                202
headache_migraine              201
interstitial_cystitis          159
boric_acid                     148
unprotected_sex                146
hair_loss                      132
painful_sex                    109
vaginal_ph_microbiome           79
hemorrhoids                     76
adenomyosis                     72
abortion_policy                 68
covid_vaccine                   51
hot_flashes_night_sweats        47
vulvodynia                      40
heart_palpitations              32
hormonal_acne                   30
hirsutism                       21
contraceptive_side_effects      15
Name: count, dtype: int64
assigned_group
sti_std                       447309
fatigue_sleep                 282200
breast_cancer                 202544
allergic_reaction             165073
headache_migraine             129365
pregnancy_test                108885
thyroid                        93445
uti                            91771
hemorrhoids                    89096
nausea                         81694
iron_anemia                    63281
menopause                      44344
hair_loss                      44184
abortion                       43448
endometriosis                  37114
ovarian_cyst                   35775
vaginal_ph_microbiome          31268
menstrual_cycle                28848
pelvic_floor                   28173
contraceptive_side_effects     24604
iud                            15944
amenorrhea                     13265
breast_pain                    13220
libido                         11787
irregular_periods               7896
abortion_policy                 7362
pcos                            7356
oral_contraceptives             6924
dysmenorrhea                    6699
bloating                        6367
tubal_ligation                  6113
bacterial_vaginosis             6027
abnormal_bleeding               5867
yeast_infection                 5340
fibroadenoma                    5192
interstitial_cystitis           4892
heavy_bleeding                  4615
hot_flashes_night_sweats        3884
heart_palpitations              3734
painful_sex                     3708
hirsutism                       3699
unprotected_sex                 3096
ovarian_torsion                 2801
adenomyosis                     2484
hormonal_acne                   1941
bartholin_cyst                  1084
vulvodynia                      1035
probiotics                       432
boric_acid                         1
Name: count, dtype: int64
assigned_group
fatigue_sleep                 25021
pregnancy_test                11500
nausea                        10565
sti_std                        7347
menopause                      5422
breast_cancer                  4475
allergic_reaction              4118
headache_migraine              3942
pelvic_floor                   3251
uti                            2821
iron_anemia                    2706
breast_pain                    2238
painful_sex                    2003
bloating                       1817
hair_loss                      1513
abortion                       1386
ovarian_cyst                   1134
iud                            1022
contraceptive_side_effects      977
endometriosis                   975
thyroid                         933
dysmenorrhea                    893
menstrual_cycle                 780
libido                          592
bacterial_vaginosis             403
vaginal_ph_microbiome           388
abnormal_bleeding               377
oral_contraceptives             344
amenorrhea                      286
hemorrhoids                     286
pcos                            285
interstitial_cystitis           271
hot_flashes_night_sweats        267
heart_palpitations              217
heavy_bleeding                  164
unprotected_sex                 153
abortion_policy                 133
vulvodynia                      115
adenomyosis                     113
tubal_ligation                   60
irregular_periods                44
hirsutism                        43
ovarian_torsion                  41
fibroadenoma                     38
yeast_infection                  38
probiotics                       32
hormonal_acne                    10
bartholin_cyst                    3
Name: count, dtype: int64

#### Result datasets to csv

In [43]:
#result_reddit.to_csv("result_reddit.csv", index=False)
#result_pm.to_csv("result_pm.csv", index=False)
#result_ct.to_csv("result_ct.csv", index=False)

## Extended DataFrames

## Get topic_summary_year

In [183]:
result_reddit
#result_ct
#result_pm

,created_utc,num_comments,score,ups,total_awards_received,upvote_ratio,year,assigned_group
4,1358258175,3,1,1.0,NaN,NaN,2013,oral_contraceptives
5,1374453111,0,1,1.0,NaN,NaN,2013,dysmenorrhea
6,1376536030,0,1,1.0,NaN,NaN,2013,menstrual_cycle
7,1377062421,0,1,1.0,NaN,NaN,2013,menstrual_cycle
8,1377896807,0,2,2.0,NaN,NaN,2013,feminine_products
...,...,...,...,...,...,...,...,...
68844,1767216903,1,1,1.0,0.0,1.0,2025,uti
68845,1767217437,2,6,1.0,0.0,1.0,2025,menstrual_cycle
68846,1767222797,2,1,1.0,0.0,1.0,2025,yeast_infection
68847,1767223888,3,1,1.0,0.0,1.0,2025,pms_pmdd
68848,1767224209,0,1,1.0,0.0,1.0,2025,uti

In [59]:
#result = df.groupby(['Branch', 'Product']).size().reset_index(name='Count')
r_count = result_reddit.groupby(['year', 'assigned_group']).size().reset_index(name='Count')
ct_count = result_ct.groupby(['start_year', 'assigned_group']).size().reset_index(name='Count')
pm_count = result_pm.groupby(['year', 'assigned_group']).size().reset_index(name='Count')

In [81]:
print(r_count['year'].min())
print(ct_count['start_year'].min())
print(pm_count['year'].min())

2013
1968
1786.0

In [84]:
pm_count

        year         assigned_group  Count
0     1786.0            hemorrhoids      1
1     1790.0             amenorrhea      1
2     1790.0            hemorrhoids      1
3     1791.0            hemorrhoids      1
4     1793.0         heavy_bleeding      1
...      ...                    ...    ...
4383  2026.0        unprotected_sex     91
4384  2026.0                    uti   2421
4385  2026.0  vaginal_ph_microbiome    565
4386  2026.0             vulvodynia     35
4387  2026.0        yeast_infection    126

[4388 rows x 3 columns]

### Data Cleaning to merge for: year_topic_summary

In [61]:
# Filter years for both pubmed and clinical trials to 2013

In [62]:
ct_count_2013 = ct_count[ct_count['start_year'] >= 2013]

In [63]:
ct_count_2013['Count'].sum()

np.int64(79784)

In [64]:
pm_count
pm_count_2013 = pm_count[pm_count['year'] >= 2013]

In [65]:
pm_count_2013['Count'].sum()

np.int64(1041283)

In [66]:
r_count

     year         assigned_group  Count
0    2013           dysmenorrhea      1
1    2013      feminine_products      1
2    2013                    iud      1
3    2013        menstrual_cycle      3
4    2013    oral_contraceptives      2
..    ...                    ...    ...
542  2025        unprotected_sex     44
543  2025                    uti   1414
544  2025  vaginal_ph_microbiome     26
545  2025             vulvodynia     12
546  2025        yeast_infection    844

[547 rows x 3 columns]

In [67]:
# rename start_year to year
ct_count_2013 = ct_count_2013.rename(columns={'start_year':'year'})
ct_count_2013

      year         assigned_group  Count
702   2013      abnormal_bleeding     15
703   2013               abortion     55
704   2013        abortion_policy      6
705   2013            adenomyosis      6
706   2013      allergic_reaction    199
...    ...                    ...    ...
1343  2026        unprotected_sex      4
1344  2026                    uti    159
1345  2026  vaginal_ph_microbiome     25
1346  2026             vulvodynia      7
1347  2026        yeast_infection      4

[646 rows x 3 columns]

In [68]:
pm_count_2013

        year         assigned_group  Count
3716  2013.0      abnormal_bleeding    146
3717  2013.0               abortion    964
3718  2013.0        abortion_policy    163
3719  2013.0            adenomyosis     69
3720  2013.0      allergic_reaction   4297
...      ...                    ...    ...
4383  2026.0        unprotected_sex     91
4384  2026.0                    uti   2421
4385  2026.0  vaginal_ph_microbiome    565
4386  2026.0             vulvodynia     35
4387  2026.0        yeast_infection    126

[672 rows x 3 columns]

In [69]:
ct_count_2013.isna().sum()
ct_count_2013.info()

<class 'pandas.DataFrame'>
RangeIndex: 646 entries, 702 to 1347
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            646 non-null    int64
 1   assigned_group  646 non-null    str
 2   Count           646 non-null    int64
dtypes: int64(2), str(1)
memory usage: 23.4 KB

In [70]:
pm_count_2013.isna().sum()
pm_count_2013.info()

<class 'pandas.DataFrame'>
RangeIndex: 672 entries, 3716 to 4387
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            672 non-null    float64
 1   assigned_group  672 non-null    str
 2   Count           672 non-null    int64
dtypes: float64(1), int64(1), str(1)
memory usage: 24.3 KB

In [71]:
r_count.isna().sum()
r_count.info()

<class 'pandas.DataFrame'>
RangeIndex: 547 entries, 0 to 546
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            547 non-null    int32
 1   assigned_group  547 non-null    str
 2   Count           547 non-null    int64
dtypes: int32(1), int64(1), str(1)
memory usage: 17.7 KB

In [72]:
r_count['assigned_group'].nunique()
pm_count_2013['assigned_group'].nunique()
ct_count_2013['assigned_group'].nunique()

48

In [73]:
pm_ct_year = pd.merge(pm_count_2013, ct_count_2013, on=['year', 'assigned_group'])
pm_ct_year
# Count_x is pm
# Count_y is ct

       year         assigned_group  Count_x  Count_y
0    2013.0      abnormal_bleeding      146       15
1    2013.0               abortion      964       55
2    2013.0        abortion_policy      163        6
3    2013.0            adenomyosis       69        6
4    2013.0      allergic_reaction     4297      199
..      ...                    ...      ...      ...
641  2026.0        unprotected_sex       91        4
642  2026.0                    uti     2421      159
643  2026.0  vaginal_ph_microbiome      565       25
644  2026.0             vulvodynia       35        7
645  2026.0        yeast_infection      126        4

[646 rows x 4 columns]

In [74]:
year_topic_summary = pd.merge(pm_ct_year, r_count, on=['year', 'assigned_group'], how='outer')

In [75]:
year_topic_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 715 entries, 0 to 714
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            715 non-null    float64
 1   assigned_group  715 non-null    str
 2   Count_x         646 non-null    float64
 3   Count_y         646 non-null    float64
 4   Count           547 non-null    float64
dtypes: float64(4), str(1)
memory usage: 37.1 KB

In [76]:
# Rename columns so they are understandable and change floats to ints
year_topic_summary = year_topic_summary.rename(columns={'Count_x':'paper_count', 'Count_y':'clinical_trial_count', 'Count':'post_count'})
str_columns = ['year','paper_count','clinical_trial_count','post_count']
year_topic_summary[str_columns] = year_topic_summary[str_columns].astype('Int64')

In [77]:
year_topic_summary = year_topic_summary.fillna(0)

In [80]:
year_topic_summary

,year,assigned_group,paper_count,clinical_trial_count,post_count
0,2013,abnormal_bleeding,146,15,0
1,2013,abortion,964,55,0
2,2013,abortion_policy,163,6,0
3,2013,adenomyosis,69,6,0
4,2013,allergic_reaction,4297,199,0
...,...,...,...,...,...
710,2026,unprotected_sex,91,4,0
711,2026,uti,2421,159,0
712,2026,vaginal_ph_microbiome,565,25,0
713,2026,vulvodynia,35,7,0
714,2026,yeast_infection,126,4,0

### year_topic_summary to csv

In [79]:
#year_topic_summary.to_csv('year_topic_summary.csv', index=False)

In [182]:
r_count.head(20)

    year       assigned_group  Count
0   2013         dysmenorrhea      1
1   2013    feminine_products      1
2   2013                  iud      1
3   2013      menstrual_cycle      3
4   2013  oral_contraceptives      2
5   2013                 pcos      1
6   2013              sti_std      1
7   2014    abnormal_bleeding      1
8   2014             abortion      2
9   2014    allergic_reaction      1
10  2014           amenorrhea      1
11  2014  bacterial_vaginosis      3
12  2014        breast_cancer      2
13  2014          breast_pain      1
14  2014         dysmenorrhea      5
15  2014        endometriosis      5
16  2014    feminine_products      3
17  2014    irregular_periods      1
18  2014                  iud      3
19  2014            menopause      1

In [121]:
pm_count_2012 = pm_count[pm_count['year'] <= 2012]
print(pm_count_2012['year'].min())
print(pm_count_2012['year'].max())
pm_count_2012 = (pm_count_2012.groupby('assigned_group', as_index=False)['Count'].sum().rename(columns={'Count': 'paper_count'}))
pm_count_2012['year'] = 2012
pm_count_2012

1786.0
2012.0

1786.0
2012.0

                assigned_group  paper_count  year
0            abnormal_bleeding         2890  2012
1                     abortion        24388  2012
2              abortion_policy         2536  2012
3                  adenomyosis          406  2012
4            allergic_reaction        95737  2012
5                   amenorrhea         9873  2012
6          bacterial_vaginosis         3048  2012
7               bartholin_cyst          580  2012
8                     bloating         2331  2012
9                   boric_acid            1  2012
10               breast_cancer        86285  2012
11                 breast_pain         4570  2012
12  contraceptive_side_effects        17265  2012
13                dysmenorrhea         3578  2012
14               endometriosis        17401  2012
15               fatigue_sleep       109948  2012
16                fibroadenoma         3468  2012
17                   hair_loss        20726  2012
18           headache_migraine        62901  2012
19          heart_palpitations         1657  2012
20              heavy_bleeding         2918  2012
21                 hemorrhoids        58848  2012
22                   hirsutism         2840  2012
23               hormonal_acne         1233  2012
24    hot_flashes_night_sweats         1720  2012
25       interstitial_cystitis         2402  2012
26                 iron_anemia        32287  2012
27           irregular_periods         6334  2012
28                         iud        10630  2012
29                      libido         6350  2012
30                   menopause        26865  2012
31             menstrual_cycle        21455  2012
32                      nausea        39207  2012
33         oral_contraceptives         5302  2012
34                ovarian_cyst        19387  2012
35             ovarian_torsion         1270  2012
36                 painful_sex         1908  2012
37                        pcos         1272  2012
38                pelvic_floor        10653  2012
39              pregnancy_test        58361  2012
40                  probiotics           38  2012
41                     sti_std       277470  2012
42                     thyroid        54722  2012
43              tubal_ligation         4928  2012
44             unprotected_sex         1183  2012
45                         uti        51192  2012
46       vaginal_ph_microbiome        19866  2012
47                  vulvodynia          293  2012
48             yeast_infection         3369  2012

In [120]:
ct_count_2012 = ct_count[ct_count['start_year'] <= 2012]
print(ct_count_2012['start_year'].min())
print(ct_count_2012['start_year'].max())
ct_count_2012 = (ct_count_2012.groupby('assigned_group', as_index=False)['Count'].sum().rename(columns={'Count': 'clinical_count'}))
ct_count_2012['year'] = 2012
ct_count_2012

1968
2012

                assigned_group  clinical_count  year
0            abnormal_bleeding              73  2012
1                     abortion             371  2012
2              abortion_policy              19  2012
3                  adenomyosis              13  2012
4            allergic_reaction            1478  2012
5                   amenorrhea              73  2012
6          bacterial_vaginosis             101  2012
7               bartholin_cyst               1  2012
8                     bloating             295  2012
9                breast_cancer             901  2012
10                 breast_pain             411  2012
11  contraceptive_side_effects             144  2012
12                dysmenorrhea             143  2012
13               endometriosis             159  2012
14               fatigue_sleep            4141  2012
15                fibroadenoma               7  2012
16                   hair_loss             349  2012
17           headache_migraine             826  2012
18          heart_palpitations              53  2012
19              heavy_bleeding              55  2012
20                 hemorrhoids              53  2012
21                   hirsutism              17  2012
22    hot_flashes_night_sweats             135  2012
23       interstitial_cystitis             101  2012
24                 iron_anemia             501  2012
25           irregular_periods               7  2012
26                         iud             177  2012
27                      libido             164  2012
28                   menopause            1387  2012
29             menstrual_cycle             187  2012
30                      nausea            1821  2012
31         oral_contraceptives             148  2012
32                ovarian_cyst             311  2012
33             ovarian_torsion               8  2012
34                 painful_sex             200  2012
35                        pcos              56  2012
36                pelvic_floor             337  2012
37              pregnancy_test            2409  2012
38                  probiotics               3  2012
39                     sti_std            3276  2012
40                     thyroid             198  2012
41              tubal_ligation               9  2012
42             unprotected_sex              51  2012
43                         uti             514  2012
44       vaginal_ph_microbiome              38  2012
45                  vulvodynia              30  2012
46             yeast_infection               7  2012

In [135]:
# Create second set 2013 data frame
pm_count_2013_2 = pm_count[pm_count['year'] >= 2013]
ct_count_2013_2 = ct_count[ct_count['start_year'] >= 2013]

# rename count
pm_count_2013_2 = pm_count_2013_2.rename(columns={'Count':'paper_count'})
ct_count_2013_2 = ct_count_2013_2.rename(columns={'Count':'clinical_count', 'start_year':'year'})

In [ ]:
pm_count_2013_2.info() # these need to be int64
ct_count_2013_2.info() # these need to be int64
pm_count_2013_2['year'] = pm_count_2013_2['year'].astype('Int64')
ct_count_2013_2['year'] = ct_count_2013_2['year'].astype('Int64')

ct_count_2012.info()
pm_count_2012.info()

<class 'pandas.DataFrame'>
RangeIndex: 672 entries, 3716 to 4387
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            672 non-null    float64
 1   assigned_group  672 non-null    str
 2   paper_count     672 non-null    int64
dtypes: float64(1), int64(1), str(1)
memory usage: 24.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 646 entries, 702 to 1347
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            646 non-null    int64
 1   assigned_group  646 non-null    str
 2   clinical_count  646 non-null    int64
dtypes: int64(2), str(1)
memory usage: 23.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   assigned_group  47 non-null     str
 1   clinical_count  47 non-null     int64
 2   year            47 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   assigned_group  49 non-null     str
 1   paper_count     49 non-null     int64
 2   year            49 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.9 KB

In [145]:
pm_count_2013_2 
ct_count_2013_2

      year         assigned_group  clinical_count
702   2013      abnormal_bleeding              15
703   2013               abortion              55
704   2013        abortion_policy               6
705   2013            adenomyosis               6
706   2013      allergic_reaction             199
...    ...                    ...             ...
1343  2026        unprotected_sex               4
1344  2026                    uti             159
1345  2026  vaginal_ph_microbiome              25
1346  2026             vulvodynia               7
1347  2026        yeast_infection               4

[646 rows x 3 columns]

In [156]:
#pm_count_2013_2.merge(pm_count_2012, on=['assigned_group', 'paper_count'])

pm_count_all = pd.concat([pm_count_2012, pm_count_2013_2], ignore_index=True)
ct_count_all = pd.concat([ct_count_2012, ct_count_2013_2], ignore_index=True)

In [162]:
pm_count_all['cumulative_count'] = pm_count_all.groupby('assigned_group')['paper_count'].cumsum()
ct_count_all['cumulative_count'] = ct_count_all.groupby('assigned_group')['clinical_count'].cumsum()

In [185]:
pm_count_all
pm_count_all = pm_count_all.rename(columns={'cumulative_count':'cumulative_count_pm'})
pm_count_all

            assigned_group  paper_count  year  cumulative_count_pm
0        abnormal_bleeding         2890  2012                 2890
1                 abortion        24388  2012                24388
2          abortion_policy         2536  2012                 2536
3              adenomyosis          406  2012                  406
4        allergic_reaction        95737  2012                95737
..                     ...          ...   ...                  ...
716        unprotected_sex           91  2026                 3096
717                    uti         2421  2026                91769
718  vaginal_ph_microbiome          565  2026                31268
719             vulvodynia           35  2026                 1035
720        yeast_infection          126  2026                 5340

[721 rows x 4 columns]

In [184]:
ct_count_all
ct_count_all = ct_count_all.rename(columns={'cumulative_count':'cumulative_count_ct'})
ct_count_all

            assigned_group  clinical_count  year  cumulative_count_ct
0        abnormal_bleeding              73  2012                   73
1                 abortion             371  2012                  371
2          abortion_policy              19  2012                   19
3              adenomyosis              13  2012                   13
4        allergic_reaction            1478  2012                 1478
..                     ...             ...   ...                  ...
688        unprotected_sex               4  2026                  153
689                    uti             159  2026                 2821
690  vaginal_ph_microbiome              25  2026                  388
691             vulvodynia               7  2026                  115
692        yeast_infection               4  2026                   38

[693 rows x 4 columns]

In [181]:
r_count

     year         assigned_group  Count
0    2013           dysmenorrhea      1
1    2013      feminine_products      1
2    2013                    iud      1
3    2013        menstrual_cycle      3
4    2013    oral_contraceptives      2
..    ...                    ...    ...
542  2025        unprotected_sex     44
543  2025                    uti   1414
544  2025  vaginal_ph_microbiome     26
545  2025             vulvodynia     12
546  2025        yeast_infection    844

[547 rows x 3 columns]

In [186]:
year_topic_summary_all = pd.merge(pm_count_all, ct_count_all, on=['year', 'assigned_group'])

In [ ]:
#year_topic_summary_all.to_csv('year_topic_summary_all.csv', index=False)