In [200]:
# source .venv/bin/activate
import numpy as np
import pandas as pd
from paperscraper.pubmed import get_pubmed_papers 
from paperscraper.pubmed import get_query_from_keywords_and_date

# For the loops for each time block
from datetime import datetime, timedelta
import time
import calendar
from Bio import Entrez

# Loading to db
# importing os module for environment variables
import os
# importing necessary functions from dotenv library
from dotenv import load_dotenv 
# loading variables from .env file
load_dotenv() 
import psycopg2
from sqlalchemy import create_engine

In [ ]:
eighteenseventy_twentyten_pcos = '("1870/01/01"[Date - Create] : "1880/12/30"[Date - Create] AND "cancers[Title]")'
pcos = get_pubmed_papers(query=eighteenseventy_twentyten_pcos, max_results=9998)
print(pcos.info())
print(pcos)

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
None
Empty DataFrame
Columns: []
Index: []

In [ ]:
twentyeleven_twentysix_pcos = '("2011/01/01"[Date - Create] : "2026/6/25"[Date - Create] AND "pcos[Title]")'
pcos22 = get_pubmed_papers(query=twentyeleven_twentysix_pcos, max_results=9998)
print(pcos22.info())
print(pcos22)

<class 'pandas.DataFrame'>
RangeIndex: 3113 entries, 0 to 3112
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     3113 non-null   str
 1   abstract  2877 non-null   str
 2   journal   3113 non-null   str
 3   date      3113 non-null   str
 4   authors   3113 non-null   object
 5   doi       2995 non-null   str
dtypes: object(1), str(5)
memory usage: 5.4+ MB
None
                                                  title  \
0     Diagnostic and prognostic biomarkers in PCOS: ...
1     Correction: THBS1: a biomarker for PCOS and it...
2     Beyond association: Mediation roles of lipidom...
3     Retraction notice to "A new look at low-dose a...
4     A 3.6:1 myo-inositol to D-chiro-inositol ratio...
...                                                 ...
3108  Reply of the Authors: Luteal-phase clomiphene ...
3109  Study of Omentin1 and Other Adipokines and Hor...
3110  A single nucleotide polymorphism in exon 7 of ...
3111             Treatment strategies in PCOS patients.
3112  Management ofanovulatory infertility associate...

                                               abstract  \
0     Polycystic ovary syndrome (PCOS) is a highly p...
1                                                   NaN
2     Polycystic ovary syndrome (PCOS) is a metaboli...
3                                                   NaN
4     PCOS is frequently associated with metabolic d...
...                                                 ...
3108                                                NaN
3109  Polycystic ovary syndrome (PCOS) is associated...
3110  Patients with polycystic ovarian syndrome (PCO...
3111  Polycystic ovary syndrome (PCOS), with a preva...
3112  Polycystic ovary syndrome (PCOS) is the most c...

                                                journal        date  \
0     Clinica chimica acta; international journal of...  2026-06-26
1     Mammalian genome : official journal of the Int...  2026-06-26
2                Prostaglandins & other lipid mediators  2026-06-24
3     Journal of gynecology obstetrics and human rep...  2026-06-23
4     Journal of obstetrics and gynaecology : the jo...  2026-06-23
...                                                 ...         ...
3108                            Fertility and sterility  2009-10-01
3109                               Oman medical journal  2009-04-01
3110                         Molecular medicine reports  2008-01-01
3111                    Reproductive biomedicine online  2005-06-01
3112  Journal of the Medical Association of Thailand...  2004-10-01

                                                authors  \
0     [Amr Ali Mohamed AbdelgawwadEl-Sehrawy, Omer I...
1     [JieZhang, LuhongyuanJin, ChiChi, WenjieHou, J...
2                             [TingyuLang, YongxiuYang]
3     [Nisreen KhaledAref, Waleed Ali SayedAhmed, Ma...
4     [PedroBelchín Fernández, VirginiaCalvente, Mar...
...                                                 ...
3108                                      [AhmedBadawy]
3109   [AtheerMahde, MahmudShaker, ZohairAl-Mashhadani]
3110  [Jung-MiPark, Bon-HeeGu, Eung-JiLee, Jae-Young...
3111  [SaschaTauchert, Annika KLudwig, KDiedrich, Ju...
3112                                  [NaresSukcharoen]

                                       doi
0                10.1016/j.cca.2026.121197
1               10.1007/s00335-026-10255-y
2     10.1016/j.prostaglandins.2026.107090
3              10.1016/j.jogoh.2026.103230
4            10.1080/01443615.2026.2681759
...                                    ...
3108     10.1016/j.fertnstert.2009.07.1004
3109                   10.5001/omj.2009.25
3110                                   NaN
3111         10.1016/s1472-6483(11)60393-3
3112                                   NaN

[3113 rows x 6 columns]

First we will look at general health - reddit forums
Then mental health - reddit forums
Then women's health - reddit forums

1. Women's health 
2. Mental Health
3. General Health

1950 - June 19th 2026

Example usage
endo_papers = get_pubmed_papers(query="endometriosis", max_results=10)

In [ ]:
date_query = '("2026/06/24"[Date - Create])'
today = get_pubmed_papers(query=date_query, max_results=9998)
print(today.info())

<class 'pandas.DataFrame'>
RangeIndex: 5740 entries, 0 to 5739
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     5740 non-null   str
 1   abstract  5030 non-null   str
 2   journal   5740 non-null   str
 3   date      5740 non-null   str
 4   authors   5740 non-null   object
 5   doi       5721 non-null   str
dtypes: object(1), str(5)
memory usage: 9.5+ MB
None

In [113]:
date_query = '("1870/01/1"[Date - Create] : "1900/12/31"[Date - Create] AND "cancers[Title/abstract]")'
today = get_pubmed_papers(query=date_query, max_results=9998)
print(today.info())
print(today)

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     2 non-null      str
 1   abstract  0 non-null      object
 2   journal   2 non-null      str
 3   date      2 non-null      str
 4   authors   2 non-null      object
 5   doi       1 non-null      str
dtypes: object(2), str(4)
memory usage: 427.0+ bytes
None
                                               title abstract  \
0                             Cancers of the Larynx.     None
1  The Infection of the Connective Tissue in Scir...     None

                             journal        date       authors  \
0                  Annals of surgery  1889-05-01     [J BBall]
1  Journal of anatomy and physiology  1879-10-01  [CCreighton]

                                doi
0  10.1097/00000658-188901000-00117
1                               NaN

In [13]:
# womens health condition query
# source: https://www.brighamandwomens.org/womens-health/diseases-conditions
conditions = ["Abdominal cerclage", "Abnormal pap smears", "Abnormal uterine bleeding",  "Alzheimer's disease", "Amenorrhea",
            "Amniocentesis", "Arthritis", "Asthma", "Bacterial vaginosis", "Bleeding disorders", "Breast cancer", "Cancers",
            "Celiac disease", "Cervical cancer", "Cervical insufficiency", "Cervicitis", "Cesarean section (C-section)",
            "Chorionic villus sampling", "Colposcopy", "Congenital abnormalities", "Continence", "Contraception (birth control)",
            "Cystoscopy", "Depression and anxiety", "Dilation and curettage (D and C)", "Dysmenorrhea",  "Endometrial ablation",  "Endometrial biopsy",
            "Endometrial cancer", "Endometriosis", "Epilepsy", "Family planning", "Female genital cutting", "Fertility preservation",
            "Fibroma", "Gallstone disease",  "Genetic conditions", "Gentle cesarean section", "Gestational diabetes", "Gestational trophoblastic disease",
            "Graves' disease", "Gynecologic cancer", "Gynecologic specialty care", "Gynecologic well-woman care", "Gynecological surgery",  "Heart disease",
             "Heavy menstrual cycles", "High-risk pregnancy","HIV", "HPV", "In-vitro fertilization", "Infertility", "Integrative medicine", "Interstitial cystitis",
             "Irritable bowel syndrome (IBS)", "Laparoscopic hysterectomy", "Laparoscopy", "Loop electrosurgical excision procedure (LEEP)", "Lupus",
             "Menopause", "Menorrhagia", "Menstrual conditions", "Miscarriage", "Morning sickness", "Multiple sclerosis", "Myomectomy", "Osteoarthritis", "Osteoporosis",
             "Ovarian cancer", "Ovarian cysts", "Ovarian fibroma", "Overactive bladder", "Pancreatic cystic neoplasm", "Pap test", "Pelvic inflammatory disease (PID)",
             "Pelvic organ prolapse", "Pelvic pain", "Pelvic ultrasound", "Perimenopause", "Placenta accreta", "Placenta previa", "Polycystic ovary syndrome (PCOS)",
             "Postpartum depression", "Preconception planning", "Pregnancy", "Pregnancy complications", "Pregnancy, first trimester", "Pregnancy, multiples",
             "Pregnancy, second trimester", "Pregnancy, third trimester", "Premenstrual dysphoric disorder (PMDD)", "Premenstrual syndrome (PMS)", "Prenatal care", "Prenatal genetic screening", "Preterm birth",
             "Primary care for women", "Recurrent pregnancy loss", "Rheumatoid arthritis", "Robotic hysterectomy", "Robotic myomectomy", "Sexually transmitted diseases (STDs)", 
             "Sleep disorders", "Small vessel disease", "Sports injuries", "STIs", "Stress urinary incontinence", "Stroke", "Thyroid disease", "Transgender care", "Tubal ligation",
             "Turner syndrome", "Type I autoimmune hepatitis", "Ultrasound", "Urinary incontinence", "Urinary tract infections (UTIs)", "Uterine and vaginal prolapse", "Uterine fibroids",
             "Vaginal birth after cesarean section", "Vaginal cancer", "Vaginitis", "Vulvar cancer", "Vulvar dysplasia", "Vulvitis", "Yeast infection"
]

example = ["Abdominal cerclage", "Abnormal pap smears", "Abnormal uterine bleeding"]

# These conditions fall under these categories
'''
  Reproductive & Gynecologic, Cancers & Oncology, Pregnancy & Obstetrics, Fertility & Family Planning, Procedures & Tests,
  Hormonal & Endocrine, Urogynecologic, Neurological, Musculoskeletal, Cardiovascular & Vascular, Gastrointestinal,
  Infectious Disease & Sexual Health, Mental Health, Autoimmune, and Other / Care & Services
'''

# Critical Areas for Womens Health Research
# https://axiawh.com/resources/womens-health-is-under-researched/
'''
Breast Cancer, Endometriosis, Sexual Health, Postpartum Hypertension,
'''

'\nBreast Cancer, Endometriosis, Sexual Health, Postpartum Hypertension,\n'

In [ ]:
date_query = f'("2026/06/25"[Date - Create] AND ({example}))'
today = get_pubmed_papers(query=date_query, max_results=9998)
print(today)

Empty DataFrame
Columns: []
Index: []

In [ ]:
blood = '("2026/06/01"[Date - Create] : "2026/6/24"[Date - Create] AND (blood[Title/abstract]))'
blood_results = get_pubmed_papers(query=blood, max_results=9998)

In [30]:
print(blood_results.info())

<class 'pandas.DataFrame'>
RangeIndex: 7268 entries, 0 to 7267
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     7268 non-null   str
 1   abstract  7148 non-null   str
 2   journal   7260 non-null   str
 3   date      7268 non-null   str
 4   authors   7268 non-null   object
 5   doi       7222 non-null   str
dtypes: object(1), str(5)
memory usage: 14.9+ MB
None

In [58]:
keywords = ["Abdominal cerclage", "Abnormal pap smears", "Abnormal uterine bleeding",  "Alzheimer's disease", "Amenorrhea",
            "Amniocentesis", "Arthritis", "Asthma", "Bacterial vaginosis", "Bleeding disorders", "Breast cancer",
            "Celiac disease", "Cervical cancer", "Cervical insufficiency", "Cervicitis", "Cesarean section (C-section)"]

date_women = '("2026/06/01"[Date - Create] : "2026/6/24"[Date - Create])'
keywords_women = " OR ".join([f"{word}[Title]" for word in keywords])

date_key = f"({date_women}) AND {keywords_women})"

women_test = get_pubmed_papers(query=date_key, max_results=9998)
print(women_test.info())

INFO:pymed_paperscraper.api:ChunkedEncodingError: Response ended prematurely.	Now at 1 attempts for ['40537290', '40537268', '40535870', '40535416', '40535129', '40533823', '40533618', '40532888', '40532887', '40531956', '40531303', '40530360', '40530076', '40528439', '40528133', '40528071', '40527062', '40525055', '40525053', '40524947', '40524677', '40524241', '40524156', '40523495', '40522936', '40522505', '40522274', '40521792', '40521575', '40521260', '40520651', '40520265', '40519570', '40519226', '40519038', '40518987', '40518467', '40517682', '40517207', '40516128', '29999857', '40515671', '40515538', '40513496', '40513284', '40512829', '40512717', '40512138', '40511424', '40511255', '40510482', '40510096', '40509826', '40507506', '40506958', '40506370', '40506343', '40505985', '40505450', '40505447', '40505432', '40505112', '40505101', '40505037', '40503342', '40502965', '40502651', '40500831', '40499527', '40498141', '40498055', '40497795', '40497566', '40496321', '40495474', '40494606', '40494507', '40493979', '40493496', '40492660', '40492569', '40492456', '40491857', '40491499', '40491498', '40491116', '40491100', '40490718', '40490253', '40489977', '33877751', '40489861', '40489829', '40489823', '40489090', '40488524', '40486446', '40486431', '40486422', '40486353', '40486304', '40486247', '40486142', '40485998', '40485444', '40485396', '40485261', '40484702', '40483418', '40482714', '40481886', '40481498', '40481256', '40481103', '40479951', '40479883', '40479882', '40478320', '40476100', '40474704', '40474642', '40474635', '40474240', '40473652', '40473396', '40473320', '40473251', '40472896', '40472477', '40472372', '40472245', '40471917', '40471883', '40470885', '40470442', '40469735', '40469486', '40469219', '40468921', '40468446', '40467600', '40467502', '40466885', '40462801', '40462016', '40461983', '40461773', '40461242', '40461129', '40461002', '40460188', '40459888', '40459216', '40458539', '40458173', '40457790', '40454299', '40453288', '40452736', '40452568', '40452301', '40451859', '40451447', '40451049', '40450216', '40448517', '40448004', '40446728', '40444407', '40443599', '40443525', '40442672', '40442657', '40442613', '40441486', '40441213', '40440786', '40440681', '40440267', '40439834', '40438880', '40438018', '40437888', '40437872', '40436636', '40436310', '40433829', '40432859', '40432659', '40432555', '40429556', '40428877', '40426823', '40425222', '40425147', '40425107', '40424943', '40424400', '40423048', '40420688', '40420133', '40420004', '40419243', '40419242', '40419163', '40418898', '40417222', '40416161', '40415697', '40413742', '40413552', '40411224', '40411138', '40410916', '40410815', '40410291', '40410009', '40409608', '40409218', '40409039', '40406479', '40406476', '40406178', '40406170', '40405941', '40405180', '40405081', '40403873', '40403512', '40403315', '40403310', '40402533', '40402180', '40402048', '40400105', '40399139', '40399137', '40398910', '40398907', '40398823', '40398489', '40398198', '40398157', '40398142', '40397901', '40396833', '40396634', '40395936', '40393440', '40391965']:
<class 'pandas.DataFrame'>
RangeIndex: 9998 entries, 0 to 9997
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     9998 non-null   str
 1   abstract  9640 non-null   str
 2   journal   9957 non-null   str
 3   date      9998 non-null   str
 4   authors   9998 non-null   object
 5   doi       9827 non-null   str
dtypes: object(1), str(5)
memory usage: 19.4+ MB
None

In [ ]:
keywords = ["Abdominal cerclage", "Abnormal pap smears", "Abnormal uterine bleeding",  "Alzheimer's disease", "Amenorrhea",
            "Amniocentesis", "Arthritis", "Asthma", "Bacterial vaginosis", "Bleeding disorders", "Breast cancer", "Cancers",
            "Celiac disease", "Cervical cancer", "Cervical insufficiency", "Cervicitis", "Cesarean section (C-section)",
            "Chorionic villus sampling", "Colposcopy", "Congenital abnormalities", "Continence", "Contraception (birth control)",
            "Cystoscopy", "Depression and anxiety", "Dilation and curettage (D and C)", "Dysmenorrhea",  "Endometrial ablation",  "Endometrial biopsy",
            "Endometrial cancer", "Endometriosis", "Epilepsy", "Family planning", "Female genital cutting", "Fertility preservation",
            "Fibroma", "Gallstone disease",  "Genetic conditions", "Gentle cesarean section", "Gestational diabetes", "Gestational trophoblastic disease",
            "Graves' disease", "Gynecologic cancer", "Gynecologic specialty care", "Gynecologic well-woman care", "Gynecological surgery",  "Heart disease",
             "Heavy menstrual cycles", "High-risk pregnancy","HIV", "HPV", "In-vitro fertilization", "Infertility", "Integrative medicine", "Interstitial cystitis",
             "Irritable bowel syndrome (IBS)", "Laparoscopic hysterectomy", "Laparoscopy", "Loop electrosurgical excision procedure (LEEP)", "Lupus",
             "Menopause", "Menorrhagia", "Menstrual conditions", "Miscarriage", "Morning sickness", "Multiple sclerosis", "Myomectomy", "Osteoarthritis", "Osteoporosis",
             "Ovarian cancer", "Ovarian cysts", "Ovarian fibroma", "Overactive bladder", "Pancreatic cystic neoplasm", "Pap test", "Pelvic inflammatory disease (PID)",
             "Pelvic organ prolapse", "Pelvic pain", "Pelvic ultrasound", "Perimenopause", "Placenta accreta", "Placenta previa", "Polycystic ovary syndrome (PCOS)",
             "Postpartum depression", "Preconception planning", "Pregnancy", "Pregnancy complications", "Pregnancy, first trimester", "Pregnancy, multiples",
             "Pregnancy, second trimester", "Pregnancy, third trimester", "Premenstrual dysphoric disorder (PMDD)", "Premenstrual syndrome (PMS)", "Prenatal care", "Prenatal genetic screening", "Preterm birth",
             "Primary care for women", "Recurrent pregnancy loss", "Rheumatoid arthritis", "Robotic hysterectomy", "Robotic myomectomy", "Sexually transmitted diseases (STDs)", 
             "Sleep disorders", "Small vessel disease", "Sports injuries", "STIs", "Stress urinary incontinence", "Stroke", "Thyroid disease", "Transgender care", "Tubal ligation",
             "Turner syndrome", "Type I autoimmune hepatitis", "Ultrasound", "Urinary incontinence", "Urinary tract infections (UTIs)", "Uterine and vaginal prolapse", "Uterine fibroids",
             "Vaginal birth after cesarean section", "Vaginal cancer", "Vaginitis", "Vulvar cancer", "Vulvar dysplasia", "Vulvitis", "Yeast infection"
]

# Looping Test

In [ ]:
#######################################################################################################################################

In [148]:
# FIRST SET OF KEYWORDS 
# PER YEAR
######## 1870 - 1983 ###########

keywords_df1 = ["Abdominal cerclage", "Abnormal pap smears", "Abnormal uterine bleeding",  "Alzheimer's disease", "Amenorrhea",
            "Amniocentesis", "Arthritis", "Asthma", "Bacterial vaginosis", "Bleeding disorders", "Breast cancer", "Cancers",
            "Celiac disease", "Cervical cancer", "Cervical insufficiency", "Cervicitis", "Cesarean section (C-section)",
            "Chorionic villus sampling", "Colposcopy", "Congenital abnormalities", "Continence", "Contraception (birth control)",
            "Cystoscopy", "Depression and anxiety", "Dilation and curettage (D and C)", "Dysmenorrhea",  "Endometrial ablation",  "Endometrial biopsy",
            "Endometrial cancer", "Endometriosis", "Epilepsy", "Family planning", "Female genital cutting", "Fertility preservation",
            "Fibroma", "Gallstone disease",  "Genetic conditions", "Gentle cesarean section", "Gestational diabetes", "Gestational trophoblastic disease",
            "Graves' disease", "Gynecologic cancer", "Gynecologic specialty care", "Gynecologic well-woman care", "Gynecological surgery",  "Heart disease",
             "Heavy menstrual cycles", "High-risk pregnancy","HIV", "HPV", "In-vitro fertilization", "Infertility", "Integrative medicine", "Interstitial cystitis",
             "Irritable bowel syndrome (IBS)", "Laparoscopic hysterectomy", "Laparoscopy", "Loop electrosurgical excision procedure (LEEP)"
]

Entrez.email = "sebrodnick@willamette.edu"  # this identifies who is pulling and lessen 429 errors for pulling

keywords_joined1 = " OR ".join(f'"{word}"[Title/abstract]' for word in keywords_df1)

start_date1 = datetime(1870, 1, 1)
end_date1 = datetime(1983, 12, 31)

# List to hold dfs for each day
dfs_list1 = []
# Loop through each day
current_date1 = start_date1

while current_date1 <= end_date1:

    #date_str1 = current_date1.strftime("%Y/%m/%d") # pubmed needs YYYY/MM/DD
    #day_query1 = f'("{date_str1}"[Date - Create]) AND ({keywords_joined1})'

    start_str1 = f"{current_date1.year}/01/01"
    end_str1 = f"{current_date1.year}/12/31"
    year_query1 = f'("{start_str1}"[Date - Create] : "{end_str1}"[Date - Create]) AND ({keywords_joined1})'

    try:
        df1 = get_pubmed_papers(query = year_query1, max_results = 9998)
        if df1 is not None and not df1.empty:
            dfs_list1.append(df1)
            print(f"Papers found for this year {start_str1} - {end_str1}: {len(df1)}")
        else:
            print(f"No papers found for this year {start_str1} - {end_str1}")
        
    except Exception as e:
        print(f"Error getting papers for {current_date1.year}: {e}")

    time.sleep(3) # This will pause (3 seconds) between each loop, this will also help with 429 errors 
    current_date1 = datetime(current_date1.year + 1, 1, 1)

    # Move to next day
   #current_date1 += timedelta(days=1)

   # Move to the next month
   # if current_date1.month == 12:
        #current_date1 = datetime(current_date1.year + 1, 1, 1)
    #else:
        #current_date1 = datetime(current_date1.year, current_date1.month + 1, 1)


if dfs_list1:
    final_df1 = pd.concat(dfs_list1, ignore_index=True)
    print(f"Total number of papers: {len(final_df1)}")

else:
    print("No data collected")
    final_df1 = pd.DataFrame()

No papers found for this year 1870/01/01 - 1870/12/31
No papers found for this year 1871/01/01 - 1871/12/31
No papers found for this year 1872/01/01 - 1872/12/31
No papers found for this year 1873/01/01 - 1873/12/31
No papers found for this year 1874/01/01 - 1874/12/31
No papers found for this year 1875/01/01 - 1875/12/31
No papers found for this year 1876/01/01 - 1876/12/31
No papers found for this year 1877/01/01 - 1877/12/31
No papers found for this year 1878/01/01 - 1878/12/31
Papers found for this year 1879/01/01 - 1879/12/31: 1
No papers found for this year 1880/01/01 - 1880/12/31
No papers found for this year 1881/01/01 - 1881/12/31
No papers found for this year 1882/01/01 - 1882/12/31
No papers found for this year 1883/01/01 - 1883/12/31
Papers found for this year 1884/01/01 - 1884/12/31: 1
No papers found for this year 1885/01/01 - 1885/12/31
Papers found for this year 1886/01/01 - 1886/12/31: 1
Papers found for this year 1887/01/01 - 1887/12/31: 1
Papers found for this year 1888/01/01 - 1888/12/31: 1
Papers found for this year 1889/01/01 - 1889/12/31: 1
No papers found for this year 1890/01/01 - 1890/12/31
No papers found for this year 1891/01/01 - 1891/12/31
Papers found for this year 1892/01/01 - 1892/12/31: 1
Papers found for this year 1893/01/01 - 1893/12/31: 1
Papers found for this year 1894/01/01 - 1894/12/31: 2
No papers found for this year 1895/01/01 - 1895/12/31
Papers found for this year 1896/01/01 - 1896/12/31: 1
No papers found for this year 1897/01/01 - 1897/12/31
Papers found for this year 1898/01/01 - 1898/12/31: 3
Papers found for this year 1899/01/01 - 1899/12/31: 2
Papers found for this year 1900/01/01 - 1900/12/31: 1
Papers found for this year 1901/01/01 - 1901/12/31: 1
Papers found for this year 1902/01/01 - 1902/12/31: 1
Papers found for this year 1903/01/01 - 1903/12/31: 3
No papers found for this year 1904/01/01 - 1904/12/31
Papers found for this year 1905/01/01 - 1905/12/31: 1
Papers found for this year 1906/01/01 - 1906/12/31: 1
Papers found for this year 1907/01/01 - 1907/12/31: 1
Papers found for this year 1908/01/01 - 1908/12/31: 2
Papers found for this year 1909/01/01 - 1909/12/31: 8
Papers found for this year 1910/01/01 - 1910/12/31: 1
Papers found for this year 1911/01/01 - 1911/12/31: 6
Papers found for this year 1912/01/01 - 1912/12/31: 1
Papers found for this year 1913/01/01 - 1913/12/31: 2
Papers found for this year 1914/01/01 - 1914/12/31: 3
No papers found for this year 1915/01/01 - 1915/12/31
Papers found for this year 1916/01/01 - 1916/12/31: 4
Papers found for this year 1917/01/01 - 1917/12/31: 4
Papers found for this year 1918/01/01 - 1918/12/31: 1
Papers found for this year 1919/01/01 - 1919/12/31: 5
Papers found for this year 1920/01/01 - 1920/12/31: 5
Papers found for this year 1921/01/01 - 1921/12/31: 7
Papers found for this year 1922/01/01 - 1922/12/31: 5
Papers found for this year 1923/01/01 - 1923/12/31: 3
Papers found for this year 1924/01/01 - 1924/12/31: 8
Papers found for this year 1925/01/01 - 1925/12/31: 6
Papers found for this year 1926/01/01 - 1926/12/31: 9
Papers found for this year 1927/01/01 - 1927/12/31: 17
Papers found for this year 1928/01/01 - 1928/12/31: 14
Papers found for this year 1929/01/01 - 1929/12/31: 11
Papers found for this year 1930/01/01 - 1930/12/31: 7
Papers found for this year 1931/01/01 - 1931/12/31: 12
Papers found for this year 1932/01/01 - 1932/12/31: 6
Papers found for this year 1933/01/01 - 1933/12/31: 14
Papers found for this year 1934/01/01 - 1934/12/31: 12
Papers found for this year 1935/01/01 - 1935/12/31: 26
Papers found for this year 1936/01/01 - 1936/12/31: 11
Papers found for this year 1937/01/01 - 1937/12/31: 9
Papers found for this year 1938/01/01 - 1938/12/31: 21
Papers found for this year 1939/01/01 - 1939/12/31: 14
Papers found for this year 1940/01/01 - 1940/12/31: 18
Papers found for this year 1941/01/01 - 1941/12/31: 20
Papers found for this year 1942/01/01 - 1942/12/31: 14
Papers found for this year 1943/01/01 - 1943/12/31: 8
Papers found for this year 1944/01/01 - 1944/12/31: 11
Papers found for this year 1945/01/01 - 1945/12/31: 12
Papers found for this year 1946/01/01 - 1946/12/31: 21
Papers found for this year 1947/01/01 - 1947/12/31: 339
Papers found for this year 1948/01/01 - 1948/12/31: 1300
Papers found for this year 1949/01/01 - 1949/12/31: 1284
Papers found for this year 1950/01/01 - 1950/12/31: 1755
Papers found for this year 1951/01/01 - 1951/12/31: 2345
Papers found for this year 1952/01/01 - 1952/12/31: 2471
Papers found for this year 1953/01/01 - 1953/12/31: 2419
Papers found for this year 1954/01/01 - 1954/12/31: 2490
Papers found for this year 1955/01/01 - 1955/12/31: 2433
Papers found for this year 1956/01/01 - 1956/12/31: 2341
Papers found for this year 1957/01/01 - 1957/12/31: 2284
Papers found for this year 1958/01/01 - 1958/12/31: 2307
Papers found for this year 1959/01/01 - 1959/12/31: 2037
Papers found for this year 1960/01/01 - 1960/12/31: 1894
Papers found for this year 1961/01/01 - 1961/12/31: 2297
Papers found for this year 1962/01/01 - 1962/12/31: 2703
Papers found for this year 1963/01/01 - 1963/12/31: 4003
Papers found for this year 1964/01/01 - 1964/12/31: 4995
Papers found for this year 1965/01/01 - 1965/12/31: 3027
Papers found for this year 1966/01/01 - 1966/12/31: 2038
Papers found for this year 1967/01/01 - 1967/12/31: 2136
Papers found for this year 1968/01/01 - 1968/12/31: 2636
Papers found for this year 1969/01/01 - 1969/12/31: 2785
Papers found for this year 1970/01/01 - 1970/12/31: 3008
Papers found for this year 1971/01/01 - 1971/12/31: 3259
Papers found for this year 1972/01/01 - 1972/12/31: 3351
Papers found for this year 1973/01/01 - 1973/12/31: 3661
Papers found for this year 1974/01/01 - 1974/12/31: 3861
Papers found for this year 1975/01/01 - 1975/12/31: 5845
Papers found for this year 1976/01/01 - 1976/12/31: 6389
Papers found for this year 1977/01/01 - 1977/12/31: 6804
Papers found for this year 1978/01/01 - 1978/12/31: 6649
INFO:pymed_paperscraper.api:ChunkedEncodingError: Response ended prematurely.	Now at 1 attempts for ['11662686', '583577', '582160', '573917', '572881', '572653', '572249', '572207', '571817', '571589', '556232', '556187', '555811', '553901', '552525', '549105', '548886', '545457', '541797', '540773', '533332', '531356', '531148', '531146', '528489', '525052', '525051', '525040', '521063', '516664', '511278', '511268', '511260', '511258', '510336', '510332', '509331', '504008', '496546', '496268', '496267', '496254', '496252', '496213', '495055', '490529', '490526', '490523', '490489', '490011', '488590', '487302', '486835', '486313', '486310', '486309', '485650', '485645', '483941', '483937', '483343', '483342', '483341', '483340', '483339', '482207', '481577', '481188', '481181', '480873', '480869', '480868', '479683', '477922', '477919', '477915', '477913', '477069', '477067', '477066', '477065', '477031', '475681', '475502', '475227', '474902', '474901', '474897', '474330', '474326', '474065', '473931', '473928', '473927', '472578', '472070', '472064', '471869', '471778', '471164', '471160', '471158', '470115', '470113', '470112', '470108', '470103', '470102', '469599', '469595', '468577', '468563', '468126', '467291', '467183', '467058', '467057', '467056', '467054', '467052', '466865', '466756', '466751', '466750', '465385', '465227', '465225', '465224', '464548', '464546', '464541', '464332', '464175', '463680', '463590', '463256', '462951', '462750', '460964', '460677', '460676', '460674', '460219', '459212', '459210', '459108', '459095', '459093', '458771', '458752', '458172', '457082', '456964', '456859', '456858', '456857', '456707', '456695', '455316', '454935', '454934', '454016', '453644', '453457', '453182', '453142', '453073', '452256', '451392', '451178', '451126', '450859', '449642', '449527', '449185', '448761', '448760', '448491', '448489', '447764', '447304', '447303', '446781', '446779', '446776', '446775', '446774', '446422', '445616', '445611', '445388', '445384', '445383', '445382', '445380', '445376', '445375', '445371', '445362', '445358', '444318', '444316', '444314', '444313', '443908', '443848', '443307', '443259', '443249', '442697', '442692', '442394', '442368', '441762', '441357', '440895', '440670', '440669', '440174', '440044', '439245', '438451', '438265', '438262', '434285', '433823', '433819', '433818', '433780', '433740', '433730', '432156', '431131', '431107', '429744', '429711', '429710', '428109', '428108', '428098', '427816', '427805', '427797', '427794', '427788', '387168', '387167', '387166', '387165', '387162']:
Papers found for this year 1979/01/01 - 1979/12/31: 7326
Papers found for this year 1980/01/01 - 1980/12/31: 8014
Papers found for this year 1981/01/01 - 1981/12/31: 8197
Papers found for this year 1982/01/01 - 1982/12/31: 8459
Papers found for this year 1983/01/01 - 1983/12/31: 9786
Total number of papers: 139311

In [142]:
print(final_df1)

                                                   title abstract  \
0      The Infection of the Connective Tissue in Scir...     None
1      Deafness in white cats, and statistics of deaf...     None
2                     DR. HUGHLINGS-JACKSON ON EPILEPSY.     None
3      The Causation of Several Variations and Congen...     None
4              Note on Electrolysis for Uterine Fibroma.     None
...                                                  ...      ...
28077                [On the problem of pykno-epilepsy].      NaN
28078  [Effect of closing and opening of the eyes on ...      NaN
28079  [Considerations on epileptic manifestations of...      NaN
28080  [Physiopathological considerations on Hunt's d...      NaN
28081  Histology of the liver in congenital heart dis...      NaN

                                                 journal        date  \
0                      Journal of anatomy and physiology  1879-10-01
1                               Science (New York, N.Y.)  1884-02-29
2                               Science (New York, N.Y.)  1886-06-11
3                      Journal of anatomy and physiology  1887-07-01
4                                      Annals of surgery  1888-11-01
...                                                  ...         ...
28077  Zhurnal nevropatologii i psikhiatrii imeni S.S...  1960-01-01
28078                               Suvremenna meditsina  1960-01-01
28079                     Rassegna di studi psichiatrici  1960-01-01
28080        Giornale di psichiatria e di neuropatologia  1960-01-01
28081                        Annales paediatriae Fenniae  1960-01-01

                                      authors  \
0                                [CCreighton]
1                                   [A GBell]
2                                        [JJ]
3                                   [W ALane]
4                                   [A PPeck]
...                                       ...
28077                            [S MBABIIAN]
28078                                [EATSEV]
28079                      [RARDITO, CMELONI]
28080  [GAMICO, MMINAZZI, ISOLDINI, EVASSENA]
28081      [E KAHVENAINEN, LHJELT, BLANDTMAN]

                                    doi
0                                  None
1         10.1126/science.ns-3.56.243-a
2         10.1126/science.ns-7.175S.533
3                                  None
4      10.1097/00000658-188807000-00156
...                                 ...
28077                               NaN
28078                               NaN
28079                               NaN
28080                               NaN
28081                               NaN

[28082 rows x 6 columns]

In [149]:
# SECOND SET OF KEYWORDS 
# PER YEAR
######## 1870 - 1983 ###########

keywords_df2 = ["Lupus", "Menopause", "Menorrhagia", "Menstrual conditions", "Miscarriage", "Morning sickness", "Multiple sclerosis", "Myomectomy", "Osteoarthritis", "Osteoporosis",
             "Ovarian cancer", "Ovarian cysts", "Ovarian fibroma", "Overactive bladder", "Pancreatic cystic neoplasm", "Pap test", "Pelvic inflammatory disease (PID)",
             "Pelvic organ prolapse", "Pelvic pain", "Pelvic ultrasound", "Perimenopause", "Placenta accreta", "Placenta previa", "Polycystic ovary syndrome (PCOS)",
             "Postpartum depression", "Preconception planning", "Pregnancy", "Pregnancy complications", "Pregnancy, first trimester", "Pregnancy, multiples",
             "Pregnancy, second trimester", "Pregnancy, third trimester", "Premenstrual dysphoric disorder (PMDD)", "Premenstrual syndrome (PMS)", "Prenatal care", "Prenatal genetic screening", 
             "Preterm birth", "Primary care for women", "Recurrent pregnancy loss", "Rheumatoid arthritis", "Robotic hysterectomy", "Robotic myomectomy", "Sexually transmitted diseases (STDs)", 
             "Sleep disorders", "Small vessel disease", "Sports injuries", "STIs", "Stress urinary incontinence", "Stroke", "Thyroid disease", "Transgender care", "Tubal ligation",
             "Turner syndrome", "Type I autoimmune hepatitis", "Ultrasound", "Urinary incontinence", "Urinary tract infections (UTIs)", "Uterine and vaginal prolapse", "Uterine fibroids",
             "Vaginal birth after cesarean section", "Vaginal cancer", "Vaginitis", "Vulvar cancer", "Vulvar dysplasia", "Vulvitis", "Yeast infection"
]

Entrez.email = "sebrodnick@willamette.edu"  # this identifies who is pulling and lessen 429 errors for pulling

keywords_joined2 = " OR ".join(f'"{word}"[Title/abstract]' for word in keywords_df2)

start_date2 = datetime(1870, 1, 1)
end_date2 = datetime(1983, 12, 31)

# List to hold dfs for each day
dfs_list2 = []
# Loop through each day
current_date2 = start_date2

while current_date2 <= end_date2:

    #date_str1 = current_date1.strftime("%Y/%m/%d") # pubmed needs YYYY/MM/DD
    #day_query1 = f'("{date_str1}"[Date - Create]) AND ({keywords_joined1})'

    start_str2 = f"{current_date2.year}/01/01"
    end_str2 = f"{current_date2.year}/12/31"
    year_query2 = f'("{start_str2}"[Date - Create] : "{end_str2}"[Date - Create]) AND ({keywords_joined2})'

    try:
        df2 = get_pubmed_papers(query = year_query2, max_results = 9998)
        if df2 is not None and not df2.empty:
            dfs_list2.append(df2)
            print(f"Papers found for this year {start_str2} - {end_str2}: {len(df2)}")
        else:
            print(f"No papers found for this year {start_str2} - {end_str2}")
        
    except Exception as e:
        print(f"Error getting papers for {current_date2.year}: {e}")

    time.sleep(3) # This will pause (3 seconds) between each loop, this will also help with 429 errors 
    current_date2 = datetime(current_date2.year + 1, 1, 1)

    # Move to next day
   #current_date1 += timedelta(days=1)

   # Move to the next month
   # if current_date1.month == 12:
        #current_date1 = datetime(current_date1.year + 1, 1, 1)
    #else:
        #current_date1 = datetime(current_date1.year, current_date1.month + 1, 1)


if dfs_list2:
    final_df2 = pd.concat(dfs_list2, ignore_index=True)
    print(f"Total number of papers: {len(final_df2)}")

else:
    print("No data collected")
    final_df2 = pd.DataFrame()

No papers found for this year 1870/01/01 - 1870/12/31
Papers found for this year 1871/01/01 - 1871/12/31: 1
No papers found for this year 1872/01/01 - 1872/12/31
No papers found for this year 1873/01/01 - 1873/12/31
No papers found for this year 1874/01/01 - 1874/12/31
No papers found for this year 1875/01/01 - 1875/12/31
No papers found for this year 1876/01/01 - 1876/12/31
No papers found for this year 1877/01/01 - 1877/12/31
No papers found for this year 1878/01/01 - 1878/12/31
No papers found for this year 1879/01/01 - 1879/12/31
No papers found for this year 1880/01/01 - 1880/12/31
No papers found for this year 1881/01/01 - 1881/12/31
No papers found for this year 1882/01/01 - 1882/12/31
No papers found for this year 1883/01/01 - 1883/12/31
No papers found for this year 1884/01/01 - 1884/12/31
Papers found for this year 1885/01/01 - 1885/12/31: 2
No papers found for this year 1886/01/01 - 1886/12/31
Papers found for this year 1887/01/01 - 1887/12/31: 1
No papers found for this year 1888/01/01 - 1888/12/31
No papers found for this year 1889/01/01 - 1889/12/31
No papers found for this year 1890/01/01 - 1890/12/31
No papers found for this year 1891/01/01 - 1891/12/31
Papers found for this year 1892/01/01 - 1892/12/31: 1
Papers found for this year 1893/01/01 - 1893/12/31: 2
Papers found for this year 1894/01/01 - 1894/12/31: 1
No papers found for this year 1895/01/01 - 1895/12/31
No papers found for this year 1896/01/01 - 1896/12/31
No papers found for this year 1897/01/01 - 1897/12/31
No papers found for this year 1898/01/01 - 1898/12/31
Papers found for this year 1899/01/01 - 1899/12/31: 1
No papers found for this year 1900/01/01 - 1900/12/31
Papers found for this year 1901/01/01 - 1901/12/31: 1
No papers found for this year 1902/01/01 - 1902/12/31
Papers found for this year 1903/01/01 - 1903/12/31: 1
No papers found for this year 1904/01/01 - 1904/12/31
Papers found for this year 1905/01/01 - 1905/12/31: 3
Papers found for this year 1906/01/01 - 1906/12/31: 1
Papers found for this year 1907/01/01 - 1907/12/31: 5
Papers found for this year 1908/01/01 - 1908/12/31: 2
Papers found for this year 1909/01/01 - 1909/12/31: 2
No papers found for this year 1910/01/01 - 1910/12/31
Papers found for this year 1911/01/01 - 1911/12/31: 5
Papers found for this year 1912/01/01 - 1912/12/31: 2
Papers found for this year 1913/01/01 - 1913/12/31: 4
Papers found for this year 1914/01/01 - 1914/12/31: 3
Papers found for this year 1915/01/01 - 1915/12/31: 2
Papers found for this year 1916/01/01 - 1916/12/31: 1
Papers found for this year 1917/01/01 - 1917/12/31: 4
Papers found for this year 1918/01/01 - 1918/12/31: 2
Papers found for this year 1919/01/01 - 1919/12/31: 2
Papers found for this year 1920/01/01 - 1920/12/31: 2
Papers found for this year 1921/01/01 - 1921/12/31: 1
Papers found for this year 1922/01/01 - 1922/12/31: 3
Papers found for this year 1923/01/01 - 1923/12/31: 4
Papers found for this year 1924/01/01 - 1924/12/31: 7
Papers found for this year 1925/01/01 - 1925/12/31: 9
Papers found for this year 1926/01/01 - 1926/12/31: 6
Papers found for this year 1927/01/01 - 1927/12/31: 10
Papers found for this year 1928/01/01 - 1928/12/31: 11
Papers found for this year 1929/01/01 - 1929/12/31: 7
Papers found for this year 1930/01/01 - 1930/12/31: 11
Papers found for this year 1931/01/01 - 1931/12/31: 8
Papers found for this year 1932/01/01 - 1932/12/31: 15
Papers found for this year 1933/01/01 - 1933/12/31: 15
Papers found for this year 1934/01/01 - 1934/12/31: 19
Papers found for this year 1935/01/01 - 1935/12/31: 13
Papers found for this year 1936/01/01 - 1936/12/31: 19
Papers found for this year 1937/01/01 - 1937/12/31: 12
Papers found for this year 1938/01/01 - 1938/12/31: 10
Papers found for this year 1939/01/01 - 1939/12/31: 17
Papers found for this year 1940/01/01 - 1940/12/31: 14
Papers found for this year 1941/01/01 - 1941/12/31: 9
Papers found for this year 1942/01/01 - 1942/12/31: 10
Papers found for this year 1943/01/01 - 1943/12/31: 13
Papers found for this year 1944/01/01 - 1944/12/31: 6
Papers found for this year 1945/01/01 - 1945/12/31: 12
Papers found for this year 1946/01/01 - 1946/12/31: 11
Papers found for this year 1947/01/01 - 1947/12/31: 282
Papers found for this year 1948/01/01 - 1948/12/31: 1295
Papers found for this year 1949/01/01 - 1949/12/31: 1260
Papers found for this year 1950/01/01 - 1950/12/31: 1878
Papers found for this year 1951/01/01 - 1951/12/31: 2258
Papers found for this year 1952/01/01 - 1952/12/31: 2316
Papers found for this year 1953/01/01 - 1953/12/31: 2448
Papers found for this year 1954/01/01 - 1954/12/31: 2564
Papers found for this year 1955/01/01 - 1955/12/31: 2628
Papers found for this year 1956/01/01 - 1956/12/31: 2541
Papers found for this year 1957/01/01 - 1957/12/31: 2748
Papers found for this year 1958/01/01 - 1958/12/31: 2778
Papers found for this year 1959/01/01 - 1959/12/31: 2717
Papers found for this year 1960/01/01 - 1960/12/31: 2626
Papers found for this year 1961/01/01 - 1961/12/31: 2820
Papers found for this year 1962/01/01 - 1962/12/31: 3029
Papers found for this year 1963/01/01 - 1963/12/31: 5342
Papers found for this year 1964/01/01 - 1964/12/31: 7684
Papers found for this year 1965/01/01 - 1965/12/31: 4656
Papers found for this year 1966/01/01 - 1966/12/31: 2456
INFO:pymed_paperscraper.api:ChunkedEncodingError: Response ended prematurely.	Now at 1 attempts for ['5627048', '5626798', '5624631', '5623845', '5623837', '5623834', '5623831', '5623825', '5623824', '5622862', '5621439', '5621423', '5621356', '5621354', '5621353', '5618717', '5618714', '5614074', '5611523', '5611518', '5610193', '5610192', '5608002', '5608001', '5607998', '5607997', '5607996', '5607994', '5606850', '5606849', '5606848', '5606668', '5600276', '5600272', '5599398', '5599390', '5597996', '5591666', '5587987', '5586723', '5584584', '5584583', '5584488', '5583592', '5307814', '5302973', '5299648', '5299610', '5264189', '5261768', '5249322', '5235904', '5235890', '5186376', '4974097', '4965427', '4964289', '4884194', '4868664', '4865556', '4864061', '4861523', '4861456', '4297750', '4294443', '4232301', '4229733', '4229195', '4228902', '4228285', '4179653', '4179425', '4169223', '4168731', '4168725', '5630271', '5608973', '5606139', '5606136', '5606135', '5606131', '4884980', '6075015', '5607692', '5593948', '5593947', '6076691', '6056228', '6051463', '6048103', '4292695', '12389566', '6057943', '5589445', '5590752', '5590751', '5590745', '5623694', '6075820', '5614127', '5606436', '5606434', '5600277', '5590442', '5583552', '6047858', '4167271', '5632242', '4861369', '5625089', '5618773', '5618770', '6078662', '6061503', '6058327', '6054799', '5628070', '5605793', '5605787', '4875908', '4860722', '4167252', '6054478', '6054476', '5593584', '5342857', '6063018', '12275623', '6083347', '6078889', '6077653', '6077597', '6073756', '6073349', '6072695', '6072403', '6069933', '6069908', '6069676', '6069611', '6069602', '6066339', '6062538', '6062283', '6061647', '6061535', '6061097', '6058548', '6058543', '6058542', '6058536', '6058532', '6058531', '6058529', '6057987', '6057645', '6057644', '6056308', '6054122', '6054120', '6053784', '6053772', '6053704', '6050853', '6050177', '6047798', '6046554', '6045447', '6045446', '6042897', '6042893', '6042891', '6042889', '6042618', '6042613', '5633709', '5633221', '5631443', '5631348', '5629784', '5629620', '5628974', '5627446', '5626859', '5626858', '5626855', '5626583', '5626582', '5626581', '5620863', '5620496', '5619617', '5618908', '5618905', '5617285', '5617282', '5612263', '5612262', '5612261', '5610367', '5610148', '5607976', '5605982', '5605980', '5605747', '5602237', '5601809', '5601807', '5601321', '5598836', '5598830', '5596856', '5595312', '5591594', '5590572', '5587423', '5587420', '5585542', '5585541', '5585540', '5585537', '5583873', '5583872', '5583294', '5342864', '5299208', '5298770', '5258169', '5258112', '5235741', '5235416', '5189366', '4979195', '4974362', '4965473', '4965379', '4964119', '4902708', '4895264', '4873963', '4869553', '4865073', '4864284', '4864034', '4383938', '4314784', '4299638', '4298678', '4293316', '4232988']:
Papers found for this year 1967/01/01 - 1967/12/31: 2558
Papers found for this year 1968/01/01 - 1968/12/31: 2752
Papers found for this year 1969/01/01 - 1969/12/31: 2921
Papers found for this year 1970/01/01 - 1970/12/31: 2985
Papers found for this year 1971/01/01 - 1971/12/31: 3018
INFO:pymed_paperscraper.api:ChunkedEncodingError: Response ended prematurely.	Now at 1 attempts for ['4483269', '4483140', '4483107', '4482246', '4481770', '4338699', '4338448', '4337896', '4336938', '4263788', '4262646', '4260989', '4115641', '4115124', '4112000', '5080184', '5033074', '5031199', '5028350', '4555545', '4337948', '4113080', '17829288', '4537320', '5032141', '4340881', '4262180', '4260667', '4113927', '5021634', '5034219', '5037477', '4625102', '5050944', '5044570', '5025881', '5025877', '4660938', '4636265', '4554553', '4503222', '4263090', '5023924', '5023908', '4112213', '4112186', '17778174', '4554383', '4482134', '5072276', '5072275', '5063957', '12275891', '4336892', '5043995', '5026582', '4623745', '4112329', '5032353', '5020842', '4482127', '5015432', '5015430', '4625276', '5029615', '12337004', '12332876', '12256597', '12256464', '12256463', '5085150', '5078123', '5076525', '5075423', '5073645', '5072925', '5071776', '5071775', '5071133', '5071131', '5071130', '5071129', '5071128', '5071126', '5071125', '5071120', '5069067', '5065608', '5065498', '5063829', '5063784', '5063606', '5063346', '5063329', '5055817', '5054595', '5054594', '5051658', '5048508', '5048507', '5048118', '5048105', '5048104', '5048103', '5048102', '5048100', '5046050', '5046047', '5043473', '5042681', '5038988', '5038844', '5038771', '5038412', '5036601', '5036600', '5036502', '5034980', '5034979', '5034899', '5034824', '5034387', '5034381', '5034379', '5034377', '5034129', '5033558', '5032458', '5032452', '5032450', '5032449', '5032446', '5032445', '5031639', '5031615', '5031614', '5031540', '5030470', '5030371', '5030366', '5029771', '5029768', '5029767', '5029757', '5029756', '5029754', '5029402', '5028924', '5028821', '5028818', '5027975', '5027221', '5027214', '5027208', '5027207', '5027206', '5027205', '5027193', '5026691', '5026675', '5026363', '5025907', '5025717', '5025340', '5025339', '5025325', '5025003', '5025001', '5025000', '5024999', '5024998', '5024995', '5024994', '5024578', '5024569', '5024298', '5024297', '5024296', '5024294', '5024115', '5024056', '5023496', '5023495', '5023494', '5023493', '5023491', '5023259', '5023255', '5023250', '5023249', '5023113', '5022484', '5021933', '5020435', '5020432', '5012752', '5012747', '5012745', '5012730', '5012492', '4680272', '4676061', '4673445', '4672848', '4666529', '4664665', '4662885', '4662835', '4658566', '4658564', '4658078', '4656986', '4655928', '4655199', '4653137', '4651136', '4650657', '4646993', '4644154', '4643223', '4639926', '4639843', '4624165', '4623550', '4623540', '4623408', '4623164', '4603935', '4581208', '4568277', '4567443', '4565394', '4557005', '4556992', '4556147', '4556124', '4556060', '4555803', '4555346', '4555110', '4555072', '4554333', '4540181', '4537994', '4537546', '4537448', '4537350', '4537270', '4537259', '4521533']:
Papers found for this year 1972/01/01 - 1972/12/31: 3115
INFO:pymed_paperscraper.api:ChunkedEncodingError: Response ended prematurely.	Now at 1 attempts for ['4489864', '4363470', '4361226', '4357773', '4356455', '4355408', '4355125', '4353351', '4353349', '4272675', '4270280', '4270278', '4211093', '4204380', '4203981', '4203979', '4203977', '4201574', '4200066', '4198472', '4141773', '4131401', '4127423', '4126199', '4125355', '4125026', '4124993', '4755597', '4490910', '4356913', '4126737', '4773998', '4740610', '4728783', '4124949', '4124947', '4124936', '4124913', '4746518', '4727396', '4202966', '4790439', '4738162', '4742640', '4730196', '4730193', '4730185', '4581079', '4201618', '4124565', '4747806', '4718526', '4590356', '4737222', '4721145', '4721140', '4721138', '4578635', '4198457', '4129087', '4777959', '4744112', '4723812', '4542201', '4766369', '12333199', '4740533', '4354456', '4742637', '4728948', '4723471', '4723464', '4723458', '4721498', '4579291', '4353980', '4124439', '4718031', '12276814', '4803455', '4802819', '4802666', '4800719', '4800377', '4799446', '4799375', '4799341', '4798876', '4797832', '4796516', '4796515', '4795785', '4792857', '4792852', '4791570', '4790404', '4785323', '4777158', '4776407', '4771663', '4765996', '4765987', '4763130', '4763125', '4763124', '4761296', '4761220', '4759679', '4757579', '4757345', '4754479', '4753784', '4749863', '4747158', '4747156', '4747155', '4747152', '4743495', '4742370', '4742032', '4742031', '4742023', '4742022', '4741698', '4740588', '4733966', '4733965', '4733962', '4733961', '4733880', '4733547', '4733122', '4732258', '4732093', '4731503', '4731335', '4729615', '4729613', '4729016', '4729015', '4727365', '4726947', '4726904', '4726537', '4725958', '4725949', '4725947', '4725945', '4725944', '4725170', '4724234', '4722601', '4721414', '4721411', '4721201', '4721124', '4721063', '4719939', '4719545', '4719042', '4718913', '4718884', '4718869', '4718430', '4717724', '4717716', '4594295', '4591097', '4588098', '4585939', '4582581', '4580609', '4579077', '4578849', '4578538', '4578296', '4578295', '4577932', '4544911', '4541640', '4516046', '4492607', '4358206', '4354887', '4354400', '4354397', '4352601', '4352576', '4273630', '4273036', '4198916', '4198122', '4140728', '4138688', '4126009', '4125963', '4124211', '4124208', '4124023', '4756073', '12306756', '12306755', '4740334', '4364781', '4724400', '4720610', '4720607', '4720606', '4718855', '4718850', '4542613', '4748458', '4732278', '4201250', '4127107', '4712998', '4268268', '4732714', '4748685', '4720768', '4720765', '4720762', '4720757', '4198366', '4124395', '4749158', '4717624', '4711347', '4353945', '4774638', '4728096', '4727688', '4727687', '4727686', '4715943', '4715941', '4715936', '4717849', '4717846', '4717845', '4353487', '4123622', '4123600', '4489527', '4730384', '4730380', '4787327', '4125950', '4793090', '4719850']:
Papers found for this year 1973/01/01 - 1973/12/31: 3458
Papers found for this year 1974/01/01 - 1974/12/31: 3493
INFO:pymed_paperscraper.api:ChunkedEncodingError: Response ended prematurely.	Now at 1 attempts for ['53391', '1183335', '814410', '810960', '1193519', '1193518', '1178004', '129769', '1242173', '1228441', '1183041', '126828', '52420', '15637883', '15637881', '1243166', '1243085', '1242825', '1242787', '1242570', '1242569', '1242568', '1242528', '1241803', '1241360', '1240117', '1240105', '1240087', '1239985', '1239211', '1239203', '1238106', '1238042', '1237819', '1237538', '1236625', '1235127', '1232622', '1229100', '1229092', '1228827', '1228464', '1227374', '1226852', '1224398', '1223902', '1223773', '1223524', '1223267', '1222904', '1222903', '1222203', '1222066', '1220378', '1219056', '1218309', '1218297', '1218266', '1218243', '1217606', '1217605', '1217604', '1217599', '1217598', '1217597', '1217596', '1217593', '1217591', '1216455', '1215927', '1215921', '1215914', '1215649', '1215545', '1215456', '1214037', '1213656', '1213080', '1213079', '1212612', '1211694', '1211411', '1211279', '1210795', '1210794', '1210792', '1210514', '1210509', '1210468', '1210342', '1209691', '1209687', '1209646', '1208549', '1207313', '1206658', '1206628', '1206626', '1206420', '1206277', '1206274', '1205814', '1205725', '1204660', '1203917', '1203177', '1202912', '1202656', '1202654', '1202478', '1202404', '1202401', '1202396', '1201966', '1201657', '1201626', '1201526', '1201469', '1201261', '1201106', '1201105', '1201104', '1200820', '1200815', '1200511', '1200508', '1200494', '1200038', '1200036', '1199937', '1199712', '1198636', '1198632', '1198018', '1198016', '1198014', '1198013', '1198011', '1198009', '1198008', '1196852', '1196735', '1196701', '1196570', '1196567', '1196566', '1196563', '1196557', '1195011', '1194471', '1194314', '1193404', '1193401', '1193400', '1193399', '1193398', '1193361', '1193358', '1193357', '1193353', '1193352', '1192920', '1192619', '1192522', '1192521', '1192359', '1192217', '1192030', '1192013', '1191607', '1191606', '1191604', '1191602', '1191601', '1191600', '1191599', '1191598', '1191022', '1190928', '1190171', '1190110', '1190099', '1189940', '1189914', '1189913', '1189158', '1188429', '1188420', '1188392', '1187248', '1187075', '1187066', '1187064', '1187062', '1187058', '1186357', '1186353', '1185050', '1185049', '1183996', '1183640', '1183639', '1183638', '1183637', '1183634', '1183633', '1183404', '1183003', '1181958', '1181580', '1181575', '1181353', '1180295', '1180294', '1178873', '1175272', '1175269', '1175264', '1108503', '1107489', '1106743', '1106444', '1106425', '1106278', '1106277', '1106190', '1105432', '1104409', '1104372', '1103765', '1103609', '1103439', '1103022', '1103021', '1102731', '1082611', '1082214', '1081876', '1081865', '1081546', '1081099', '1080782', '1061561', '1060575', '1059276', '1059058', '1059020', '1059012', '1052856', '1046554']:
Papers found for this year 1975/01/01 - 1975/12/31: 5506
Papers found for this year 1976/01/01 - 1976/12/31: 5841
Papers found for this year 1977/01/01 - 1977/12/31: 6092
Papers found for this year 1978/01/01 - 1978/12/31: 6260
Papers found for this year 1979/01/01 - 1979/12/31: 7030
Papers found for this year 1980/01/01 - 1980/12/31: 7277
Papers found for this year 1981/01/01 - 1981/12/31: 7651
Papers found for this year 1982/01/01 - 1982/12/31: 8242
Papers found for this year 1983/01/01 - 1983/12/31: 9205
Total number of papers: 144053

In [146]:
print(final_df2)

                                                   title abstract  \
0                 Uterine Contractions during Pregnancy.     None
1      The Washington monument, and the lightning str...     None
2      THE WASHINGTON MONUMENT, AND THE LIGHTNING STR...     None
3      Detachment of the Retina in both Eyes with Alb...     None
4                                    A Lightning Stroke.     None
...                                                  ...      ...
30657  [Some data on the functional state of the live...      NaN
30658  [Fetal masculinization produced by sex steroid...      NaN
30659                           [Anemias in obstetrics].      NaN
30660  [On pregnancy of the rudimentary accessory cor...      NaN
30661  Some comments on the relationship of the distr...      NaN

                                                 journal        date  \
0                      Journal of anatomy and physiology  1871-11-01
1                               Science (New York, N.Y.)  1885-07-24
2                               Science (New York, N.Y.)  1885-06-26
3      Transactions of the American Ophthalmological ...  1887-01-01
4                               Science (New York, N.Y.)  1892-01-29
...                                                  ...         ...
30657  Zhurnal nevropatologii i psikhiatrii imeni S.S...  1960-01-01
30658  Revista de obstetricia y ginecologia de Venezuela  1960-01-01
30659  Revista de obstetricia y ginecologia de Venezuela  1960-01-01
30660       Zeitschrift fur Geburtshilfe und Gynakologie  1960-01-01
30661       Acta psychiatrica Scandinavica. Supplementum  1960-01-01

                                    authors  \
0                                        []
1                                [M CMeigs]
2                                   [NoneM]
3                            [O FWadsworth]
4                                      [JH]
...                                     ...
30657           [M AAKSIANTSEV, P IVLASOVA]
30658                             [OAGUERO]
30659                  [OAGUERO, MLAYRISSE]
30660                         [MACS, BTOTH]
30661  [E DACHESON, C ABACHRACH, F MWRIGHT]

                                      doi
0                                    None
1           10.1126/science.ns-6.129.63-a
2            10.1126/science.ns-5.125.517
3                                    None
4            10.1126/science.ns-19.469.66
...                                   ...
30657                                 NaN
30658                                 NaN
30659                                 NaN
30660                                 NaN
30661  10.1111/j.1600-0447.1960.tb08674.x

[30662 rows x 6 columns]

In [ ]:
#######################################################################################################################################

In [ ]:
#######################################################################################################################################

In [151]:
# FIRST SET OF KEYWORDS 
# PER MONTH
######## 1984 - 2000 ###########

keywords_df1 = ["Abdominal cerclage", "Abnormal pap smears", "Abnormal uterine bleeding",  "Alzheimer's disease", "Amenorrhea",
            "Amniocentesis", "Arthritis", "Asthma", "Bacterial vaginosis", "Bleeding disorders", "Breast cancer", "Cancers",
            "Celiac disease", "Cervical cancer", "Cervical insufficiency", "Cervicitis", "Cesarean section (C-section)",
            "Chorionic villus sampling", "Colposcopy", "Congenital abnormalities", "Continence", "Contraception (birth control)",
            "Cystoscopy", "Depression and anxiety", "Dilation and curettage (D and C)", "Dysmenorrhea",  "Endometrial ablation",  "Endometrial biopsy",
            "Endometrial cancer", "Endometriosis", "Epilepsy", "Family planning", "Female genital cutting", "Fertility preservation",
            "Fibroma", "Gallstone disease",  "Genetic conditions", "Gentle cesarean section", "Gestational diabetes", "Gestational trophoblastic disease",
            "Graves' disease", "Gynecologic cancer", "Gynecologic specialty care", "Gynecologic well-woman care", "Gynecological surgery",  "Heart disease",
             "Heavy menstrual cycles", "High-risk pregnancy","HIV", "HPV", "In-vitro fertilization", "Infertility", "Integrative medicine", "Interstitial cystitis",
             "Irritable bowel syndrome (IBS)", "Laparoscopic hysterectomy", "Laparoscopy", "Loop electrosurgical excision procedure (LEEP)"
]

Entrez.email = "sebrodnick@willamette.edu"  # this identifies who is pulling and lessen 429 errors for pulling

keywords_joined = " OR ".join(f'"{word}"[Title/abstract]' for word in keywords_df1)

start_date = datetime(1984, 1, 1)
end_date = datetime(2000, 12, 31)

# List to hold dfs for each day
dfs_list = []
# Loop through each day
current_date = start_date

while current_date <= end_date:
    last_day = calendar.monthrange(current_date.year, current_date.month)[1]
    start_str = current_date.strftime("%Y/%m/01")
    end_str = current_date.strftime(f"%Y/%m/{last_day}")
    month_query = f'("{start_str}"[Date - Create] : "{end_str}"[Date - Create]) AND ({keywords_joined})'

    try:
        df = get_pubmed_papers(query = month_query, max_results = 9998)
        if df is not None and not df.empty:
            dfs_list.append(df)
            print(f"Papers found for this year {start_str} - {end_str}: {len(df)}")

        else:
            print(f"No papers found for this month {start_str} - {end_str}")
    except Exception as e:
        print(f"Error getting papers for {start_str} - {end_str}: {e}")

    time.sleep(3) # This will pause (3 seconds) between each loop, this will also help with 429 errors 
    
    if current_date.month == 12:
        current_date = datetime(current_date.year + 1, 1, 1)
    else:
        current_date = datetime(current_date.year, current_date.month + 1, 1)

if dfs_list:
    final_df = pd.concat(dfs_list, ignore_index=True)
    print(f"Total number of papers: {len(final_df)}")

else:
    print("No data collected")
    final_df = pd.DataFrame()

Papers found for this year 1984/01/01 - 1984/01/31: 2705
Papers found for this year 1984/02/01 - 1984/02/29: 714
Papers found for this year 1984/03/01 - 1984/03/31: 679
Papers found for this year 1984/04/01 - 1984/04/30: 762
Papers found for this year 1984/05/01 - 1984/05/31: 690
Papers found for this year 1984/06/01 - 1984/06/30: 719
Papers found for this year 1984/07/01 - 1984/07/31: 706
Papers found for this year 1984/08/01 - 1984/08/31: 590
Papers found for this year 1984/09/01 - 1984/09/30: 795
Papers found for this year 1984/10/01 - 1984/10/31: 702
Papers found for this year 1984/11/01 - 1984/11/30: 678
Papers found for this year 1984/12/01 - 1984/12/31: 746
Papers found for this year 1985/01/01 - 1985/01/31: 2823
Papers found for this year 1985/02/01 - 1985/02/28: 596
Papers found for this year 1985/03/01 - 1985/03/31: 758
Papers found for this year 1985/04/01 - 1985/04/30: 714
Papers found for this year 1985/05/01 - 1985/05/31: 786
Papers found for this year 1985/06/01 - 1985/06/30: 733
Papers found for this year 1985/07/01 - 1985/07/31: 824
Papers found for this year 1985/08/01 - 1985/08/31: 607
Papers found for this year 1985/09/01 - 1985/09/30: 789
Papers found for this year 1985/10/01 - 1985/10/31: 738
Papers found for this year 1985/11/01 - 1985/11/30: 801
Papers found for this year 1985/12/01 - 1985/12/31: 822
Papers found for this year 1986/01/01 - 1986/01/31: 3117
Papers found for this year 1986/02/01 - 1986/02/28: 721
Papers found for this year 1986/03/01 - 1986/03/31: 851
Papers found for this year 1986/04/01 - 1986/04/30: 801
Papers found for this year 1986/05/01 - 1986/05/31: 764
Papers found for this year 1986/06/01 - 1986/06/30: 780
Papers found for this year 1986/07/01 - 1986/07/31: 820
Papers found for this year 1986/08/01 - 1986/08/31: 768
Papers found for this year 1986/09/01 - 1986/09/30: 900
Papers found for this year 1986/10/01 - 1986/10/31: 806
Papers found for this year 1986/11/01 - 1986/11/30: 975
Papers found for this year 1986/12/01 - 1986/12/31: 847
Papers found for this year 1987/01/01 - 1987/01/31: 3658
Papers found for this year 1987/02/01 - 1987/02/28: 809
Papers found for this year 1987/03/01 - 1987/03/31: 978
Papers found for this year 1987/04/01 - 1987/04/30: 889
Papers found for this year 1987/05/01 - 1987/05/31: 953
Papers found for this year 1987/06/01 - 1987/06/30: 939
Papers found for this year 1987/07/01 - 1987/07/31: 1002
Papers found for this year 1987/08/01 - 1987/08/31: 921
Papers found for this year 1987/09/01 - 1987/09/30: 1067
Papers found for this year 1987/10/01 - 1987/10/31: 1099
Papers found for this year 1987/11/01 - 1987/11/30: 1001
Papers found for this year 1987/12/01 - 1987/12/31: 992
Papers found for this year 1988/01/01 - 1988/01/31: 4331
Papers found for this year 1988/02/01 - 1988/02/29: 949
Papers found for this year 1988/03/01 - 1988/03/31: 1133
Papers found for this year 1988/04/01 - 1988/04/30: 1118
Papers found for this year 1988/05/01 - 1988/05/31: 1078
Papers found for this year 1988/06/01 - 1988/06/30: 1179
Papers found for this year 1988/07/01 - 1988/07/31: 1192
Papers found for this year 1988/08/01 - 1988/08/31: 1034
Papers found for this year 1988/09/01 - 1988/09/30: 1214
Papers found for this year 1988/10/01 - 1988/10/31: 1236
Papers found for this year 1988/11/01 - 1988/11/30: 1001
Papers found for this year 1988/12/01 - 1988/12/31: 1254
Papers found for this year 1989/01/01 - 1989/01/31: 5145
Papers found for this year 1989/02/01 - 1989/02/28: 1188
Papers found for this year 1989/03/01 - 1989/03/31: 1375
Papers found for this year 1989/04/01 - 1989/04/30: 1278
Papers found for this year 1989/05/01 - 1989/05/31: 1329
Papers found for this year 1989/06/01 - 1989/06/30: 1382
Papers found for this year 1989/07/01 - 1989/07/31: 1396
Papers found for this year 1989/08/01 - 1989/08/31: 1191
Papers found for this year 1989/09/01 - 1989/09/30: 1487
Papers found for this year 1989/10/01 - 1989/10/31: 1309
Papers found for this year 1989/11/01 - 1989/11/30: 1442
Papers found for this year 1989/12/01 - 1989/12/31: 1332
Papers found for this year 1990/01/01 - 1990/01/31: 5387
Papers found for this year 1990/02/01 - 1990/02/28: 1382
Papers found for this year 1990/03/01 - 1990/03/31: 1475
Papers found for this year 1990/04/01 - 1990/04/30: 1429
Papers found for this year 1990/05/01 - 1990/05/31: 1336
Papers found for this year 1990/06/01 - 1990/06/30: 1489
Papers found for this year 1990/07/01 - 1990/07/31: 1483
Papers found for this year 1990/08/01 - 1990/08/31: 1261
Papers found for this year 1990/09/01 - 1990/09/30: 1626
Papers found for this year 1990/10/01 - 1990/10/31: 1495
Papers found for this year 1990/11/01 - 1990/11/30: 1512
Papers found for this year 1990/12/01 - 1990/12/31: 1566
Papers found for this year 1991/01/01 - 1991/01/31: 5710
Papers found for this year 1991/02/01 - 1991/02/28: 1399
Papers found for this year 1991/03/01 - 1991/03/31: 1617
Papers found for this year 1991/04/01 - 1991/04/30: 1495
Papers found for this year 1991/05/01 - 1991/05/31: 1521
Papers found for this year 1991/06/01 - 1991/06/30: 1559
Papers found for this year 1991/07/01 - 1991/07/31: 1636
Papers found for this year 1991/08/01 - 1991/08/31: 1395
Papers found for this year 1991/09/01 - 1991/09/30: 1730
Papers found for this year 1991/10/01 - 1991/10/31: 1456
Papers found for this year 1991/11/01 - 1991/11/30: 1617
Papers found for this year 1991/12/01 - 1991/12/31: 1629
Papers found for this year 1992/01/01 - 1992/01/31: 5724
Papers found for this year 1992/02/01 - 1992/02/29: 1551
Papers found for this year 1992/03/01 - 1992/03/31: 1782
Papers found for this year 1992/04/01 - 1992/04/30: 1773
Papers found for this year 1992/05/01 - 1992/05/31: 1771
Papers found for this year 1992/06/01 - 1992/06/30: 1776
Papers found for this year 1992/07/01 - 1992/07/31: 1766
Papers found for this year 1992/08/01 - 1992/08/31: 1537
Papers found for this year 1992/09/01 - 1992/09/30: 1929
Papers found for this year 1992/10/01 - 1992/10/31: 1723
Papers found for this year 1992/11/01 - 1992/11/30: 1792
Papers found for this year 1992/12/01 - 1992/12/31: 1622
Papers found for this year 1993/01/01 - 1993/01/31: 5567
Papers found for this year 1993/02/01 - 1993/02/28: 1610
Papers found for this year 1993/03/01 - 1993/03/31: 2041
Papers found for this year 1993/04/01 - 1993/04/30: 1797
Papers found for this year 1993/05/01 - 1993/05/31: 1893
Papers found for this year 1993/06/01 - 1993/06/30: 1884
Papers found for this year 1993/07/01 - 1993/07/31: 1839
Papers found for this year 1993/08/01 - 1993/08/31: 1544
Papers found for this year 1993/09/01 - 1993/09/30: 1979
Papers found for this year 1993/10/01 - 1993/10/31: 1826
Papers found for this year 1993/11/01 - 1993/11/30: 1960
Papers found for this year 1993/12/01 - 1993/12/31: 1825
Papers found for this year 1994/01/01 - 1994/01/31: 5751
Papers found for this year 1994/02/01 - 1994/02/28: 1713
Papers found for this year 1994/03/01 - 1994/03/31: 2117
Papers found for this year 1994/04/01 - 1994/04/30: 1861
Papers found for this year 1994/05/01 - 1994/05/31: 2032
Papers found for this year 1994/06/01 - 1994/06/30: 1964
Papers found for this year 1994/07/01 - 1994/07/31: 1998
Papers found for this year 1994/08/01 - 1994/08/31: 1908
Papers found for this year 1994/09/01 - 1994/09/30: 2081
Papers found for this year 1994/10/01 - 1994/10/31: 1980
Papers found for this year 1994/11/01 - 1994/11/30: 1974
Papers found for this year 1994/12/01 - 1994/12/31: 2020
Papers found for this year 1995/01/01 - 1995/01/31: 5511
Papers found for this year 1995/02/01 - 1995/02/28: 1913
Papers found for this year 1995/03/01 - 1995/03/31: 2224
Papers found for this year 1995/04/01 - 1995/04/30: 2108
Papers found for this year 1995/05/01 - 1995/05/31: 2117
Papers found for this year 1995/06/01 - 1995/06/30: 2073
Papers found for this year 1995/07/01 - 1995/07/31: 2301
Papers found for this year 1995/08/01 - 1995/08/31: 1932
Papers found for this year 1995/09/01 - 1995/09/30: 2329
Papers found for this year 1995/10/01 - 1995/10/31: 2096
Papers found for this year 1995/11/01 - 1995/11/30: 2227
Papers found for this year 1995/12/01 - 1995/12/31: 2141
Papers found for this year 1996/01/01 - 1996/01/31: 5627
Papers found for this year 1996/02/01 - 1996/02/29: 2119
Papers found for this year 1996/03/01 - 1996/03/31: 2445
Papers found for this year 1996/04/01 - 1996/04/30: 2187
Papers found for this year 1996/05/01 - 1996/05/31: 2315
Papers found for this year 1996/06/01 - 1996/06/30: 2237
Papers found for this year 1996/07/01 - 1996/07/31: 2277
Papers found for this year 1996/08/01 - 1996/08/31: 2235
Papers found for this year 1996/09/01 - 1996/09/30: 2408
Papers found for this year 1996/10/01 - 1996/10/31: 2422
Papers found for this year 1996/11/01 - 1996/11/30: 2428
Papers found for this year 1996/12/01 - 1996/12/31: 2357
Papers found for this year 1997/01/01 - 1997/01/31: 5855
Papers found for this year 1997/02/01 - 1997/02/28: 2148
Papers found for this year 1997/03/01 - 1997/03/31: 2487
Papers found for this year 1997/04/01 - 1997/04/30: 2396
Papers found for this year 1997/05/01 - 1997/05/31: 2547
Papers found for this year 1997/06/01 - 1997/06/30: 2350
Papers found for this year 1997/07/01 - 1997/07/31: 2464
Papers found for this year 1997/08/01 - 1997/08/31: 2116
Papers found for this year 1997/09/01 - 1997/09/30: 803
Papers found for this year 1997/10/01 - 1997/10/31: 1358
Papers found for this year 1997/11/01 - 1997/11/30: 1629
Papers found for this year 1997/12/01 - 1997/12/31: 1595
Papers found for this year 1998/01/01 - 1998/01/31: 1713
Papers found for this year 1998/02/01 - 1998/02/28: 2213
Papers found for this year 1998/03/01 - 1998/03/31: 2437
Papers found for this year 1998/04/01 - 1998/04/30: 2612
Papers found for this year 1998/05/01 - 1998/05/31: 3064
Papers found for this year 1998/06/01 - 1998/06/30: 3075
Papers found for this year 1998/07/01 - 1998/07/31: 2833
Papers found for this year 1998/08/01 - 1998/08/31: 2673
Papers found for this year 1998/09/01 - 1998/09/30: 2051
Papers found for this year 1998/10/01 - 1998/10/31: 2998
Papers found for this year 1998/11/01 - 1998/11/30: 2571
Papers found for this year 1998/12/01 - 1998/12/31: 2653
Papers found for this year 1999/01/01 - 1999/01/31: 2390
Papers found for this year 1999/02/01 - 1999/02/28: 2447
Papers found for this year 1999/03/01 - 1999/03/31: 2800
Papers found for this year 1999/04/01 - 1999/04/30: 2891
Papers found for this year 1999/05/01 - 1999/05/31: 2851
Papers found for this year 1999/06/01 - 1999/06/30: 2662
Papers found for this year 1999/07/01 - 1999/07/31: 3176
Papers found for this year 1999/08/01 - 1999/08/31: 2827
Papers found for this year 1999/09/01 - 1999/09/30: 2630
Papers found for this year 1999/10/01 - 1999/10/31: 2643
Papers found for this year 1999/11/01 - 1999/11/30: 2531
INFO:pymed_paperscraper.api:ChunkedEncodingError: Response ended prematurely.	Now at 1 attempts for ['10597772', '10597771', '10597760', '10597756', '10597746', '10597744', '10597740', '10597733', '10597729', '10597692', '10597585', '10597570', '10597403', '10597384', '10597335', '10597321', '10597320', '10597313', '10597312', '10597311', '10597304', '10597299', '10597289', '10597287', '10597280', '10597275', '10597274', '10597269', '10597264', '10597263', '10597254', '10597247', '10597244', '10597236', '10597234', '10597224', '10597221', '10597214', '10597213', '10597208', '10597201', '10597197', '10597189', '10597188', '10597187', '10597185', '10597183', '10597126', '10597104', '10597094', '10597090', '10597087', '10597081', '10597064', '10597062', '10597014', '10596968', '10596965', '10596925', '10596908', '10596883', '10596854', '10596848', '10596840', '10596797', '10596778', '10596763', '10596761', '10596755', '10596717', '10596716', '10596715', '10596712', '10596698', '10596693', '10596691', '10596690', '10596689', '10596688', '10596687', '10596686', '10596685', '10596684', '10596678', '10596677', '10596676', '10596580', '10596568', '10596559', '10596543', '10596517', '10596487', '10596444', '10596417', '10596365', '10596340', '10596330', '10596328', '10596323', '10596322', '10596317', '10596313', '10596306', '10596291', '10596281', '10596266', '10596229', '10596033', '10596032', '10596031', '10596030', '10596029', '10554374', '10554369', '10554105', '10554051', '10554043', '10554038', '10554029', '10554024', '10554021', '10554019', '10554015', '10554013', '10554010', '10554009', '10554005', '10553981', '10553979', '10553967', '10553924', '10553690', '10553677', '10553632', '10553629', '10553628', '10553627', '10553623', '10553582', '10553579', '10553570', '10553568', '10553539', '10553536', '10553497', '10553494', '10553493', '10553275', '10553208', '10553198', '10553022', '10553004', '10552989', '10539869', '10596022', '10596021', '10596019', '10595966', '10595962', '10595944', '10595940', '10595937', '10595936', '10595935', '10595930', '10595922', '10595914', '10595909', '10595907', '10595878', '10595869', '10595868', '10595864', '10595835', '10595827', '10595815', '10595802', '10595771', '10595734', '10595689', '10595684', '10595683', '10595671', '10595633', '10595596', '10595550', '10595530', '10595524', '10595506', '10595464', '10595456', '10595452', '10595403', '10595395', '10595385', '10595334', '10595333', '10595289', '10595288', '10595280', '10595279', '10595278', '10595276', '10595275', '10595273', '10595270', '10595267', '10595266', '10595265', '10595263', '10595262', '10595259', '10595257', '10595254', '10595253', '10595252', '10595248', '10595247', '10595178', '10595165', '10595148', '10595146', '10595056', '10594971', '10594956', '10594954', '10594949', '10594938', '10594926', '10594868', '10594867', '10594861', '10594844', '10594838', '10594796', '10594755', '10594700', '10594667', '10594585', '10594566', '10594560', '10594545', '10594542', '10594541', '10594539', '10594530', '10594513', '10594505', '10594484', '10594477']:
Papers found for this year 1999/12/01 - 1999/12/31: 2700
Papers found for this year 2000/01/01 - 2000/01/31: 2609
Papers found for this year 2000/02/01 - 2000/02/29: 2806
Papers found for this year 2000/03/01 - 2000/03/31: 3347
Papers found for this year 2000/04/01 - 2000/04/30: 2805
Papers found for this year 2000/05/01 - 2000/05/31: 2704
Papers found for this year 2000/06/01 - 2000/06/30: 3324
Papers found for this year 2000/07/01 - 2000/07/31: 2692
Papers found for this year 2000/08/01 - 2000/08/31: 3591
Papers found for this year 2000/09/01 - 2000/09/30: 2950
Papers found for this year 2000/10/01 - 2000/10/31: 2733
Papers found for this year 2000/11/01 - 2000/11/30: 3135
Papers found for this year 2000/12/01 - 2000/12/31: 2271
Total number of papers: 392808

In [ ]:
print(final_df)

In [ ]:
#######################################################################################################################################

In [152]:
# SECOND SET OF KEYWORDS 
# PER MONTH
######## 1984 - 2000 ###########

keywords_df2 = ["Lupus", "Menopause", "Menorrhagia", "Menstrual conditions", "Miscarriage", "Morning sickness", "Multiple sclerosis", "Myomectomy", "Osteoarthritis", "Osteoporosis",
             "Ovarian cancer", "Ovarian cysts", "Ovarian fibroma", "Overactive bladder", "Pancreatic cystic neoplasm", "Pap test", "Pelvic inflammatory disease (PID)",
             "Pelvic organ prolapse", "Pelvic pain", "Pelvic ultrasound", "Perimenopause", "Placenta accreta", "Placenta previa", "Polycystic ovary syndrome (PCOS)",
             "Postpartum depression", "Preconception planning", "Pregnancy", "Pregnancy complications", "Pregnancy, first trimester", "Pregnancy, multiples",
             "Pregnancy, second trimester", "Pregnancy, third trimester", "Premenstrual dysphoric disorder (PMDD)", "Premenstrual syndrome (PMS)", "Prenatal care", "Prenatal genetic screening", 
             "Preterm birth", "Primary care for women", "Recurrent pregnancy loss", "Rheumatoid arthritis", "Robotic hysterectomy", "Robotic myomectomy", "Sexually transmitted diseases (STDs)", 
             "Sleep disorders", "Small vessel disease", "Sports injuries", "STIs", "Stress urinary incontinence", "Stroke", "Thyroid disease", "Transgender care", "Tubal ligation",
             "Turner syndrome", "Type I autoimmune hepatitis", "Ultrasound", "Urinary incontinence", "Urinary tract infections (UTIs)", "Uterine and vaginal prolapse", "Uterine fibroids",
             "Vaginal birth after cesarean section", "Vaginal cancer", "Vaginitis", "Vulvar cancer", "Vulvar dysplasia", "Vulvitis", "Yeast infection"
]

Entrez.email = "sebrodnick@willamette.edu"  # this identifies who is pulling and lessen 429 errors for pulling

keywords_joined22 = " OR ".join(f'"{word}"[Title/abstract]' for word in keywords_df2)

start_date22 = datetime(1984, 1, 1)
end_date22 = datetime(2000, 12, 31)

# List to hold dfs for each day
dfs_list22 = []
# Loop through each day
current_date22 = start_date22

while current_date22 <= end_date22:
    last_day22 = calendar.monthrange(current_date22.year, current_date22.month)[1]
    start_str22 = current_date22.strftime("%Y/%m/01")
    end_str22 = current_date22.strftime(f"%Y/%m/{last_day22}")
    month_query22 = f'("{start_str22}"[Date - Create] : "{end_str22}"[Date - Create]) AND ({keywords_joined22})'

    try:
        df22 = get_pubmed_papers(query = month_query22, max_results = 9998)
        if df22 is not None and not df22.empty:
            dfs_list22.append(df22)
            print(f"Papers found for this year {start_str22} - {end_str22}: {len(df22)}")

        else:
            print(f"No papers found for this month {start_str22} - {end_str22}")
    except Exception as e:
        print(f"Error getting papers for {start_str22} - {end_str22}: {e}")

    time.sleep(3) # This will pause (3 seconds) between each loop, this will also help with 429 errors 
    
    if current_date22.month == 12:
        current_date22 = datetime(current_date22.year + 1, 1, 1)
    else:
        current_date22 = datetime(current_date22.year, current_date22.month + 1, 1)

if dfs_list22:
    final_df22 = pd.concat(dfs_list22, ignore_index=True)
    print(f"Total number of papers: {len(final_df22)}")

else:
    print("No data collected")
    final_df22 = pd.DataFrame()

Papers found for this year 1984/01/01 - 1984/01/31: 2489
Papers found for this year 1984/02/01 - 1984/02/29: 580
Papers found for this year 1984/03/01 - 1984/03/31: 760
Papers found for this year 1984/04/01 - 1984/04/30: 655
Papers found for this year 1984/05/01 - 1984/05/31: 664
Papers found for this year 1984/06/01 - 1984/06/30: 701
Papers found for this year 1984/07/01 - 1984/07/31: 716
Papers found for this year 1984/08/01 - 1984/08/31: 562
Papers found for this year 1984/09/01 - 1984/09/30: 750
Papers found for this year 1984/10/01 - 1984/10/31: 674
Papers found for this year 1984/11/01 - 1984/11/30: 665
Papers found for this year 1984/12/01 - 1984/12/31: 635
Papers found for this year 1985/01/01 - 1985/01/31: 2618
Papers found for this year 1985/02/01 - 1985/02/28: 633
Papers found for this year 1985/03/01 - 1985/03/31: 767
Papers found for this year 1985/04/01 - 1985/04/30: 625
Papers found for this year 1985/05/01 - 1985/05/31: 665
Papers found for this year 1985/06/01 - 1985/06/30: 666
Papers found for this year 1985/07/01 - 1985/07/31: 739
Papers found for this year 1985/08/01 - 1985/08/31: 605
Papers found for this year 1985/09/01 - 1985/09/30: 753
Papers found for this year 1985/10/01 - 1985/10/31: 739
Papers found for this year 1985/11/01 - 1985/11/30: 771
Papers found for this year 1985/12/01 - 1985/12/31: 702
Papers found for this year 1986/01/01 - 1986/01/31: 2699
Papers found for this year 1986/02/01 - 1986/02/28: 670
Papers found for this year 1986/03/01 - 1986/03/31: 776
Papers found for this year 1986/04/01 - 1986/04/30: 786
Papers found for this year 1986/05/01 - 1986/05/31: 727
Papers found for this year 1986/06/01 - 1986/06/30: 759
Papers found for this year 1986/07/01 - 1986/07/31: 704
Papers found for this year 1986/08/01 - 1986/08/31: 662
Papers found for this year 1986/09/01 - 1986/09/30: 797
Papers found for this year 1986/10/01 - 1986/10/31: 754
Papers found for this year 1986/11/01 - 1986/11/30: 795
Papers found for this year 1986/12/01 - 1986/12/31: 690
Papers found for this year 1987/01/01 - 1987/01/31: 2968
Papers found for this year 1987/02/01 - 1987/02/28: 713
Papers found for this year 1987/03/01 - 1987/03/31: 859
Papers found for this year 1987/04/01 - 1987/04/30: 791
Papers found for this year 1987/05/01 - 1987/05/31: 810
Papers found for this year 1987/06/01 - 1987/06/30: 847
Papers found for this year 1987/07/01 - 1987/07/31: 828
Papers found for this year 1987/08/01 - 1987/08/31: 728
Papers found for this year 1987/09/01 - 1987/09/30: 876
Papers found for this year 1987/10/01 - 1987/10/31: 812
Papers found for this year 1987/11/01 - 1987/11/30: 807
Papers found for this year 1987/12/01 - 1987/12/31: 783
Papers found for this year 1988/01/01 - 1988/01/31: 3393
Papers found for this year 1988/02/01 - 1988/02/29: 723
Papers found for this year 1988/03/01 - 1988/03/31: 885
Papers found for this year 1988/04/01 - 1988/04/30: 832
Papers found for this year 1988/05/01 - 1988/05/31: 884
Papers found for this year 1988/06/01 - 1988/06/30: 841
Papers found for this year 1988/07/01 - 1988/07/31: 914
Papers found for this year 1988/08/01 - 1988/08/31: 792
Papers found for this year 1988/09/01 - 1988/09/30: 925
Papers found for this year 1988/10/01 - 1988/10/31: 887
Papers found for this year 1988/11/01 - 1988/11/30: 834
Papers found for this year 1988/12/01 - 1988/12/31: 835
Papers found for this year 1989/01/01 - 1989/01/31: 3687
Papers found for this year 1989/02/01 - 1989/02/28: 905
Papers found for this year 1989/03/01 - 1989/03/31: 1072
Papers found for this year 1989/04/01 - 1989/04/30: 1012
Papers found for this year 1989/05/01 - 1989/05/31: 1069
Papers found for this year 1989/06/01 - 1989/06/30: 1018
Papers found for this year 1989/07/01 - 1989/07/31: 1005
Papers found for this year 1989/08/01 - 1989/08/31: 882
Papers found for this year 1989/09/01 - 1989/09/30: 1073
Papers found for this year 1989/10/01 - 1989/10/31: 999
Papers found for this year 1989/11/01 - 1989/11/30: 1074
Papers found for this year 1989/12/01 - 1989/12/31: 964
Papers found for this year 1990/01/01 - 1990/01/31: 3814
Papers found for this year 1990/02/01 - 1990/02/28: 982
Papers found for this year 1990/03/01 - 1990/03/31: 1080
Papers found for this year 1990/04/01 - 1990/04/30: 1040
Papers found for this year 1990/05/01 - 1990/05/31: 1023
Papers found for this year 1990/06/01 - 1990/06/30: 1056
Papers found for this year 1990/07/01 - 1990/07/31: 1054
Papers found for this year 1990/08/01 - 1990/08/31: 905
Papers found for this year 1990/09/01 - 1990/09/30: 1105
Papers found for this year 1990/10/01 - 1990/10/31: 1079
Papers found for this year 1990/11/01 - 1990/11/30: 1055
INFO:pymed_paperscraper.api:ChunkedEncodingError: Response ended prematurely.	Now at 1 attempts for ['2282628', '2282207', '2282203', '2281995', '2281594', '2281565', '2281271', '2280440', '2280426', '2280238', '2280064', '2280050', '2280035', '2280007', '2279730', '2279639', '2279515', '2279511', '2279020', '2278405', '2278339', '2278327', '2277741', '2277404', '2277401', '2277400', '2277398', '2277395', '2277282', '2277279', '2277252', '2277251', '2277209', '2277207', '2277204', '2277203', '2277134', '2276976', '2276935', '2276309', '2276187', '2276047', '2276037', '2275558', '2274139', '2274126', '2274125', '2274076', '2274075', '2272881', '2272865', '2272797', '2272000', '2271843', '2270974', '2270972', '2270970', '2270969', '2270962', '2270473', '2270300', '2269898', '2268760', '2268220', '2268218', '2268106', '2266573', '2266242', '2265849', '2265837', '2265489', '2265488', '2265350', '2265334', '2265131', '2265117', '2265050', '2265043', '2264947', '2264083', '2264076', '2264074', '2264073', '2264071', '2263605', '2261720', '2261716', '2261009', '2261005', '2261001', '2260999', '2260997', '2260879', '2260686', '2260654', '2260637', '2260592', '2260546', '2260543', '2260542', '2260534', '2260157', '2260154', '2260153', '2260147', '2260146', '2260142', '2260132', '2259705', '2259547', '2259539', '2258631', '2258627', '2258086', '2258075', '2258074', '2258073', '2258072', '2258068', '2258065', '2258064', '2258063', '2257462', '2257461', '2257460', '2257459', '2257457', '2257452', '2257451', '2257450', '2257449', '2257448', '2257232', '2257224', '2257209', '2256762', '2256727', '2256698', '2256694', '2256576', '2256529', '2256515', '2256508', '2256505', '2256502', '2256500', '2256496', '2256495', '2256492', '2256489', '2256486', '2256485', '2256484', '2256483', '2256149', '2255222', '2255217', '2254843', '2254561', '2254554', '2254552', '2254546', '2254354', '2253894', '2253797', '2253796', '2253541', '2253371', '2253352', '2252456', '2252455', '2252121', '2252120', '2252115', '2252112', '2252102', '2252045', '2251619', '2251614', '2251604', '2251024', '2251021', '2250107', '2249642', '2248735', '2248184', '2247930', '2247913', '2247846', '2247832', '2247824', '2247823', '2247815', '2247248', '2247235', '2246968', '2246964', '2246913', '2246910', '2246697', '2246636', '2246563', '2246557', '2246036', '2246034', '2245860', '2245859', '2245858', '2245857', '2245847', '2245846', '2245845', '2245844', '2245837', '2245836', '2245835', '2245834', '2245833', '2245832', '2245828', '2245719', '2245702', '2245700', '2245606', '2245561', '2245557', '2245504', '2244776', '2244772', '2244641', '2244607', '2244606', '2244285', '2243997', '2243996', '2243990', '2243984', '2243982', '2243979', '2243977', '2243976', '2243970', '2243961', '2243959', '2243957', '2243751', '2243750', '2243409', '2243408', '2243407']:
Papers found for this year 1990/12/01 - 1990/12/31: 1023
Papers found for this year 1991/01/01 - 1991/01/31: 3740
Papers found for this year 1991/02/01 - 1991/02/28: 992
Papers found for this year 1991/03/01 - 1991/03/31: 1180
Papers found for this year 1991/04/01 - 1991/04/30: 998
Papers found for this year 1991/05/01 - 1991/05/31: 996
Papers found for this year 1991/06/01 - 1991/06/30: 1042
Papers found for this year 1991/07/01 - 1991/07/31: 1121
Papers found for this year 1991/08/01 - 1991/08/31: 953
Papers found for this year 1991/09/01 - 1991/09/30: 1132
Papers found for this year 1991/10/01 - 1991/10/31: 1088
Papers found for this year 1991/11/01 - 1991/11/30: 1075
Papers found for this year 1991/12/01 - 1991/12/31: 1121
Papers found for this year 1992/01/01 - 1992/01/31: 3571
Papers found for this year 1992/02/01 - 1992/02/29: 1033
Papers found for this year 1992/03/01 - 1992/03/31: 1202
Papers found for this year 1992/04/01 - 1992/04/30: 1162
Papers found for this year 1992/05/01 - 1992/05/31: 1220
Papers found for this year 1992/06/01 - 1992/06/30: 1145
Papers found for this year 1992/07/01 - 1992/07/31: 1201
Papers found for this year 1992/08/01 - 1992/08/31: 980
Papers found for this year 1992/09/01 - 1992/09/30: 1299
Papers found for this year 1992/10/01 - 1992/10/31: 1147
Papers found for this year 1992/11/01 - 1992/11/30: 1111
Papers found for this year 1992/12/01 - 1992/12/31: 1119
Papers found for this year 1993/01/01 - 1993/01/31: 3567
Papers found for this year 1993/02/01 - 1993/02/28: 1088
Papers found for this year 1993/03/01 - 1993/03/31: 1333
Papers found for this year 1993/04/01 - 1993/04/30: 1202
Papers found for this year 1993/05/01 - 1993/05/31: 1265
Papers found for this year 1993/06/01 - 1993/06/30: 1192
Papers found for this year 1993/07/01 - 1993/07/31: 1297
Papers found for this year 1993/08/01 - 1993/08/31: 979
Papers found for this year 1993/09/01 - 1993/09/30: 1396
Papers found for this year 1993/10/01 - 1993/10/31: 1228
Papers found for this year 1993/11/01 - 1993/11/30: 1301
Papers found for this year 1993/12/01 - 1993/12/31: 1204
Papers found for this year 1994/01/01 - 1994/01/31: 3614
Papers found for this year 1994/02/01 - 1994/02/28: 1126
Papers found for this year 1994/03/01 - 1994/03/31: 1350
Papers found for this year 1994/04/01 - 1994/04/30: 1146
Papers found for this year 1994/05/01 - 1994/05/31: 1311
INFO:pymed_paperscraper.api:HTTPError: 500 Server Error: Internal Server Error for url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?tool=paperscraper&email=abc%40def.gh&db=pubmed&id=8081592&id=8081591&id=8081590&id=8081532&id=8081526&id=8081519&id=8081518&id=8081517&id=8081516&id=8081513&id=8080927&id=8080920&id=8080916&id=8080914&id=8080909&id=8080710&id=8080706&id=8080643&id=8079669&id=8079666&id=8079663&id=8079656&id=8079652&id=8079017&id=8078634&id=8078189&id=8078019&id=8078016&id=8078004&id=8077979&id=8077976&id=8077975&id=8077973&id=8077972&id=8077845&id=8077832&id=8077824&id=8077823&id=8077821&id=8075882&id=8075862&id=8075657&id=8075654&id=8075475&id=8075355&id=8075311&id=8075244&id=8074980&id=8074909&id=8074833&id=8074365&id=8074340&id=8073980&id=8073976&id=8073968&id=8073953&id=8073376&id=8073322&id=8073317&id=8072598&id=8072238&id=8072236&id=8072234&id=8071800&id=8071796&id=8071731&id=8071509&id=8071165&id=8071162&id=8071161&id=8071070&id=8071031&id=8071025&id=8070283&id=8070260&id=8070258&id=8070231&id=8070146&id=8069991&id=8069744&id=8069733&id=8069336&id=8068977&id=8068966&id=8068836&id=8068435&id=8068434&id=8068427&id=8068169&id=8068157&id=8067932&id=8067723&id=8066531&id=8065807&id=8065736&id=8065728&id=8065724&id=8065718&id=8065079&id=8065078&id=8064005&id=8063949&id=8063935&id=8063928&id=8062634&id=8062509&id=8062481&id=8062373&id=8062363&id=8061807&id=8061805&id=8061797&id=8061586&id=8061558&id=8061266&id=8061263&id=8061262&id=8061261&id=8060250&id=8059320&id=8059307&id=8057957&id=8057820&id=8057815&id=8057409&id=8056479&id=8056364&id=8056361&id=8056360&id=8055243&id=8055237&id=8053833&id=8052935&id=8052933&id=8052932&id=8052931&id=8052930&id=8052929&id=8052928&id=8052927&id=8052926&id=8052925&id=8052924&id=8052923&id=8052112&id=8052111&id=8052021&id=8051532&id=8051530&id=8051528&id=8051495&id=8050872&id=8050774&id=8049981&id=8048824&id=8048810&id=8048033&id=8048030&id=8048021&id=8047575&id=8047348&id=8047304&id=8046155&id=8046041&id=8046040&id=8046038&id=8045999&id=8045993&id=8045072&id=8045070&id=8045069&id=8045061&id=8044589&id=8044369&id=8044368&id=8044360&id=8044186&id=8044183&id=8044179&id=8043342&id=8042487&id=8042486&id=8042483&id=8042472&id=8042471&id=8041867&id=8041650&id=8041061&id=8040629&id=8040627&id=8040625&id=8040622&id=8040620&id=8039777&id=8038975&id=8038974&id=8038418&id=8038417&id=8038415&id=8038409&id=8038406&id=8037980&id=8037504&id=8037500&id=8037499&id=8037498&id=8037497&id=8037496&id=8036646&id=8033454&id=8033453&id=8033452&id=8033450&id=8033448&id=8033446&id=8033445&id=8033444&id=8033443&id=8033441&id=8033370&id=8033369&id=8033367&id=8033362&id=8032868&id=8032847&id=8032816&id=8031707&id=8031506&id=8031417&id=8031402&id=8029164&id=8029161&id=8027414&id=8026817&id=8024912&id=8024910&id=8023924&id=8023392&id=8020817&id=8020816&id=8018650&id=8018648&id=8018645&id=8018635&id=8017450&id=8016797&id=8015683&id=8015677&id=8015289&id=8015285&retmode=xml.	Now at 1 attempts for ['8081592', '8081591', '8081590', '8081532', '8081526', '8081519', '8081518', '8081517', '8081516', '8081513', '8080927', '8080920', '8080916', '8080914', '8080909', '8080710', '8080706', '8080643', '8079669', '8079666', '8079663', '8079656', '8079652', '8079017', '8078634', '8078189', '8078019', '8078016', '8078004', '8077979', '8077976', '8077975', '8077973', '8077972', '8077845', '8077832', '8077824', '8077823', '8077821', '8075882', '8075862', '8075657', '8075654', '8075475', '8075355', '8075311', '8075244', '8074980', '8074909', '8074833', '8074365', '8074340', '8073980', '8073976', '8073968', '8073953', '8073376', '8073322', '8073317', '8072598', '8072238', '8072236', '8072234', '8071800', '8071796', '8071731', '8071509', '8071165', '8071162', '8071161', '8071070', '8071031', '8071025', '8070283', '8070260', '8070258', '8070231', '8070146', '8069991', '8069744', '8069733', '8069336', '8068977', '8068966', '8068836', '8068435', '8068434', '8068427', '8068169', '8068157', '8067932', '8067723', '8066531', '8065807', '8065736', '8065728', '8065724', '8065718', '8065079', '8065078', '8064005', '8063949', '8063935', '8063928', '8062634', '8062509', '8062481', '8062373', '8062363', '8061807', '8061805', '8061797', '8061586', '8061558', '8061266', '8061263', '8061262', '8061261', '8060250', '8059320', '8059307', '8057957', '8057820', '8057815', '8057409', '8056479', '8056364', '8056361', '8056360', '8055243', '8055237', '8053833', '8052935', '8052933', '8052932', '8052931', '8052930', '8052929', '8052928', '8052927', '8052926', '8052925', '8052924', '8052923', '8052112', '8052111', '8052021', '8051532', '8051530', '8051528', '8051495', '8050872', '8050774', '8049981', '8048824', '8048810', '8048033', '8048030', '8048021', '8047575', '8047348', '8047304', '8046155', '8046041', '8046040', '8046038', '8045999', '8045993', '8045072', '8045070', '8045069', '8045061', '8044589', '8044369', '8044368', '8044360', '8044186', '8044183', '8044179', '8043342', '8042487', '8042486', '8042483', '8042472', '8042471', '8041867', '8041650', '8041061', '8040629', '8040627', '8040625', '8040622', '8040620', '8039777', '8038975', '8038974', '8038418', '8038417', '8038415', '8038409', '8038406', '8037980', '8037504', '8037500', '8037499', '8037498', '8037497', '8037496', '8036646', '8033454', '8033453', '8033452', '8033450', '8033448', '8033446', '8033445', '8033444', '8033443', '8033441', '8033370', '8033369', '8033367', '8033362', '8032868', '8032847', '8032816', '8031707', '8031506', '8031417', '8031402', '8029164', '8029161', '8027414', '8026817', '8024912', '8024910', '8023924', '8023392', '8020817', '8020816', '8018650', '8018648', '8018645', '8018635', '8017450', '8016797', '8015683', '8015677', '8015289', '8015285']:
Papers found for this year 1994/06/01 - 1994/06/30: 1286
Papers found for this year 1994/07/01 - 1994/07/31: 1322
Papers found for this year 1994/08/01 - 1994/08/31: 1246
Papers found for this year 1994/09/01 - 1994/09/30: 1437
Papers found for this year 1994/10/01 - 1994/10/31: 1229
Papers found for this year 1994/11/01 - 1994/11/30: 1299
Papers found for this year 1994/12/01 - 1994/12/31: 1282
Papers found for this year 1995/01/01 - 1995/01/31: 3560
Papers found for this year 1995/02/01 - 1995/02/28: 1286
Papers found for this year 1995/03/01 - 1995/03/31: 1449
Papers found for this year 1995/04/01 - 1995/04/30: 1260
Papers found for this year 1995/05/01 - 1995/05/31: 1329
Papers found for this year 1995/06/01 - 1995/06/30: 1311
Papers found for this year 1995/07/01 - 1995/07/31: 1399
Papers found for this year 1995/08/01 - 1995/08/31: 1120
Papers found for this year 1995/09/01 - 1995/09/30: 1463
Papers found for this year 1995/10/01 - 1995/10/31: 1328
Papers found for this year 1995/11/01 - 1995/11/30: 1429
Papers found for this year 1995/12/01 - 1995/12/31: 1359
Papers found for this year 1996/01/01 - 1996/01/31: 3497
Papers found for this year 1996/02/01 - 1996/02/29: 1344
Papers found for this year 1996/03/01 - 1996/03/31: 1537
Papers found for this year 1996/04/01 - 1996/04/30: 1338
Papers found for this year 1996/05/01 - 1996/05/31: 1391
Papers found for this year 1996/06/01 - 1996/06/30: 1316
Papers found for this year 1996/07/01 - 1996/07/31: 1409
Papers found for this year 1996/08/01 - 1996/08/31: 1311
Papers found for this year 1996/09/01 - 1996/09/30: 1557
Papers found for this year 1996/10/01 - 1996/10/31: 1372
Papers found for this year 1996/11/01 - 1996/11/30: 1453
Papers found for this year 1996/12/01 - 1996/12/31: 1448
Papers found for this year 1997/01/01 - 1997/01/31: 4006
Papers found for this year 1997/02/01 - 1997/02/28: 1371
Papers found for this year 1997/03/01 - 1997/03/31: 1555
Papers found for this year 1997/04/01 - 1997/04/30: 1479
Papers found for this year 1997/05/01 - 1997/05/31: 1514
Papers found for this year 1997/06/01 - 1997/06/30: 1405
Papers found for this year 1997/07/01 - 1997/07/31: 1601
Papers found for this year 1997/08/01 - 1997/08/31: 1325
Papers found for this year 1997/09/01 - 1997/09/30: 507
Papers found for this year 1997/10/01 - 1997/10/31: 782
Papers found for this year 1997/11/01 - 1997/11/30: 1069
Papers found for this year 1997/12/01 - 1997/12/31: 1075
Papers found for this year 1998/01/01 - 1998/01/31: 1123
Papers found for this year 1998/02/01 - 1998/02/28: 1345
Papers found for this year 1998/03/01 - 1998/03/31: 1670
Papers found for this year 1998/04/01 - 1998/04/30: 1679
Papers found for this year 1998/05/01 - 1998/05/31: 1886
Papers found for this year 1998/06/01 - 1998/06/30: 1892
Papers found for this year 1998/07/01 - 1998/07/31: 1846
Papers found for this year 1998/08/01 - 1998/08/31: 1737
Papers found for this year 1998/09/01 - 1998/09/30: 1310
Papers found for this year 1998/10/01 - 1998/10/31: 1980
Papers found for this year 1998/11/01 - 1998/11/30: 1597
Papers found for this year 1998/12/01 - 1998/12/31: 1789
Papers found for this year 1999/01/01 - 1999/01/31: 1521
Papers found for this year 1999/02/01 - 1999/02/28: 1471
Papers found for this year 1999/03/01 - 1999/03/31: 1692
Papers found for this year 1999/04/01 - 1999/04/30: 1745
Papers found for this year 1999/05/01 - 1999/05/31: 1972
Papers found for this year 1999/06/01 - 1999/06/30: 1729
Papers found for this year 1999/07/01 - 1999/07/31: 2112
Papers found for this year 1999/08/01 - 1999/08/31: 1843
Papers found for this year 1999/09/01 - 1999/09/30: 1774
Papers found for this year 1999/10/01 - 1999/10/31: 1665
Papers found for this year 1999/11/01 - 1999/11/30: 1628
Papers found for this year 1999/12/01 - 1999/12/31: 1752
Papers found for this year 2000/01/01 - 2000/01/31: 1687
Papers found for this year 2000/02/01 - 2000/02/29: 1837
Papers found for this year 2000/03/01 - 2000/03/31: 2254
Papers found for this year 2000/04/01 - 2000/04/30: 1830
Papers found for this year 2000/05/01 - 2000/05/31: 2034
Papers found for this year 2000/06/01 - 2000/06/30: 2292
Papers found for this year 2000/07/01 - 2000/07/31: 1689
Papers found for this year 2000/08/01 - 2000/08/31: 2258
Papers found for this year 2000/09/01 - 2000/09/30: 1969

In [158]:
print(final_df22)

                                                    title  \
0       [Extracranial-intracranial arterial anastomosi...
1       Spatio-temporal processing in multiple sclerosis.
2       Normotensive and spontaneously-hypertensive ra...
3       [The change of fertility and factors impacting...
4       [Limitations of the indicator-total fertility-...
...                                                   ...
270512  Avoiding multiple pregnancies in ART: multiple...
270513  Risk-benefit decision making for treatment of ...
270514  Does selenium reduce the risk of threatened pr...
270515  Exposure to mercury in pregnant women from Alt...
270516                    Management of male infertility.

                                                 abstract  \
0                                                     NaN
1       The processing of spatial and temporal detail ...
2       The effect of arginine-vasopressin (AVP) on po...
3       In 1981 a 3% random sampling of women born bet...
4       Among all 1982 births in Chongwen District of ...
...                                                   ...
270512  Although most professional societies have issu...
270513  The Committee on Research on Psychiatric Treat...
270514  Selenium (Se), an essential trace element in h...
270515  The region of Alta Floresta in the South of th...
270516  The causes of infertility are known in a small...

                                                  journal        date  \
0        Polski tygodnik lekarski (Warsaw, Poland : 1960)  1984-01-30
1       Documenta ophthalmologica. Advances in ophthal...  1984-01-30
2                                          Brain research  1984-01-30
3                         Ren kou yan jiu = Renkou yanjiu  1984-01-29
4                         Ren kou yan jiu = Renkou yanjiu  1984-01-29
...                                                   ...         ...
270512               Human reproduction (Oxford, England)  2000-12-01
270513                 The American journal of psychiatry  2000-12-01
270514                             Environmental research  2000-12-01
270515                             Environmental research  2000-12-01
270516  Bailliere's best practice & research. Clinical...  2000-12-01

                                                  authors  \
0                                       [JOpara, RMrówka]
1       [M SMarx, J GMay, J LReed, H HMatteson, H Jvan...
2                     [C RGardner, M HRichards, JMöhring]
3                                             [FGao, XGu]
4                                              [NoneNone]
...                                                   ...
270512                                        [GPennings]
270513  [K LWisner, D AZarin, E SHolmboe, P SAppelbaum...
270514        [GHuel, DCampagna, FGirard, TMoreau, PBlot]
270515  [SHacon, EYokoo, JValente, R CCampos, V Ada Si...
270516                                         [H WBaker]

                                 doi
0                                NaN
1                 10.1007/BF00159076
2       10.1016/0006-8993(84)90891-6
3                                NaN
4                                NaN
...                              ...
270512     10.1093/humrep/15.12.2466
270513  10.1176/appi.ajp.157.12.1933
270514        10.1006/enrs.2000.4094
270515        10.1006/enrs.2000.4115
270516        10.1053/beem.2000.0088

[270517 rows x 6 columns]

In [ ]:
#########################################################################################################################################

In [161]:
# FOR FULL LIST OF KEYWORDS
# PER MONTH
###### 2001 - 2026

keywords_full = ["Abdominal cerclage", "Abnormal pap smears", "Abnormal uterine bleeding",  "Alzheimer's disease", "Amenorrhea",
            "Amniocentesis", "Arthritis", "Asthma", "Bacterial vaginosis", "Bleeding disorders", "Breast cancer", "Cancers",
            "Celiac disease", "Cervical cancer", "Cervical insufficiency", "Cervicitis", "Cesarean section (C-section)",
            "Chorionic villus sampling", "Colposcopy", "Congenital abnormalities", "Continence", "Contraception (birth control)",
            "Cystoscopy", "Depression and anxiety", "Dilation and curettage (D and C)", "Dysmenorrhea",  "Endometrial ablation",  "Endometrial biopsy",
            "Endometrial cancer", "Endometriosis", "Epilepsy", "Family planning", "Female genital cutting", "Fertility preservation",
            "Fibroma", "Gallstone disease",  "Genetic conditions", "Gentle cesarean section", "Gestational diabetes", "Gestational trophoblastic disease",
            "Graves' disease", "Gynecologic cancer", "Gynecologic specialty care", "Gynecologic well-woman care", "Gynecological surgery",  "Heart disease",
             "Heavy menstrual cycles", "High-risk pregnancy","HIV", "HPV", "In-vitro fertilization", "Infertility", "Integrative medicine", "Interstitial cystitis",
             "Irritable bowel syndrome (IBS)", "Laparoscopic hysterectomy", "Laparoscopy", "Loop electrosurgical excision procedure (LEEP)", "Lupus",
             "Menopause", "Menorrhagia", "Menstrual conditions", "Miscarriage", "Morning sickness", "Multiple sclerosis", "Myomectomy", "Osteoarthritis", "Osteoporosis",
             "Ovarian cancer", "Ovarian cysts", "Ovarian fibroma", "Overactive bladder", "Pancreatic cystic neoplasm", "Pap test", "Pelvic inflammatory disease (PID)",
             "Pelvic organ prolapse", "Pelvic pain", "Pelvic ultrasound", "Perimenopause", "Placenta accreta", "Placenta previa", "Polycystic ovary syndrome (PCOS)",
             "Postpartum depression", "Preconception planning", "Pregnancy", "Pregnancy complications", "Pregnancy, first trimester", "Pregnancy, multiples",
             "Pregnancy, second trimester", "Pregnancy, third trimester", "Premenstrual dysphoric disorder (PMDD)", "Premenstrual syndrome (PMS)", "Prenatal care", "Prenatal genetic screening", "Preterm birth",
             "Primary care for women", "Recurrent pregnancy loss", "Rheumatoid arthritis", "Robotic hysterectomy", "Robotic myomectomy", "Sexually transmitted diseases (STDs)", 
             "Sleep disorders", "Small vessel disease", "Sports injuries", "STIs", "Stress urinary incontinence", "Stroke", "Thyroid disease", "Transgender care", "Tubal ligation",
             "Turner syndrome", "Type I autoimmune hepatitis", "Ultrasound", "Urinary incontinence", "Urinary tract infections (UTIs)", "Uterine and vaginal prolapse", "Uterine fibroids",
             "Vaginal birth after cesarean section", "Vaginal cancer", "Vaginitis", "Vulvar cancer", "Vulvar dysplasia", "Vulvitis", "Yeast infection"
]

Entrez.email = "sebrodnick@willamette.edu"  

start_date11 = datetime(2001, 1, 1)
end_date11 = datetime(2026, 6, 27)


dfs_list11 = []
current_date11 = start_date11

while current_date11 <= end_date11:
    last_day11 = calendar.monthrange(current_date11.year, current_date11.month)[1]
    start_str11 = current_date11.strftime("%Y/%m/01")
    end_str11 = current_date11.strftime(f"%Y/%m/{last_day11}")

    for keyword in keywords_full:
        month_query11 = f'("{start_str11}"[Date - Create] : "{end_str11}"[Date - Create]) AND ({keyword})'
        
        try:
            df11 = get_pubmed_papers(query = month_query11, max_results = 9998)
            
            if df11 is not None and not df11.empty:
                dfs_list11.append(df11)
                print(f"Papers found for '{keyword}' for this year {start_str11} - {end_str11}: {len(df11)}")
                
            else:
                print(f"No papers found for '{keyword}' this month {start_str11} - {end_str11}")
                
        except Exception as e:
            print(f"Error getting papers for '{keyword}': {start_str11} - {end_str11}: {e}")
            
        time.sleep(1) 
        
    if current_date11.month == 12:
        current_date11 = datetime(current_date11.year + 1, 1, 1)
        
    else:
        current_date11 = datetime(current_date11.year, current_date11.month + 1, 1)

if dfs_list11:
    final_df11 = pd.concat(dfs_list11, ignore_index=True)
    print(f"Total number of papers: {len(final_df11)}")

else:
    print("No data collected")
    final_df11 = pd.DataFrame()

No papers found for 'Abdominal cerclage' this month 2001/01/01 - 2001/01/31
Papers found for 'Abnormal pap smears' for this year 2001/01/01 - 2001/01/31: 3
Papers found for 'Abnormal uterine bleeding' for this year 2001/01/01 - 2001/01/31: 6
Papers found for 'Alzheimer's disease' for this year 2001/01/01 - 2001/01/31: 149
Papers found for 'Amenorrhea' for this year 2001/01/01 - 2001/01/31: 11
Papers found for 'Amniocentesis' for this year 2001/01/01 - 2001/01/31: 8
Papers found for 'Arthritis' for this year 2001/01/01 - 2001/01/31: 266
Papers found for 'Asthma' for this year 2001/01/01 - 2001/01/31: 181
Papers found for 'Bacterial vaginosis' for this year 2001/01/01 - 2001/01/31: 9
Papers found for 'Bleeding disorders' for this year 2001/01/01 - 2001/01/31: 101
Papers found for 'Breast cancer' for this year 2001/01/01 - 2001/01/31: 355
Papers found for 'Cancers' for this year 2001/01/01 - 2001/01/31: 3190
Papers found for 'Celiac disease' for this year 2001/01/01 - 2001/01/31: 30
Papers found for 'Cervical cancer' for this year 2001/01/01 - 2001/01/31: 57
Papers found for 'Cervical insufficiency' for this year 2001/01/01 - 2001/01/31: 4
Papers found for 'Cervicitis' for this year 2001/01/01 - 2001/01/31: 464
Papers found for 'Cesarean section (C-section)' for this year 2001/01/01 - 2001/01/31: 52
Papers found for 'Chorionic villus sampling' for this year 2001/01/01 - 2001/01/31: 1
Papers found for 'Colposcopy' for this year 2001/01/01 - 2001/01/31: 5
Papers found for 'Congenital abnormalities' for this year 2001/01/01 - 2001/01/31: 531
Papers found for 'Continence' for this year 2001/01/01 - 2001/01/31: 11
Papers found for 'Contraception (birth control)' for this year 2001/01/01 - 2001/01/31: 33
Papers found for 'Cystoscopy' for this year 2001/01/01 - 2001/01/31: 14
Papers found for 'Depression and anxiety' for this year 2001/01/01 - 2001/01/31: 23
Papers found for 'Dilation and curettage (D and C)' for this year 2001/01/01 - 2001/01/31: 2
Papers found for 'Dysmenorrhea' for this year 2001/01/01 - 2001/01/31: 4
No papers found for 'Endometrial ablation' this month 2001/01/01 - 2001/01/31
Papers found for 'Endometrial biopsy' for this year 2001/01/01 - 2001/01/31: 18
Papers found for 'Endometrial cancer' for this year 2001/01/01 - 2001/01/31: 26
Papers found for 'Endometriosis' for this year 2001/01/01 - 2001/01/31: 16
Papers found for 'Epilepsy' for this year 2001/01/01 - 2001/01/31: 136
Papers found for 'Family planning' for this year 2001/01/01 - 2001/01/31: 25
No papers found for 'Female genital cutting' this month 2001/01/01 - 2001/01/31
Papers found for 'Fertility preservation' for this year 2001/01/01 - 2001/01/31: 6
Papers found for 'Fibroma' for this year 2001/01/01 - 2001/01/31: 19
Papers found for 'Gallstone disease' for this year 2001/01/01 - 2001/01/31: 41
Papers found for 'Genetic conditions' for this year 2001/01/01 - 2001/01/31: 1137
No papers found for 'Gentle cesarean section' this month 2001/01/01 - 2001/01/31
Papers found for 'Gestational diabetes' for this year 2001/01/01 - 2001/01/31: 17
Papers found for 'Gestational trophoblastic disease' for this year 2001/01/01 - 2001/01/31: 2
Papers found for 'Graves' disease' for this year 2001/01/01 - 2001/01/31: 20
Papers found for 'Gynecologic cancer' for this year 2001/01/01 - 2001/01/31: 74
Papers found for 'Gynecologic specialty care' for this year 2001/01/01 - 2001/01/31: 20
No papers found for 'Gynecologic well-woman care' this month 2001/01/01 - 2001/01/31
Papers found for 'Gynecological surgery' for this year 2001/01/01 - 2001/01/31: 78
Papers found for 'Heart disease' for this year 2001/01/01 - 2001/01/31: 1291
No papers found for 'Heavy menstrual cycles' this month 2001/01/01 - 2001/01/31
Papers found for 'High-risk pregnancy' for this year 2001/01/01 - 2001/01/31: 42
Papers found for 'HIV' for this year 2001/01/01 - 2001/01/31: 428
Papers found for 'HPV' for this year 2001/01/01 - 2001/01/31: 31
Papers found for 'In-vitro fertilization' for this year 2001/01/01 - 2001/01/31: 56
Papers found for 'Infertility' for this year 2001/01/01 - 2001/01/31: 76
Papers found for 'Integrative medicine' for this year 2001/01/01 - 2001/01/31: 3
Papers found for 'Interstitial cystitis' for this year 2001/01/01 - 2001/01/31: 11
Papers found for 'Irritable bowel syndrome (IBS)' for this year 2001/01/01 - 2001/01/31: 5
Papers found for 'Laparoscopic hysterectomy' for this year 2001/01/01 - 2001/01/31: 5
Papers found for 'Laparoscopy' for this year 2001/01/01 - 2001/01/31: 115
Papers found for 'Loop electrosurgical excision procedure (LEEP)' for this year 2001/01/01 - 2001/01/31: 1
Papers found for 'Lupus' for this year 2001/01/01 - 2001/01/31: 53
Papers found for 'Menopause' for this year 2001/01/01 - 2001/01/31: 96
Papers found for 'Menorrhagia' for this year 2001/01/01 - 2001/01/31: 3
Papers found for 'Menstrual conditions' for this year 2001/01/01 - 2001/01/31: 3
Papers found for 'Miscarriage' for this year 2001/01/01 - 2001/01/31: 39
Papers found for 'Morning sickness' for this year 2001/01/01 - 2001/01/31: 4
Papers found for 'Multiple sclerosis' for this year 2001/01/01 - 2001/01/31: 82
No papers found for 'Myomectomy' this month 2001/01/01 - 2001/01/31
Papers found for 'Osteoarthritis' for this year 2001/01/01 - 2001/01/31: 73
Papers found for 'Osteoporosis' for this year 2001/01/01 - 2001/01/31: 106
Papers found for 'Ovarian cancer' for this year 2001/01/01 - 2001/01/31: 96
Papers found for 'Ovarian cysts' for this year 2001/01/01 - 2001/01/31: 21
No papers found for 'Ovarian fibroma' this month 2001/01/01 - 2001/01/31
No papers found for 'Overactive bladder' this month 2001/01/01 - 2001/01/31
Papers found for 'Pancreatic cystic neoplasm' for this year 2001/01/01 - 2001/01/31: 9
Papers found for 'Pap test' for this year 2001/01/01 - 2001/01/31: 9
No papers found for 'Pelvic inflammatory disease (PID)' this month 2001/01/01 - 2001/01/31
Papers found for 'Pelvic organ prolapse' for this year 2001/01/01 - 2001/01/31: 8
Papers found for 'Pelvic pain' for this year 2001/01/01 - 2001/01/31: 22
Papers found for 'Pelvic ultrasound' for this year 2001/01/01 - 2001/01/31: 37
Papers found for 'Perimenopause' for this year 2001/01/01 - 2001/01/31: 3
Papers found for 'Placenta accreta' for this year 2001/01/01 - 2001/01/31: 2
Papers found for 'Placenta previa' for this year 2001/01/01 - 2001/01/31: 4
Papers found for 'Polycystic ovary syndrome (PCOS)' for this year 2001/01/01 - 2001/01/31: 9
Papers found for 'Postpartum depression' for this year 2001/01/01 - 2001/01/31: 3
Papers found for 'Preconception planning' for this year 2001/01/01 - 2001/01/31: 1
Papers found for 'Pregnancy' for this year 2001/01/01 - 2001/01/31: 689
Papers found for 'Pregnancy complications' for this year 2001/01/01 - 2001/01/31: 364
Papers found for 'Pregnancy, first trimester' for this year 2001/01/01 - 2001/01/31: 31
Papers found for 'Pregnancy, multiples' for this year 2001/01/01 - 2001/01/31: 48
Papers found for 'Pregnancy, second trimester' for this year 2001/01/01 - 2001/01/31: 20
Papers found for 'Pregnancy, third trimester' for this year 2001/01/01 - 2001/01/31: 17
Papers found for 'Premenstrual dysphoric disorder (PMDD)' for this year 2001/01/01 - 2001/01/31: 2
Papers found for 'Premenstrual syndrome (PMS)' for this year 2001/01/01 - 2001/01/31: 1
Papers found for 'Prenatal care' for this year 2001/01/01 - 2001/01/31: 38
Papers found for 'Prenatal genetic screening' for this year 2001/01/01 - 2001/01/31: 9
Papers found for 'Preterm birth' for this year 2001/01/01 - 2001/01/31: 58
Papers found for 'Primary care for women' for this year 2001/01/01 - 2001/01/31: 39
Papers found for 'Recurrent pregnancy loss' for this year 2001/01/01 - 2001/01/31: 7
Papers found for 'Rheumatoid arthritis' for this year 2001/01/01 - 2001/01/31: 132
Papers found for 'Robotic hysterectomy' for this year 2001/01/01 - 2001/01/31: 1
No papers found for 'Robotic myomectomy' this month 2001/01/01 - 2001/01/31
Papers found for 'Sexually transmitted diseases (STDs)' for this year 2001/01/01 - 2001/01/31: 364
Papers found for 'Sleep disorders' for this year 2001/01/01 - 2001/01/31: 89
Papers found for 'Small vessel disease' for this year 2001/01/01 - 2001/01/31: 30
Papers found for 'Sports injuries' for this year 2001/01/01 - 2001/01/31: 49
Papers found for 'STIs' for this year 2001/01/01 - 2001/01/31: 365
Papers found for 'Stress urinary incontinence' for this year 2001/01/01 - 2001/01/31: 16
Papers found for 'Stroke' for this year 2001/01/01 - 2001/01/31: 318
Papers found for 'Thyroid disease' for this year 2001/01/01 - 2001/01/31: 140
Papers found for 'Transgender care' for this year 2001/01/01 - 2001/01/31: 1
Papers found for 'Tubal ligation' for this year 2001/01/01 - 2001/01/31: 4
Papers found for 'Turner syndrome' for this year 2001/01/01 - 2001/01/31: 10
Papers found for 'Type I autoimmune hepatitis' for this year 2001/01/01 - 2001/01/31: 2
Papers found for 'Ultrasound' for this year 2001/01/01 - 2001/01/31: 1577
Papers found for 'Urinary incontinence' for this year 2001/01/01 - 2001/01/31: 41
Papers found for 'Urinary tract infections (UTIs)' for this year 2001/01/01 - 2001/01/31: 45
Papers found for 'Uterine and vaginal prolapse' for this year 2001/01/01 - 2001/01/31: 7
Papers found for 'Uterine fibroids' for this year 2001/01/01 - 2001/01/31: 20
Papers found for 'Vaginal birth after cesarean section' for this year 2001/01/01 - 2001/01/31: 4
Papers found for 'Vaginal cancer' for this year 2001/01/01 - 2001/01/31: 22
Papers found for 'Vaginitis' for this year 2001/01/01 - 2001/01/31: 132
Papers found for 'Vulvar cancer' for this year 2001/01/01 - 2001/01/31: 12
Papers found for 'Vulvar dysplasia' for this year 2001/01/01 - 2001/01/31: 1
Papers found for 'Vulvitis' for this year 2001/01/01 - 2001/01/31: 4
Papers found for 'Yeast infection' for this year 2001/01/01 - 2001/01/31: 37
Papers found for 'Abdominal cerclage' for this year 2001/02/01 - 2001/02/28: 1
Papers found for 'Abnormal pap smears' for this year 2001/02/01 - 2001/02/28: 6
Papers found for 'Abnormal uterine bleeding' for this year 2001/02/01 - 2001/02/28: 7
Papers found for 'Alzheimer's disease' for this year 2001/02/01 - 2001/02/28: 435
Papers found for 'Amenorrhea' for this year 2001/02/01 - 2001/02/28: 36
Papers found for 'Amniocentesis' for this year 2001/02/01 - 2001/02/28: 33
Papers found for 'Arthritis' for this year 2001/02/01 - 2001/02/28: 653
Papers found for 'Asthma' for this year 2001/02/01 - 2001/02/28: 532
Papers found for 'Bacterial vaginosis' for this year 2001/02/01 - 2001/02/28: 23
Papers found for 'Bleeding disorders' for this year 2001/02/01 - 2001/02/28: 273
Papers found for 'Breast cancer' for this year 2001/02/01 - 2001/02/28: 1076
Papers found for 'Cancers' for this year 2001/02/01 - 2001/02/28: 9464
Papers found for 'Celiac disease' for this year 2001/02/01 - 2001/02/28: 61
Papers found for 'Cervical cancer' for this year 2001/02/01 - 2001/02/28: 212
Papers found for 'Cervical insufficiency' for this year 2001/02/01 - 2001/02/28: 6
Papers found for 'Cervicitis' for this year 2001/02/01 - 2001/02/28: 1364
Papers found for 'Cesarean section (C-section)' for this year 2001/02/01 - 2001/02/28: 170
Papers found for 'Chorionic villus sampling' for this year 2001/02/01 - 2001/02/28: 7
Papers found for 'Colposcopy' for this year 2001/02/01 - 2001/02/28: 22
Papers found for 'Congenital abnormalities' for this year 2001/02/01 - 2001/02/28: 1558
Papers found for 'Continence' for this year 2001/02/01 - 2001/02/28: 49
Papers found for 'Contraception (birth control)' for this year 2001/02/01 - 2001/02/28: 83
Papers found for 'Cystoscopy' for this year 2001/02/01 - 2001/02/28: 40
Papers found for 'Depression and anxiety' for this year 2001/02/01 - 2001/02/28: 79
Papers found for 'Dilation and curettage (D and C)' for this year 2001/02/01 - 2001/02/28: 12
Papers found for 'Dysmenorrhea' for this year 2001/02/01 - 2001/02/28: 14
Papers found for 'Endometrial ablation' for this year 2001/02/01 - 2001/02/28: 7
Papers found for 'Endometrial biopsy' for this year 2001/02/01 - 2001/02/28: 88
Papers found for 'Endometrial cancer' for this year 2001/02/01 - 2001/02/28: 113
Papers found for 'Endometriosis' for this year 2001/02/01 - 2001/02/28: 65
Papers found for 'Epilepsy' for this year 2001/02/01 - 2001/02/28: 346
Papers found for 'Family planning' for this year 2001/02/01 - 2001/02/28: 82
Papers found for 'Female genital cutting' for this year 2001/02/01 - 2001/02/28: 1
Papers found for 'Fertility preservation' for this year 2001/02/01 - 2001/02/28: 10
Papers found for 'Fibroma' for this year 2001/02/01 - 2001/02/28: 44
Papers found for 'Gallstone disease' for this year 2001/02/01 - 2001/02/28: 105
Papers found for 'Genetic conditions' for this year 2001/02/01 - 2001/02/28: 3254
No papers found for 'Gentle cesarean section' this month 2001/02/01 - 2001/02/28
Papers found for 'Gestational diabetes' for this year 2001/02/01 - 2001/02/28: 38
Papers found for 'Gestational trophoblastic disease' for this year 2001/02/01 - 2001/02/28: 13
Papers found for 'Graves' disease' for this year 2001/02/01 - 2001/02/28: 58
Papers found for 'Gynecologic cancer' for this year 2001/02/01 - 2001/02/28: 258
Papers found for 'Gynecologic specialty care' for this year 2001/02/01 - 2001/02/28: 37
No papers found for 'Gynecologic well-woman care' this month 2001/02/01 - 2001/02/28
Papers found for 'Gynecological surgery' for this year 2001/02/01 - 2001/02/28: 261
Papers found for 'Heart disease' for this year 2001/02/01 - 2001/02/28: 3341
No papers found for 'Heavy menstrual cycles' this month 2001/02/01 - 2001/02/28
Papers found for 'High-risk pregnancy' for this year 2001/02/01 - 2001/02/28: 116
Papers found for 'HIV' for this year 2001/02/01 - 2001/02/28: 1188
Papers found for 'HPV' for this year 2001/02/01 - 2001/02/28: 75
Papers found for 'In-vitro fertilization' for this year 2001/02/01 - 2001/02/28: 163
Papers found for 'Infertility' for this year 2001/02/01 - 2001/02/28: 240
Papers found for 'Integrative medicine' for this year 2001/02/01 - 2001/02/28: 22
Papers found for 'Interstitial cystitis' for this year 2001/02/01 - 2001/02/28: 14
Papers found for 'Irritable bowel syndrome (IBS)' for this year 2001/02/01 - 2001/02/28: 13
Papers found for 'Laparoscopic hysterectomy' for this year 2001/02/01 - 2001/02/28: 20
Papers found for 'Laparoscopy' for this year 2001/02/01 - 2001/02/28: 305
No papers found for 'Loop electrosurgical excision procedure (LEEP)' this month 2001/02/01 - 2001/02/28
Papers found for 'Lupus' for this year 2001/02/01 - 2001/02/28: 202
Papers found for 'Menopause' for this year 2001/02/01 - 2001/02/28: 278
Papers found for 'Menorrhagia' for this year 2001/02/01 - 2001/02/28: 17
Papers found for 'Menstrual conditions' for this year 2001/02/01 - 2001/02/28: 25
Papers found for 'Miscarriage' for this year 2001/02/01 - 2001/02/28: 97
Papers found for 'Morning sickness' for this year 2001/02/01 - 2001/02/28: 7
Papers found for 'Multiple sclerosis' for this year 2001/02/01 - 2001/02/28: 221
Papers found for 'Myomectomy' for this year 2001/02/01 - 2001/02/28: 13
Papers found for 'Osteoarthritis' for this year 2001/02/01 - 2001/02/28: 181
Papers found for 'Osteoporosis' for this year 2001/02/01 - 2001/02/28: 246
Papers found for 'Ovarian cancer' for this year 2001/02/01 - 2001/02/28: 318
Papers found for 'Ovarian cysts' for this year 2001/02/01 - 2001/02/28: 66
No papers found for 'Ovarian fibroma' this month 2001/02/01 - 2001/02/28
Papers found for 'Overactive bladder' for this year 2001/02/01 - 2001/02/28: 10
Papers found for 'Pancreatic cystic neoplasm' for this year 2001/02/01 - 2001/02/28: 9
Papers found for 'Pap test' for this year 2001/02/01 - 2001/02/28: 36
Papers found for 'Pelvic inflammatory disease (PID)' for this year 2001/02/01 - 2001/02/28: 5
Papers found for 'Pelvic organ prolapse' for this year 2001/02/01 - 2001/02/28: 16
Papers found for 'Pelvic pain' for this year 2001/02/01 - 2001/02/28: 59
Papers found for 'Pelvic ultrasound' for this year 2001/02/01 - 2001/02/28: 112
Papers found for 'Perimenopause' for this year 2001/02/01 - 2001/02/28: 14
Papers found for 'Placenta accreta' for this year 2001/02/01 - 2001/02/28: 2
Papers found for 'Placenta previa' for this year 2001/02/01 - 2001/02/28: 6
Papers found for 'Polycystic ovary syndrome (PCOS)' for this year 2001/02/01 - 2001/02/28: 16
Papers found for 'Postpartum depression' for this year 2001/02/01 - 2001/02/28: 23
Papers found for 'Preconception planning' for this year 2001/02/01 - 2001/02/28: 2
Papers found for 'Pregnancy' for this year 2001/02/01 - 2001/02/28: 2179
Papers found for 'Pregnancy complications' for this year 2001/02/01 - 2001/02/28: 1063
Papers found for 'Pregnancy, first trimester' for this year 2001/02/01 - 2001/02/28: 76
Papers found for 'Pregnancy, multiples' for this year 2001/02/01 - 2001/02/28: 180
Papers found for 'Pregnancy, second trimester' for this year 2001/02/01 - 2001/02/28: 50
Papers found for 'Pregnancy, third trimester' for this year 2001/02/01 - 2001/02/28: 59
Papers found for 'Premenstrual dysphoric disorder (PMDD)' for this year 2001/02/01 - 2001/02/28: 6
Papers found for 'Premenstrual syndrome (PMS)' for this year 2001/02/01 - 2001/02/28: 3
Papers found for 'Prenatal care' for this year 2001/02/01 - 2001/02/28: 116
Papers found for 'Prenatal genetic screening' for this year 2001/02/01 - 2001/02/28: 24
Papers found for 'Preterm birth' for this year 2001/02/01 - 2001/02/28: 136
Papers found for 'Primary care for women' for this year 2001/02/01 - 2001/02/28: 98
Papers found for 'Recurrent pregnancy loss' for this year 2001/02/01 - 2001/02/28: 23
Papers found for 'Rheumatoid arthritis' for this year 2001/02/01 - 2001/02/28: 304
No papers found for 'Robotic hysterectomy' this month 2001/02/01 - 2001/02/28
No papers found for 'Robotic myomectomy' this month 2001/02/01 - 2001/02/28
Papers found for 'Sexually transmitted diseases (STDs)' for this year 2001/02/01 - 2001/02/28: 1114
Papers found for 'Sleep disorders' for this year 2001/02/01 - 2001/02/28: 273
Papers found for 'Small vessel disease' for this year 2001/02/01 - 2001/02/28: 67
Papers found for 'Sports injuries' for this year 2001/02/01 - 2001/02/28: 123
Papers found for 'STIs' for this year 2001/02/01 - 2001/02/28: 1115
Papers found for 'Stress urinary incontinence' for this year 2001/02/01 - 2001/02/28: 47
Papers found for 'Stroke' for this year 2001/02/01 - 2001/02/28: 821
Papers found for 'Thyroid disease' for this year 2001/02/01 - 2001/02/28: 331
Papers found for 'Transgender care' for this year 2001/02/01 - 2001/02/28: 1
Papers found for 'Tubal ligation' for this year 2001/02/01 - 2001/02/28: 11
Papers found for 'Turner syndrome' for this year 2001/02/01 - 2001/02/28: 31
Papers found for 'Type I autoimmune hepatitis' for this year 2001/02/01 - 2001/02/28: 7
Papers found for 'Ultrasound' for this year 2001/02/01 - 2001/02/28: 4075
Papers found for 'Urinary incontinence' for this year 2001/02/01 - 2001/02/28: 118
Papers found for 'Urinary tract infections (UTIs)' for this year 2001/02/01 - 2001/02/28: 140
Papers found for 'Uterine and vaginal prolapse' for this year 2001/02/01 - 2001/02/28: 12
Papers found for 'Uterine fibroids' for this year 2001/02/01 - 2001/02/28: 65
Papers found for 'Vaginal birth after cesarean section' for this year 2001/02/01 - 2001/02/28: 12
Papers found for 'Vaginal cancer' for this year 2001/02/01 - 2001/02/28: 93
Papers found for 'Vaginitis' for this year 2001/02/01 - 2001/02/28: 376
Papers found for 'Vulvar cancer' for this year 2001/02/01 - 2001/02/28: 22
Papers found for 'Vulvar dysplasia' for this year 2001/02/01 - 2001/02/28: 1
Papers found for 'Vulvitis' for this year 2001/02/01 - 2001/02/28: 16
Papers found for 'Yeast infection' for this year 2001/02/01 - 2001/02/28: 181
No papers found for 'Abdominal cerclage' this month 2001/03/01 - 2001/03/31
Papers found for 'Abnormal pap smears' for this year 2001/03/01 - 2001/03/31: 12

KeyboardInterrupt:

In [ ]:
if 'dfs_list11' in locals() and dfs_list11:
    df = pd.concat(dfs_list11, ignore_index = True)

In [165]:
df

,title,abstract,journal,date,authors,doi
0,Reparative changes and the false-positive/fals...,Reparative changes can be a diagnostic challen...,Archives of pathology & laboratory medicine,2001-01-11,"[T JColgan, S LWoodhouse, P EStyer, MKennedy, ...",10.5858/2001-125-0134-RCATFP
1,When a Pap smear is abnormal.,NaN,Harvard women's health watch,2001-01-04,[],NaN
2,Cytomorphology of small-cell (neuroendocrine) ...,Small-cell (neuroendocrine) carcinoma of the f...,Diagnostic cytopathology,2001-01-03,"[M CCiesla, B JGuidos, S MSelvaggi]",10.1002/1097-0339(200101)24:1<46::aid-dc1008>3...
3,Dual distant uterine placental insertion conne...,There are several types of intrauterine membra...,The Journal of reproductive medicine,2001-01-12,"[TSilberstein, TKivilevitz, FPress, DGoldstein...",NaN
4,Vaginal misoprostol for induction of labor: 25...,To compare the efficacy and safety of two regi...,International journal of gynaecology and obste...,2001-01-09,"[M TEl-Sherbiny, I HEl-Gharieb, H AGewely]",10.1016/s0020-7292(00)00308-8
...,...,...,...,...,...,...
2219906,HIV testing in 2006: issues and methods.,Infection with HIV and subsequent development ...,Expert review of anti-infective therapy,2006-10-03,"[DenisonChang, KateLearmonth, Elizabeth MDax]",10.1586/14787210.4.4.565
2219907,Tenofovir disoproxil fumarate-emtricitabine co...,Truvada is the coformulation of tenofovir diso...,Expert review of anti-infective therapy,2006-10-03,"[Rosa MaríaMuñoz de Benito, Jose RamónArribas ...",10.1586/14787210.4.4.523
2219908,Chlamydia trachomatis and herpes simplex virus...,The role of viral and bacterial co-infection i...,European journal of gynaecological oncology,2006-10-03,"[AKwaśniewska, EKorobowicz, JVisconti, MZdunek...",NaN
2219909,Vaccination against human genital papillomavir...,Human genital papillomaviruses are the necessa...,European journal of gynaecological oncology,2006-10-03,"[GDe Palo, LMariani]",NaN
2219910,Proceedings of the XL Anniversary of Clinical ...,NaN,Wiadomosci parazytologiczne,2006-10-03,[],NaN

In [167]:
# This is the final dataframe from the 5 total blocks
pubmed_data = pd.concat([final_df1, final_df2, final_df, final_df22, df], ignore_index = True)

In [168]:
pubmed_data

,title,abstract,journal,date,authors,doi
0,The Infection of the Connective Tissue in Scir...,None,Journal of anatomy and physiology,1879-10-01,[CCreighton],None
1,"Deafness in white cats, and statistics of deaf...",None,"Science (New York, N.Y.)",1884-02-29,[A GBell],10.1126/science.ns-3.56.243-a
2,DR. HUGHLINGS-JACKSON ON EPILEPSY.,None,"Science (New York, N.Y.)",1886-06-11,[JJ],10.1126/science.ns-7.175S.533
3,The Causation of Several Variations and Congen...,None,Journal of anatomy and physiology,1887-07-01,[W ALane],None
4,Note on Electrolysis for Uterine Fibroma.,None,Annals of surgery,1888-11-01,[A PPeck],10.1097/00000658-188807000-00156
...,...,...,...,...,...,...
3166595,HIV testing in 2006: issues and methods.,Infection with HIV and subsequent development ...,Expert review of anti-infective therapy,2006-10-03,"[DenisonChang, KateLearmonth, Elizabeth MDax]",10.1586/14787210.4.4.565
3166596,Tenofovir disoproxil fumarate-emtricitabine co...,Truvada is the coformulation of tenofovir diso...,Expert review of anti-infective therapy,2006-10-03,"[Rosa MaríaMuñoz de Benito, Jose RamónArribas ...",10.1586/14787210.4.4.523
3166597,Chlamydia trachomatis and herpes simplex virus...,The role of viral and bacterial co-infection i...,European journal of gynaecological oncology,2006-10-03,"[AKwaśniewska, EKorobowicz, JVisconti, MZdunek...",NaN
3166598,Vaccination against human genital papillomavir...,Human genital papillomaviruses are the necessa...,European journal of gynaecological oncology,2006-10-03,"[GDe Palo, LMariani]",NaN
3166599,Proceedings of the XL Anniversary of Clinical ...,NaN,Wiadomosci parazytologiczne,2006-10-03,[],NaN

In [ ]:
# Remove duplicates
pubmed_data = pubmed_data.drop_duplicates(subset = ["title", "doi"], keep = "first")

In [186]:
pubmed_data

,title,abstract,journal,date,authors,doi
0,The Infection of the Connective Tissue in Scir...,None,Journal of anatomy and physiology,1879-10-01,[CCreighton],None
1,"Deafness in white cats, and statistics of deaf...",None,"Science (New York, N.Y.)",1884-02-29,[A GBell],10.1126/science.ns-3.56.243-a
2,DR. HUGHLINGS-JACKSON ON EPILEPSY.,None,"Science (New York, N.Y.)",1886-06-11,[JJ],10.1126/science.ns-7.175S.533
3,The Causation of Several Variations and Congen...,None,Journal of anatomy and physiology,1887-07-01,[W ALane],None
4,Note on Electrolysis for Uterine Fibroma.,None,Annals of surgery,1888-11-01,[A PPeck],10.1097/00000658-188807000-00156
...,...,...,...,...,...,...
3165756,Brief report: Behavioral risk factors for yout...,"By most reports, soccer (football) is among th...",Journal of pediatric psychology,2006-10-03,"[David CSchwebel, Mark MBanaszek, McCallMcDaniel]",10.1093/jpepsy/jsl034
3165757,Is there evidence that proprioception or balan...,NaN,Physical therapy,2006-10-03,"[Jessica LOwen, SeanCampbell, Sara JFalkner, C...",10.2522/ptj.20050329
3165758,A prospective study of injury incidence among ...,Sports-related injuries are an issue of concer...,American journal of epidemiology,2006-10-03,"[Sarah BKnowles, Stephen WMarshall, J MichaelB...",10.1093/aje/kwj337
3165759,[Most severe consequences of eye contusion inj...,One third of all eye injuries are contusion in...,Srpski arhiv za celokupno lekarstvo,2006-10-03,[MiroslavVukosavljević],10.2298/sarh0608278v
3165810,Effects of directional microphone and adaptive...,Although cochlear implant (CI) users have enjo...,The Journal of the Acoustical Society of America,2006-10-31,"[KingChung, Fan-GangZeng, Kyle NAcker]",10.1121/1.2258500

In [ ]:
# Change authors to a string
pubmed_data['authors'] = pubmed_data['authors'].astype(str)

In [192]:
pubmed_data

,title,abstract,journal,date,authors,doi
0,The Infection of the Connective Tissue in Scir...,None,Journal of anatomy and physiology,1879-10-01,['CCreighton'],None
1,"Deafness in white cats, and statistics of deaf...",None,"Science (New York, N.Y.)",1884-02-29,['A GBell'],10.1126/science.ns-3.56.243-a
2,DR. HUGHLINGS-JACKSON ON EPILEPSY.,None,"Science (New York, N.Y.)",1886-06-11,['JJ'],10.1126/science.ns-7.175S.533
3,The Causation of Several Variations and Congen...,None,Journal of anatomy and physiology,1887-07-01,['W ALane'],None
4,Note on Electrolysis for Uterine Fibroma.,None,Annals of surgery,1888-11-01,['A PPeck'],10.1097/00000658-188807000-00156
...,...,...,...,...,...,...
3165756,Brief report: Behavioral risk factors for yout...,"By most reports, soccer (football) is among th...",Journal of pediatric psychology,2006-10-03,"['David CSchwebel', 'Mark MBanaszek', 'McCallM...",10.1093/jpepsy/jsl034
3165757,Is there evidence that proprioception or balan...,NaN,Physical therapy,2006-10-03,"['Jessica LOwen', 'SeanCampbell', 'Sara JFalkn...",10.2522/ptj.20050329
3165758,A prospective study of injury incidence among ...,Sports-related injuries are an issue of concer...,American journal of epidemiology,2006-10-03,"['Sarah BKnowles', 'Stephen WMarshall', 'J Mic...",10.1093/aje/kwj337
3165759,[Most severe consequences of eye contusion inj...,One third of all eye injuries are contusion in...,Srpski arhiv za celokupno lekarstvo,2006-10-03,['MiroslavVukosavljević'],10.2298/sarh0608278v
3165810,Effects of directional microphone and adaptive...,Although cochlear implant (CI) users have enjo...,The Journal of the Acoustical Society of America,2006-10-31,"['KingChung', 'Fan-GangZeng', 'Kyle NAcker']",10.1121/1.2258500

In [193]:
pubmed_data.to_csv("pubmed_data.csv", index = False)

In [ ]:
##################################################################################################################################################
# RAW DATA TO DB
##################################################################################################################################################

In [ ]:
# Connect to the database
conn = psycopg2.connect(
    dbname=os.getenv("DBNAME"),
    user=os.getenv("DBUSER"),
    password=os.getenv("DBPASSWORD"),
    port=os.getenv("DBPORT"),
    host=os.getenv("DBHOST")
)
conn_string=os.getenv("CONNSTRING")

# Create engine
engine = create_engine(
    f"postgresql+psycopg2://{os.getenv('DBUSER')}:{os.getenv('DBPASSWORD')}"
    f"@{os.getenv('DBHOST')}:{os.getenv('DBPORT')}/{os.getenv('DBNAME')}"
)

In [201]:
pubmed_data.to_sql("pubmed_articles", engine, if_exists="append", index=False, method="multi", chunksize=1000)

DatabaseError: Execution failed on sql 'INSERT INTO pubmed_articles (title, abstract, journal, date, authors, doi) VALUES (:title_m0, :abstract_m0, :journal_m0, :date_m0, :authors_m0, :doi_m0), (:title_m1, :abstract_m1, :journal_m1, :date_m1, :authors_m1, :doi_m1), (:title_m2, :abstract_m2, :journal_m2, :date_m2, :authors_m2, :doi_m2), (:title_m3, :abstract_m3, :journal_m3, :date_m3, :authors_m3, :doi_m3), (:title_m4, :abstract_m4, :journal_m4, :date_m4, :authors_m4, :doi_m4), (:title_m5, :abstract_m5, :journal_m5, :date_m5, :authors_m5, :doi_m5), (:title_m6, :abstract_m6, :journal_m6, :date_m6, :authors_m6, :doi_m6), (:title_m7, :abstract_m7, :journal_m7, :date_m7, :authors_m7, :doi_m7), (:title_m8, :abstract_m8, :journal_m8, :date_m8, :authors_m8, :doi_m8), (:title_m9, :abstract_m9, :journal_m9, :date_m9, :authors_m9, :doi_m9), (:title_m10, :abstract_m10, :journal_m10, :date_m10, :authors_m10, :doi_m10), (:title_m11, :abstract_m11, :journal_m11, :date_m11, :authors_m11, :doi_m11), (:title_m12, :abstract_m12, :journal_m12, :date_m12, :authors_m12, :doi_m12), (:title_m13, :abstract_m13, :journal_m13, :date_m13, :authors_m13, :doi_m13), (:title_m14, :abstract_m14, :journal_m14, :date_m14, :authors_m14, :doi_m14), (:title_m15, :abstract_m15, :journal_m15, :date_m15, :authors_m15, :doi_m15), (:title_m16, :abstract_m16, :journal_m16, :date_m16, :authors_m16, :doi_m16), (:title_m17, :abstract_m17, :journal_m17, :date_m17, :authors_m17, :doi_m17), (:title_m18, :abstract_m18, :journal_m18, :date_m18, :authors_m18, :doi_m18), (:title_m19, :abstract_m19, :journal_m19, :date_m19, :authors_m19, :doi_m19), (:title_m20, :abstract_m20, :journal_m20, :date_m20, :authors_m20, :doi_m20), (:title_m21, :abstract_m21, :journal_m21, :date_m21, :authors_m21, :doi_m21), (:title_m22, :abstract_m22, :journal_m22, :date_m22, :authors_m22, :doi_m22), (:title_m23, :abstract_m23, :journal_m23, :date_m23, :authors_m23, :doi_m23), (:title_m24, :abstract_m24, :journal_m24, :date_m24, :authors_m24, :doi_m24), (:title_m25, :abstract_m25, :journal_m25, :date_m25, :authors_m25, :doi_m25), (:title_m26, :abstract_m26, :journal_m26, :date_m26, :authors_m26, :doi_m26), (:title_m27, :abstract_m27, :journal_m27, :date_m27, :authors_m27, :doi_m27), (:title_m28, :abstract_m28, :journal_m28, :date_m28, :authors_m28, :doi_m28), (:title_m29, :abstract_m29, :journal_m29, :date_m29, :authors_m29, :doi_m29), (:title_m30, :abstract_m30, :journal_m30, :date_m30, :authors_m30, :doi_m30), (:title_m31, :abstract_m31, :journal_m31, :date_m31, :authors_m31, :doi_m31), (:title_m32, :abstract_m32, :journal_m32, :date_m32, :authors_m32, :doi_m32), (:title_m33, :abstract_m33, :journal_m33, :date_m33, :authors_m33, :doi_m33), (:title_m34, :abstract_m34, :journal_m34, :date_m34, :authors_m34, :doi_m34), (:title_m35, :abstract_m35, :journal_m35, :date_m35, :authors_m35, :doi_m35), (:title_m36, :abstract_m36, :journal_m36, :date_m36, :authors_m36, :doi_m36), (:title_m37, :abstract_m37, :journal_m37, :date_m37, :authors_m37, :doi_m37), (:title_m38, :abstract_m38, :journal_m38, :date_m38, :authors_m38, :doi_m38), (:title_m39, :abstract_m39, :journal_m39, :date_m39, :authors_m39, :doi_m39), (:title_m40, :abstract_m40, :journal_m40, :date_m40, :authors_m40, :doi_m40), (:title_m41, :abstract_m41, :journal_m41, :date_m41, :authors_m41, :doi_m41), (:title_m42, :abstract_m42, :journal_m42, :date_m42, :authors_m42, :doi_m42), (:title_m43, :abstract_m43, :journal_m43, :date_m43, :authors_m43, :doi_m43), (:title_m44, :abstract_m44, :journal_m44, :date_m44, :authors_m44, :doi_m44), (:title_m45, :abstract_m45, :journal_m45, :date_m45, :authors_m45, :doi_m45), (:title_m46, :abstract_m46, :journal_m46, :date_m46, :authors_m46, :doi_m46), (:title_m47, :abstract_m47, :journal_m47, :date_m47, :authors_m47, :doi_m47), (:title_m48, :abstract_m48, :journal_m48, :date_m48, :authors_m48, :doi_m48), (:title_m49, :abstract_m49, :journal_m49, :date_m49, :authors_m49, :doi_m49), (:title_m50, :abstract_m50, :journal_m50, :date_m50, :authors_m50, :doi_m50), (:title_m51, :abstract_m51, :journal_m51, :date_m51, :authors_m51, :doi_m51), (:title_m52, :abstract_m52, :journal_m52, :date_m52, :authors_m52, :doi_m52), (:title_m53, :abstract_m53, :journal_m53, :date_m53, :authors_m53, :doi_m53), (:title_m54, :abstract_m54, :journal_m54, :date_m54, :authors_m54, :doi_m54), (:title_m55, :abstract_m55, :journal_m55, :date_m55, :authors_m55, :doi_m55), (:title_m56, :abstract_m56, :journal_m56, :date_m56, :authors_m56, :doi_m56), (:title_m57, :abstract_m57, :journal_m57, :date_m57, :authors_m57, :doi_m57), (:title_m58, :abstract_m58, :journal_m58, :date_m58, :authors_m58, :doi_m58), (:title_m59, :abstract_m59, :journal_m59, :date_m59, :authors_m59, :doi_m59), (:title_m60, :abstract_m60, :journal_m60, :date_m60, :authors_m60, :doi_m60), (:title_m61, :abstract_m61, :journal_m61, :date_m61, :authors_m61, :doi_m61), (:title_m62, :abstract_m62, :journal_m62, :date_m62, :authors_m62, :doi_m62), (:title_m63, :abstract_m63, :journal_m63, :date_m63, :authors_m63, :doi_m63), (:title_m64, :abstract_m64, :journal_m64, :date_m64, :authors_m64, :doi_m64), (:title_m65, :abstract_m65, :journal_m65, :date_m65, :authors_m65, :doi_m65), (:title_m66, :abstract_m66, :journal_m66, :date_m66, :authors_m66, :doi_m66), (:title_m67, :abstract_m67, :journal_m67, :date_m67, :authors_m67, :doi_m67), (:title_m68, :abstract_m68, :journal_m68, :date_m68, :authors_m68, :doi_m68), (:title_m69, :abstract_m69, :journal_m69, :date_m69, :authors_m69, :doi_m69), (:title_m70, :abstract_m70, :journal_m70, :date_m70, :authors_m70, :doi_m70), (:title_m71, :abstract_m71, :journal_m71, :date_m71, :authors_m71, :doi_m71), (:title_m72, :abstract_m72, :journal_m72, :date_m72, :authors_m72, :doi_m72), (:title_m73, :abstract_m73, :journal_m73, :date_m73, :authors_m73, :doi_m73), (:title_m74, :abstract_m74, :journal_m74, :date_m74, :authors_m74, :doi_m74), (:title_m75, :abstract_m75, :journal_m75, :date_m75, :authors_m75, :doi_m75), (:title_m76, :abstract_m76, :journal_m76, :date_m76, :authors_m76, :doi_m76), (:title_m77, :abstract_m77, :journal_m77, :date_m77, :authors_m77, :doi_m77), (:title_m78, :abstract_m78, :journal_m78, :date_m78, :authors_m78, :doi_m78), (:title_m79, :abstract_m79, :journal_m79, :date_m79, :authors_m79, :doi_m79), (:title_m80, :abstract_m80, :journal_m80, :date_m80, :authors_m80, :doi_m80), (:title_m81, :abstract_m81, :journal_m81, :date_m81, :authors_m81, :doi_m81), (:title_m82, :abstract_m82, :journal_m82, :date_m82, :authors_m82, :doi_m82), (:title_m83, :abstract_m83, :journal_m83, :date_m83, :authors_m83, :doi_m83), (:title_m84, :abstract_m84, :journal_m84, :date_m84, :authors_m84, :doi_m84), (:title_m85, :abstract_m85, :journal_m85, :date_m85, :authors_m85, :doi_m85), (:title_m86, :abstract_m86, :journal_m86, :date_m86, :authors_m86, :doi_m86), (:title_m87, :abstract_m87, :journal_m87, :date_m87, :authors_m87, :doi_m87), (:title_m88, :abstract_m88, :journal_m88, :date_m88, :authors_m88, :doi_m88), (:title_m89, :abstract_m89, :journal_m89, :date_m89, :authors_m89, :doi_m89), (:title_m90, :abstract_m90, :journal_m90, :date_m90, :authors_m90, :doi_m90), (:title_m91, :abstract_m91, :journal_m91, :date_m91, :authors_m91, :doi_m91), (:title_m92, :abstract_m92, :journal_m92, :date_m92, :authors_m92, :doi_m92), (:title_m93, :abstract_m93, :journal_m93, :date_m93, :authors_m93, :doi_m93), (:title_m94, :abstract_m94, :journal_m94, :date_m94, :authors_m94, :doi_m94), (:title_m95, :abstract_m95, :journal_m95, :date_m95, :authors_m95, :doi_m95), (:title_m96, :abstract_m96, :journal_m96, :date_m96, :authors_m96, :doi_m96), (:title_m97, :abstract_m97, :journal_m97, :date_m97, :authors_m97, :doi_m97), (:title_m98, :abstract_m98, :journal_m98, :date_m98, :authors_m98, :doi_m98), (:title_m99, :abstract_m99, :journal_m99, :date_m99, :authors_m99, :doi_m99), (:title_m100, :abstract_m100, :journal_m100, :date_m100, :authors_m100, :doi_m100), (:title_m101, :abstract_m101, :journal_m101, :date_m101, :authors_m101, :doi_m101), (:title_m102, :abstract_m102, :journal_m102, :date_m102, :authors_m102, :doi_m102), (:title_m103, :abstract_m103, :journal_m103, :date_m103, :authors_m103, :doi_m103), (:title_m104, :abstract_m104, :journal_m104, :date_m104, :authors_m104, :doi_m104), (:title_m105, :abstract_m105, :journal_m105, :date_m105, :authors_m105, :doi_m105), (:title_m106, :abstract_m106, :journal_m106, :date_m106, :authors_m106, :doi_m106), (:title_m107, :abstract_m107, :journal_m107, :date_m107, :authors_m107, :doi_m107), (:title_m108, :abstract_m108, :journal_m108, :date_m108, :authors_m108, :doi_m108), (:title_m109, :abstract_m109, :journal_m109, :date_m109, :authors_m109, :doi_m109), (:title_m110, :abstract_m110, :journal_m110, :date_m110, :authors_m110, :doi_m110), (:title_m111, :abstract_m111, :journal_m111, :date_m111, :authors_m111, :doi_m111), (:title_m112, :abstract_m112, :journal_m112, :date_m112, :authors_m112, :doi_m112), (:title_m113, :abstract_m113, :journal_m113, :date_m113, :authors_m113, :doi_m113), (:title_m114, :abstract_m114, :journal_m114, :date_m114, :authors_m114, :doi_m114), (:title_m115, :abstract_m115, :journal_m115, :date_m115, :authors_m115, :doi_m115), (:title_m116, :abstract_m116, :journal_m116, :date_m116, :authors_m116, :doi_m116), (:title_m117, :abstract_m117, :journal_m117, :date_m117, :authors_m117, :doi_m117), (:title_m118, :abstract_m118, :journal_m118, :date_m118, :authors_m118, :doi_m118), (:title_m119, :abstract_m119, :journal_m119, :date_m119, :authors_m119, :doi_m119), (:title_m120, :abstract_m120, :journal_m120, :date_m120, :authors_m120, :doi_m120), (:title_m121, :abstract_m121, :journal_m121, :date_m121, :authors_m121, :doi_m121), (:title_m122, :abstract_m122, :journal_m122, :date_m122, :authors_m122, :doi_m122), (:title_m123, :abstract_m123, :journal_m123, :date_m123, :authors_m123, :doi_m123), (:title_m124, :abstract_m124, :journal_m124, :date_m124, :authors_m124, :doi_m124), (:title_m125, :abstract_m125, :journal_m125, :date_m125, :authors_m125, :doi_m125), (:title_m126, :abstract_m126, :journal_m126, :date_m126, :authors_m126, :doi_m126), (:title_m127, :abstract_m127, :journal_m127, :date_m127, :authors_m127, :doi_m127), (:title_m128, :abstract_m128, :journal_m128, :date_m128, :authors_m128, :doi_m128), (:title_m129, :abstract_m129, :journal_m129, :date_m129, :authors_m129, :doi_m129), (:title_m130, :abstract_m130, :journal_m130, :date_m130, :authors_m130, :doi_m130), (:title_m131, :abstract_m131, :journal_m131, :date_m131, :authors_m131, :doi_m131), (:title_m132, :abstract_m132, :journal_m132, :date_m132, :authors_m132, :doi_m132), (:title_m133, :abstract_m133, :journal_m133, :date_m133, :authors_m133, :doi_m133), (:title_m134, :abstract_m134, :journal_m134, :date_m134, :authors_m134, :doi_m134), (:title_m135, :abstract_m135, :journal_m135, :date_m135, :authors_m135, :doi_m135), (:title_m136, :abstract_m136, :journal_m136, :date_m136, :authors_m136, :doi_m136), (:title_m137, :abstract_m137, :journal_m137, :date_m137, :authors_m137, :doi_m137), (:title_m138, :abstract_m138, :journal_m138, :date_m138, :authors_m138, :doi_m138), (:title_m139, :abstract_m139, :journal_m139, :date_m139, :authors_m139, :doi_m139), (:title_m140, :abstract_m140, :journal_m140, :date_m140, :authors_m140, :doi_m140), (:title_m141, :abstract_m141, :journal_m141, :date_m141, :authors_m141, :doi_m141), (:title_m142, :abstract_m142, :journal_m142, :date_m142, :authors_m142, :doi_m142), (:title_m143, :abstract_m143, :journal_m143, :date_m143, :authors_m143, :doi_m143), (:title_m144, :abstract_m144, :journal_m144, :date_m144, :authors_m144, :doi_m144), (:title_m145, :abstract_m145, :journal_m145, :date_m145, :authors_m145, :doi_m145), (:title_m146, :abstract_m146, :journal_m146, :date_m146, :authors_m146, :doi_m146), (:title_m147, :abstract_m147, :journal_m147, :date_m147, :authors_m147, :doi_m147), (:title_m148, :abstract_m148, :journal_m148, :date_m148, :authors_m148, :doi_m148), (:title_m149, :abstract_m149, :journal_m149, :date_m149, :authors_m149, :doi_m149), (:title_m150, :abstract_m150, :journal_m150, :date_m150, :authors_m150, :doi_m150), (:title_m151, :abstract_m151, :journal_m151, :date_m151, :authors_m151, :doi_m151), (:title_m152, :abstract_m152, :journal_m152, :date_m152, :authors_m152, :doi_m152), (:title_m153, :abstract_m153, :journal_m153, :date_m153, :authors_m153, :doi_m153), (:title_m154, :abstract_m154, :journal_m154, :date_m154, :authors_m154, :doi_m154), (:title_m155, :abstract_m155, :journal_m155, :date_m155, :authors_m155, :doi_m155), (:title_m156, :abstract_m156, :journal_m156, :date_m156, :authors_m156, :doi_m156), (:title_m157, :abstract_m157, :journal_m157, :date_m157, :authors_m157, :doi_m157), (:title_m158, :abstract_m158, :journal_m158, :date_m158, :authors_m158, :doi_m158), (:title_m159, :abstract_m159, :journal_m159, :date_m159, :authors_m159, :doi_m159), (:title_m160, :abstract_m160, :journal_m160, :date_m160, :authors_m160, :doi_m160), (:title_m161, :abstract_m161, :journal_m161, :date_m161, :authors_m161, :doi_m161), (:title_m162, :abstract_m162, :journal_m162, :date_m162, :authors_m162, :doi_m162), (:title_m163, :abstract_m163, :journal_m163, :date_m163, :authors_m163, :doi_m163), (:title_m164, :abstract_m164, :journal_m164, :date_m164, :authors_m164, :doi_m164), (:title_m165, :abstract_m165, :journal_m165, :date_m165, :authors_m165, :doi_m165), (:title_m166, :abstract_m166, :journal_m166, :date_m166, :authors_m166, :doi_m166), (:title_m167, :abstract_m167, :journal_m167, :date_m167, :authors_m167, :doi_m167), (:title_m168, :abstract_m168, :journal_m168, :date_m168, :authors_m168, :doi_m168), (:title_m169, :abstract_m169, :journal_m169, :date_m169, :authors_m169, :doi_m169), (:title_m170, :abstract_m170, :journal_m170, :date_m170, :authors_m170, :doi_m170), (:title_m171, :abstract_m171, :journal_m171, :date_m171, :authors_m171, :doi_m171), (:title_m172, :abstract_m172, :journal_m172, :date_m172, :authors_m172, :doi_m172), (:title_m173, :abstract_m173, :journal_m173, :date_m173, :authors_m173, :doi_m173), (:title_m174, :abstract_m174, :journal_m174, :date_m174, :authors_m174, :doi_m174), (:title_m175, :abstract_m175, :journal_m175, :date_m175, :authors_m175, :doi_m175), (:title_m176, :abstract_m176, :journal_m176, :date_m176, :authors_m176, :doi_m176), (:title_m177, :abstract_m177, :journal_m177, :date_m177, :authors_m177, :doi_m177), (:title_m178, :abstract_m178, :journal_m178, :date_m178, :authors_m178, :doi_m178), (:title_m179, :abstract_m179, :journal_m179, :date_m179, :authors_m179, :doi_m179), (:title_m180, :abstract_m180, :journal_m180, :date_m180, :authors_m180, :doi_m180), (:title_m181, :abstract_m181, :journal_m181, :date_m181, :authors_m181, :doi_m181), (:title_m182, :abstract_m182, :journal_m182, :date_m182, :authors_m182, :doi_m182), (:title_m183, :abstract_m183, :journal_m183, :date_m183, :authors_m183, :doi_m183), (:title_m184, :abstract_m184, :journal_m184, :date_m184, :authors_m184, :doi_m184), (:title_m185, :abstract_m185, :journal_m185, :date_m185, :authors_m185, :doi_m185), (:title_m186, :abstract_m186, :journal_m186, :date_m186, :authors_m186, :doi_m186), (:title_m187, :abstract_m187, :journal_m187, :date_m187, :authors_m187, :doi_m187), (:title_m188, :abstract_m188, :journal_m188, :date_m188, :authors_m188, :doi_m188), (:title_m189, :abstract_m189, :journal_m189, :date_m189, :authors_m189, :doi_m189), (:title_m190, :abstract_m190, :journal_m190, :date_m190, :authors_m190, :doi_m190), (:title_m191, :abstract_m191, :journal_m191, :date_m191, :authors_m191, :doi_m191), (:title_m192, :abstract_m192, :journal_m192, :date_m192, :authors_m192, :doi_m192), (:title_m193, :abstract_m193, :journal_m193, :date_m193, :authors_m193, :doi_m193), (:title_m194, :abstract_m194, :journal_m194, :date_m194, :authors_m194, :doi_m194), (:title_m195, :abstract_m195, :journal_m195, :date_m195, :authors_m195, :doi_m195), (:title_m196, :abstract_m196, :journal_m196, :date_m196, :authors_m196, :doi_m196), (:title_m197, :abstract_m197, :journal_m197, :date_m197, :authors_m197, :doi_m197), (:title_m198, :abstract_m198, :journal_m198, :date_m198, :authors_m198, :doi_m198), (:title_m199, :abstract_m199, :journal_m199, :date_m199, :authors_m199, :doi_m199), (:title_m200, :abstract_m200, :journal_m200, :date_m200, :authors_m200, :doi_m200), (:title_m201, :abstract_m201, :journal_m201, :date_m201, :authors_m201, :doi_m201), (:title_m202, :abstract_m202, :journal_m202, :date_m202, :authors_m202, :doi_m202), (:title_m203, :abstract_m203, :journal_m203, :date_m203, :authors_m203, :doi_m203), (:title_m204, :abstract_m204, :journal_m204, :date_m204, :authors_m204, :doi_m204), (:title_m205, :abstract_m205, :journal_m205, :date_m205, :authors_m205, :doi_m205), (:title_m206, :abstract_m206, :journal_m206, :date_m206, :authors_m206, :doi_m206), (:title_m207, :abstract_m207, :journal_m207, :date_m207, :authors_m207, :doi_m207), (:title_m208, :abstract_m208, :journal_m208, :date_m208, :authors_m208, :doi_m208), (:title_m209, :abstract_m209, :journal_m209, :date_m209, :authors_m209, :doi_m209), (:title_m210, :abstract_m210, :journal_m210, :date_m210, :authors_m210, :doi_m210), (:title_m211, :abstract_m211, :journal_m211, :date_m211, :authors_m211, :doi_m211), (:title_m212, :abstract_m212, :journal_m212, :date_m212, :authors_m212, :doi_m212), (:title_m213, :abstract_m213, :journal_m213, :date_m213, :authors_m213, :doi_m213), (:title_m214, :abstract_m214, :journal_m214, :date_m214, :authors_m214, :doi_m214), (:title_m215, :abstract_m215, :journal_m215, :date_m215, :authors_m215, :doi_m215), (:title_m216, :abstract_m216, :journal_m216, :date_m216, :authors_m216, :doi_m216), (:title_m217, :abstract_m217, :journal_m217, :date_m217, :authors_m217, :doi_m217), (:title_m218, :abstract_m218, :journal_m218, :date_m218, :authors_m218, :doi_m218), (:title_m219, :abstract_m219, :journal_m219, :date_m219, :authors_m219, :doi_m219), (:title_m220, :abstract_m220, :journal_m220, :date_m220, :authors_m220, :doi_m220), (:title_m221, :abstract_m221, :journal_m221, :date_m221, :authors_m221, :doi_m221), (:title_m222, :abstract_m222, :journal_m222, :date_m222, :authors_m222, :doi_m222), (:title_m223, :abstract_m223, :journal_m223, :date_m223, :authors_m223, :doi_m223), (:title_m224, :abstract_m224, :journal_m224, :date_m224, :authors_m224, :doi_m224), (:title_m225, :abstract_m225, :journal_m225, :date_m225, :authors_m225, :doi_m225), (:title_m226, :abstract_m226, :journal_m226, :date_m226, :authors_m226, :doi_m226), (:title_m227, :abstract_m227, :journal_m227, :date_m227, :authors_m227, :doi_m227), (:title_m228, :abstract_m228, :journal_m228, :date_m228, :authors_m228, :doi_m228), (:title_m229, :abstract_m229, :journal_m229, :date_m229, :authors_m229, :doi_m229), (:title_m230, :abstract_m230, :journal_m230, :date_m230, :authors_m230, :doi_m230), (:title_m231, :abstract_m231, :journal_m231, :date_m231, :authors_m231, :doi_m231), (:title_m232, :abstract_m232, :journal_m232, :date_m232, :authors_m232, :doi_m232), (:title_m233, :abstract_m233, :journal_m233, :date_m233, :authors_m233, :doi_m233), (:title_m234, :abstract_m234, :journal_m234, :date_m234, :authors_m234, :doi_m234), (:title_m235, :abstract_m235, :journal_m235, :date_m235, :authors_m235, :doi_m235), (:title_m236, :abstract_m236, :journal_m236, :date_m236, :authors_m236, :doi_m236), (:title_m237, :abstract_m237, :journal_m237, :date_m237, :authors_m237, :doi_m237), (:title_m238, :abstract_m238, :journal_m238, :date_m238, :authors_m238, :doi_m238), (:title_m239, :abstract_m239, :journal_m239, :date_m239, :authors_m239, :doi_m239), (:title_m240, :abstract_m240, :journal_m240, :date_m240, :authors_m240, :doi_m240), (:title_m241, :abstract_m241, :journal_m241, :date_m241, :authors_m241, :doi_m241), (:title_m242, :abstract_m242, :journal_m242, :date_m242, :authors_m242, :doi_m242), (:title_m243, :abstract_m243, :journal_m243, :date_m243, :authors_m243, :doi_m243), (:title_m244, :abstract_m244, :journal_m24