In [2]:
import pandas as pd
import polars as pl
from datetime import date
from rake_nltk import Rake

# final raw pubmed data (no abstract or author)

In [27]:
pm_df = pd.read_csv("/Users/shantibrodnick/Downloads/510Capstone/GenderDisparityinResearch/data/raw/final_raw_pubmed_data.csv")

In [ ]:
pm_df.info()
# 10,206,788 rows

<class 'pandas.DataFrame'>
RangeIndex: 10206788 entries, 0 to 10206787
Data columns (total 5 columns):
 #   Column      Dtype
---  ------      -----
 0   Unnamed: 0  int64
 1   title       str
 2   journal     str
 3   date        str
 4   doi         str
dtypes: int64(1), str(4)
memory usage: 2.0 GB

In [4]:
pm_df

,Unnamed: 0,title,journal,date,doi
0,0,Anti-tumor necrosis factor-alpha antibody trea...,Rheumatology international,2006-10-20,10.1007/s00296-006-0241-1
1,1,[Quantification of expression of leukotriene B...,Beijing da xue xue bao. Yi xue ban = Journal o...,2006-10-28,NaN
2,2,Interleukin-7 induced immunopathology in arthr...,Annals of the rheumatic diseases,2006-10-14,10.1136/ard.2006.058479
3,3,High-throughput quantitation of metabolically ...,"Methods in molecular biology (Clifton, N.J.)",2006-10-31,10.1385/1-59745-167-3:267
4,4,Pulsed electrical stimulation to defer TKA in ...,Orthopedics,2006-10-26,10.3928/01477447-20061001-13
...,...,...,...,...,...
10206783,10206783,Reframing precision nutrition in irritable bow...,Frontiers in immunology,2026-06-15,10.3389/fimmu.2026.1809221
10206784,10206784,Serum neurofilament light chain in paediatric ...,"Multiple sclerosis (Houndmills, Basingstoke, E...",2026-06-23,10.1177/13524585261450816
10206785,10206785,Solvent-free engineering of a co-amorphous efa...,International journal of pharmaceutics,2026-06-11,10.1016/j.ijpharm.2026.127068
10206786,10206786,Longitudinal assessment of myocardial involvem...,Frontiers in cardiovascular medicine,2026-06-03,10.3389/fcvm.2026.1725291
10206787,10206787,MRPS22 variants alter mitochondrial ribosome a...,Human molecular genetics,2026-06-03,10.1093/hmg/ddag042

In [8]:
pm_df = pm_df.drop(['Unnamed: 0'], axis = 1)

In [9]:
pm_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10206788 entries, 0 to 10206787
Data columns (total 4 columns):
 #   Column   Dtype
---  ------   -----
 0   title    str
 1   journal  str
 2   date     str
 3   doi      str
dtypes: str(4)
memory usage: 2.0 GB

In [12]:
pm_df['title'].head().tolist()

['Anti-tumor necrosis factor-alpha antibody treatment reduces serum CXCL16 levels in patients with rheumatoid arthritis.',
 '[Quantification of expression of leukotriene B4 inducing tumor necrosis factor-alpha and interleukin-1beta at mRNA level in synovial membrane cells of rheumatoid arthritis by real-time quantitative PCR].',
 'Interleukin-7 induced immunopathology in arthritis.',
 'High-throughput quantitation of metabolically labeled anionic glycoconjugates by scintillation proximity assay utilizing binding to cationic dyes.',
 'Pulsed electrical stimulation to defer TKA in patients with knee osteoarthritis.']

# cleaned_raw_pubmed_data.csv into LAZYFRAME

In [3]:
raw_df = pl.scan_csv("/Users/shantibrodnick/Downloads/510Capstone/GenderDisparityinResearch/notebooks/Article_Data_APIs/data/cleaned_raw_pubmed_data.csv")

In [5]:
raw_df.select(pl.len()).collect().item()
# 10,206,788 rows

10206788

In [28]:
raw_df.head(2).collect()

shape: (2, 6)
┌─────────────────┬────────────────┬────────────────┬────────────┬────────────────┬────────────────┐
│ title           ┆ abstract       ┆ journal        ┆ date       ┆ authors        ┆ doi            │
│ ---             ┆ ---            ┆ ---            ┆ ---        ┆ ---            ┆ ---            │
│ str             ┆ str            ┆ str            ┆ str        ┆ str            ┆ str            │
╞═════════════════╪════════════════╪════════════════╪════════════╪════════════════╪════════════════╡
│ Anti-tumor      ┆ The aim of     ┆ Rheumatology   ┆ 2006-10-20 ┆ ['YasunoriKage ┆ 10.1007/s00296 │
│ necrosis        ┆ this study was ┆ international  ┆            ┆ yama',         ┆ -006-0241-1    │
│ factor-alp…     ┆ to a…          ┆                ┆            ┆ 'EijiTori…     ┆                │
│ [Quantification ┆ To investigate ┆ Beijing da xue ┆ 2006-10-28 ┆ ['Zhan-kunChen ┆ null           │
│ of expression … ┆ quantification ┆ xue bao. Yi    ┆            ┆ ',             ┆                │
│                 ┆ …              ┆ xue…           ┆            ┆ 'Hou-shanLv']  ┆                │
└─────────────────┴────────────────┴────────────────┴────────────┴────────────────┴────────────────┘

## Date Cleaning for that one column

In [33]:
# Find all the length of all unique dates
raw_df.select(pl.col('date').cast(pl.String).str.len_chars()).unique().collect()
# 4, 10, and 98
# 98 is odd

shape: (3, 1)
┌──────┐
│ date │
│ ---  │
│ u32  │
╞══════╡
│ 10   │
│ 4    │
│ 98   │
└──────┘

In [34]:
# The 98 was the formatting issue which is taken care of in the pubmed_final_data_export.ipynb
raw_df.filter(pl.col('date').cast(pl.String).str.len_chars() == 98).collect()

shape: (1, 6)
┌──────────────────────┬─────────────────────┬─────────┬──────────────┬─────────────────────┬──────┐
│ title                ┆ abstract            ┆ journal ┆ date         ┆ authors             ┆ doi  │
│ ---                  ┆ ---                 ┆ ---     ┆ ---          ┆ ---                 ┆ ---  │
│ str                  ┆ str                 ┆ str     ┆ str          ┆ str                 ┆ str  │
╞══════════════════════╪═════════════════════╪═════════╪══════════════╪═════════════════════╪══════╡
│ Comparing Essure®    ┆ Hundreds of         ┆ 2021    ┆ ['Aileen     ┆ 10.25302/10.2021.CE ┆ null │
│ and Tubal Li…        ┆ thousands of US wo… ┆         ┆ M.Gariepy',  ┆ R.160936359         ┆      │
│                      ┆                     ┆         ┆ 'Daniel J…   ┆                     ┆      │
└──────────────────────┴─────────────────────┴─────────┴──────────────┴─────────────────────┴──────┘

In [35]:
# Define row that is all shifted over
row = pl.col('date').cast(pl.String).str.len_chars() == 98

In [36]:
# Replace like we did in pubmed_final_data_export
f_raw_df = raw_df.with_columns([
    pl.when(row).then(pl.col('date')).otherwise(pl.col('authors')).alias('authors'),
    pl.when(row).then(pl.col('journal')).otherwise(pl.col('date')).alias('date'),
    pl.when(row).then(None).otherwise(pl.col('journal')).alias('journal')
])

In [37]:
# Check to see if the row changed
f_raw_df.filter(pl.col('doi') == "10.25302/10.2021.CER.160936359").collect()
# YAY IT DID

shape: (1, 6)
┌──────────────────────┬─────────────────────┬─────────┬──────┬──────────────┬─────────────────────┐
│ title                ┆ abstract            ┆ journal ┆ date ┆ authors      ┆ doi                 │
│ ---                  ┆ ---                 ┆ ---     ┆ ---  ┆ ---          ┆ ---                 │
│ str                  ┆ str                 ┆ str     ┆ str  ┆ str          ┆ str                 │
╞══════════════════════╪═════════════════════╪═════════╪══════╪══════════════╪═════════════════════╡
│ Comparing Essure®    ┆ Hundreds of         ┆ null    ┆ 2021 ┆ ['Aileen     ┆ 10.25302/10.2021.CE │
│ and Tubal Li…        ┆ thousands of US wo… ┆         ┆      ┆ M.Gariepy',  ┆ R.160936359         │
│                      ┆                     ┆         ┆      ┆ 'Daniel J…   ┆                     │
└──────────────────────┴─────────────────────┴─────────┴──────┴──────────────┴─────────────────────┘

In [38]:
# Find the row with 4
raw_df.filter(pl.col('date').cast(pl.String).str.len_chars() == 4).collect()

shape: (4_976, 6)
┌────────────────────┬────────────────────┬─────────┬──────┬───────────────────┬───────────────────┐
│ title              ┆ abstract           ┆ journal ┆ date ┆ authors           ┆ doi               │
│ ---                ┆ ---                ┆ ---     ┆ ---  ┆ ---               ┆ ---               │
│ str                ┆ str                ┆ str     ┆ str  ┆ str               ┆ str               │
╞════════════════════╪════════════════════╪═════════╪══════╪═══════════════════╪═══════════════════╡
│ Molecular Imaging  ┆ The Molecular      ┆ null    ┆ 2004 ┆ []                ┆ null              │
│ and Contrast…      ┆ Imaging and Cont…  ┆         ┆      ┆                   ┆                   │
│ Screening for      ┆ To assess evidence ┆ null    ┆ 2006 ┆ ['Evelyn          ┆ null              │
│ Hereditary Hemoc…  ┆ sufficiency…       ┆         ┆      ┆ PWhitlock',       ┆                   │
│                    ┆                    ┆         ┆      ┆ 'Betsy AG…        ┆                   │
│ WHO Guideline on   ┆ Since the          ┆ null    ┆ 2017 ┆ []                ┆ null              │
│ Syphilis Scre…     ┆ publication of the ┆         ┆      ┆                   ┆                   │
│                    ┆ W…                 ┆         ┆      ┆                   ┆                   │
│ Using nationwide   ┆ Electronic health  ┆ null    ┆ 2017 ┆ ['HarryHemingway' ┆ 10.3310/pgfar0504 │
│ ‘big data’ fr…     ┆ records (EHR…      ┆         ┆      ┆ , 'Gene SFede…    ┆ 0                 │
│ Can Coping-Skills  ┆ Many survivors of  ┆ null    ┆ 2018 ┆ ['Christopher     ┆ 10.25302/9.2018.C │
│ Training Hel…      ┆ critical ill…      ┆         ┆      ┆ E.Cox', 'Catheri… ┆ ER.195            │
│ …                  ┆ …                  ┆ …       ┆ …    ┆ …                 ┆ …                 │
│ Recommendations    ┆ Evidence-informed  ┆ null    ┆ 2013 ┆ []                ┆ null              │
│ for Drug Thera…    ┆ recommendati…      ┆         ┆      ┆                   ┆                   │
│ Evidence review    ┆ The aim of this    ┆ null    ┆ 2019 ┆ ['NoneNone']      ┆ null              │
│ for previous c…    ┆ review is to d…    ┆         ┆      ┆                   ┆                   │
│ WHO consolidated   ┆ Respiratory        ┆ null    ┆ 2026 ┆ []                ┆ null              │
│ guidelines fo…     ┆ illness remains a  ┆         ┆      ┆                   ┆                   │
│                    ┆ …                  ┆         ┆      ┆                   ┆                   │
│ Prepregnancy BMI   ┆ The 2009 National  ┆ null    ┆ 2026 ┆ ['NoneNone',      ┆ 10.17226/29228    │
│ and Gestation…     ┆ Academies re…      ┆         ┆      ┆ 'Erin             ┆                   │
│                    ┆                    ┆         ┆      ┆ HammersFors…      ┆                   │
│ WHO consolidated   ┆ Sickle-cell        ┆ null    ┆ 2026 ┆ []                ┆ null              │
│ guidelines fo…     ┆ disease is a       ┆         ┆      ┆                   ┆                   │
│                    ┆ leadi…             ┆         ┆      ┆                   ┆                   │
└────────────────────┴────────────────────┴─────────┴──────┴───────────────────┴───────────────────┘

In [39]:
# Standardize the date column to make sure it has 10
ff_raw_df = f_raw_df.with_columns(
    pl.when(pl.col('date').cast(pl.String).str.len_chars() == 4).then(pl.col('date').cast(pl.String) + "-01-01")
    .otherwise(pl.col('date').cast(pl.String))
)

In [40]:
# Check to see if it worked
ff_raw_df.select(pl.col('date').cast(pl.String).str.len_chars()).unique().collect()
# Yay it worked!

shape: (1, 1)
┌──────┐
│ date │
│ ---  │
│ u32  │
╞══════╡
│ 10   │
└──────┘

In [43]:
ff_raw_df.select(pl.col('date').max()).collect()

shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ str        │
╞════════════╡
│ 2026-07-01 │
└────────────┘

In [55]:
ff_raw_df.select(pl.col('date').min()).collect()

shape: (1, 1)
┌────────────┐
│ date       │
│ ---        │
│ str        │
╞════════════╡
│ 1781-06-01 │
└────────────┘

### Change date to datetime

In [44]:
# Change rows to datetime
dt_raw_df = ff_raw_df.with_columns(
    pl.col('date').str.strptime(pl.Date, format = "%Y-%m-%d")
    )

In [45]:
#pl.Config.restore_defaults()
dt_raw_df.head(2).collect()

shape: (2, 6)
┌─────────────────┬────────────────┬────────────────┬────────────┬────────────────┬────────────────┐
│ title           ┆ abstract       ┆ journal        ┆ date       ┆ authors        ┆ doi            │
│ ---             ┆ ---            ┆ ---            ┆ ---        ┆ ---            ┆ ---            │
│ str             ┆ str            ┆ str            ┆ date       ┆ str            ┆ str            │
╞═════════════════╪════════════════╪════════════════╪════════════╪════════════════╪════════════════╡
│ Anti-tumor      ┆ The aim of     ┆ Rheumatology   ┆ 2006-10-20 ┆ ['YasunoriKage ┆ 10.1007/s00296 │
│ necrosis        ┆ this study was ┆ international  ┆            ┆ yama',         ┆ -006-0241-1    │
│ factor-alp…     ┆ to a…          ┆                ┆            ┆ 'EijiTori…     ┆                │
│ [Quantification ┆ To investigate ┆ Beijing da xue ┆ 2006-10-28 ┆ ['Zhan-kunChen ┆ null           │
│ of expression … ┆ quantification ┆ xue bao. Yi    ┆            ┆ ',             ┆                │
│                 ┆ …              ┆ xue…           ┆            ┆ 'Hou-shanLv']  ┆                │
└─────────────────┴────────────────┴────────────────┴────────────┴────────────────┴────────────────┘

### Drop authors column

In [58]:
dt_drop_raw_df = dt_raw_df.drop(['authors'])

## Now I want to filter for only years between 1948 - 2026

In [26]:
# Filter between 1948 - 2026
fil_raw_df = dt_raw_df.filter(pl.col('date').is_between(date(1948, 1, 1), date(2026, 6, 30)))

In [ ]:
# Check row count now
fil_raw_df.select(pl.len()).collect().item()
# 10,185,407
# Too big

10185407

In [ ]:
#raw_df_00_26.select(pl.len()).collect().item()
# 9,380,169
# #raw_df_00_26.collect().estimated_size("mb")
# 14 GB

9380169

In [55]:
#pl.Config(fmt_str_lengths=2000, tbl_rows=2)
fil_raw_df.head(2).collect()

shape: (2, 6)
┌─────────────────┬────────────────┬────────────────┬────────────┬────────────────┬────────────────┐
│ title           ┆ abstract       ┆ journal        ┆ date       ┆ authors        ┆ doi            │
│ ---             ┆ ---            ┆ ---            ┆ ---        ┆ ---            ┆ ---            │
│ str             ┆ str            ┆ str            ┆ date       ┆ str            ┆ str            │
╞═════════════════╪════════════════╪════════════════╪════════════╪════════════════╪════════════════╡
│ Anti-tumor      ┆ The aim of     ┆ Rheumatology   ┆ 2006-10-20 ┆ ['YasunoriKage ┆ 10.1007/s00296 │
│ necrosis        ┆ this study was ┆ international  ┆            ┆ yama',         ┆ -006-0241-1    │
│ factor-alp…     ┆ to a…          ┆                ┆            ┆ 'EijiTori…     ┆                │
│ [Quantification ┆ To investigate ┆ Beijing da xue ┆ 2006-10-28 ┆ ['Zhan-kunChen ┆ null           │
│ of expression … ┆ quantification ┆ xue bao. Yi    ┆            ┆ ',             ┆                │
│                 ┆ …              ┆ xue…           ┆            ┆ 'Hou-shanLv']  ┆                │
└─────────────────┴────────────────┴────────────────┴────────────┴────────────────┴────────────────┘

# Thought
## What if I instead of filtering for years, and only doing 2000 - 2026 or even less, I can try and extract keywords from the abstract of the lazy frame and then save that as a csv.

### Test

In [15]:
# Make a small test lazyframe
test = raw_df.head(5).collect()

In [16]:
test

shape: (5, 6)
┌─────────────────┬────────────────┬────────────────┬────────────┬────────────────┬────────────────┐
│ title           ┆ abstract       ┆ journal        ┆ date       ┆ authors        ┆ doi            │
│ ---             ┆ ---            ┆ ---            ┆ ---        ┆ ---            ┆ ---            │
│ str             ┆ str            ┆ str            ┆ str        ┆ str            ┆ str            │
╞═════════════════╪════════════════╪════════════════╪════════════╪════════════════╪════════════════╡
│ Anti-tumor      ┆ The aim of     ┆ Rheumatology   ┆ 2006-10-20 ┆ ['YasunoriKage ┆ 10.1007/s00296 │
│ necrosis        ┆ this study was ┆ international  ┆            ┆ yama',         ┆ -006-0241-1    │
│ factor-alp…     ┆ to a…          ┆                ┆            ┆ 'EijiTori…     ┆                │
│ [Quantification ┆ To investigate ┆ Beijing da xue ┆ 2006-10-28 ┆ ['Zhan-kunChen ┆ null           │
│ of expression … ┆ quantification ┆ xue bao. Yi    ┆            ┆ ',             ┆                │
│                 ┆ …              ┆ xue…           ┆            ┆ 'Hou-shanLv']  ┆                │
│ Interleukin-7   ┆ Interleukin    ┆ Annals of the  ┆ 2006-10-14 ┆ ['S A          ┆ 10.1136/ard.20 │
│ induced         ┆ (IL)-7 is a    ┆ rheumatic      ┆            ┆ YHartgring',   ┆ 06.058479      │
│ immunopa…       ┆ potent…        ┆ diseas…        ┆            ┆ 'J W JBijls…   ┆                │
│ High-throughput ┆ Rapid,         ┆ Methods in     ┆ 2006-10-31 ┆ ['Karen        ┆ 10.1385/1-5974 │
│ quantitation o… ┆ quantitative   ┆ molecular      ┆            ┆ JRees-Milton', ┆ 5-167-3:267    │
│                 ┆ methods su…    ┆ biology (…     ┆            ┆ 'Tassos…       ┆                │
│ Pulsed          ┆ null           ┆ Orthopedics    ┆ 2006-10-26 ┆ ['Michael      ┆ 10.3928/014774 │
│ electrical      ┆                ┆                ┆            ┆ AMont', 'David ┆ 47-20061001-13 │
│ stimulation …   ┆                ┆                ┆            ┆ SHung…         ┆                │
└─────────────────┴────────────────┴────────────────┴────────────┴────────────────┴────────────────┘

In [17]:
# View lenngth of each abstract
test.with_columns(
    pl.col('abstract').str.len_chars()
)

shape: (5, 6)
┌──────────────────┬──────────┬──────────────────┬────────────┬──────────────────┬─────────────────┐
│ title            ┆ abstract ┆ journal          ┆ date       ┆ authors          ┆ doi             │
│ ---              ┆ ---      ┆ ---              ┆ ---        ┆ ---              ┆ ---             │
│ str              ┆ u32      ┆ str              ┆ str        ┆ str              ┆ str             │
╞══════════════════╪══════════╪══════════════════╪════════════╪══════════════════╪═════════════════╡
│ Anti-tumor       ┆ 925      ┆ Rheumatology     ┆ 2006-10-20 ┆ ['YasunoriKageya ┆ 10.1007/s00296- │
│ necrosis         ┆          ┆ international    ┆            ┆ ma', 'EijiTori…  ┆ 006-0241-1      │
│ factor-alp…      ┆          ┆                  ┆            ┆                  ┆                 │
│ [Quantification  ┆ 1589     ┆ Beijing da xue   ┆ 2006-10-28 ┆ ['Zhan-kunChen', ┆ null            │
│ of expression …  ┆          ┆ xue bao. Yi xue… ┆            ┆ 'Hou-shanLv']    ┆                 │
│ Interleukin-7    ┆ 1425     ┆ Annals of the    ┆ 2006-10-14 ┆ ['S A            ┆ 10.1136/ard.200 │
│ induced          ┆          ┆ rheumatic        ┆            ┆ YHartgring', 'J  ┆ 6.058479        │
│ immunopa…        ┆          ┆ diseas…          ┆            ┆ W JBijls…        ┆                 │
│ High-throughput  ┆ 1730     ┆ Methods in       ┆ 2006-10-31 ┆ ['Karen          ┆ 10.1385/1-59745 │
│ quantitation o…  ┆          ┆ molecular        ┆            ┆ JRees-Milton',   ┆ -167-3:267      │
│                  ┆          ┆ biology (…       ┆            ┆ 'Tassos…         ┆                 │
│ Pulsed           ┆ null     ┆ Orthopedics      ┆ 2006-10-26 ┆ ['Michael        ┆ 10.3928/0147744 │
│ electrical       ┆          ┆                  ┆            ┆ AMont', 'David   ┆ 7-20061001-13   │
│ stimulation …    ┆          ┆                  ┆            ┆ SHung…           ┆                 │
└──────────────────┴──────────┴──────────────────┴────────────┴──────────────────┴─────────────────┘

In [74]:
with pl.Config(fmt_str_lengths=2000, tbl_rows=2):
    print(test.tail(2))

shape: (2, 6)
┌─────────────────┬─────────────────┬─────────────┬────────────┬─────────────────┬─────────────────┐
│ title           ┆ abstract        ┆ journal     ┆ date       ┆ authors         ┆ doi             │
│ ---             ┆ ---             ┆ ---         ┆ ---        ┆ ---             ┆ ---             │
│ str             ┆ str             ┆ str         ┆ str        ┆ str             ┆ str             │
╞═════════════════╪═════════════════╪═════════════╪════════════╪═════════════════╪═════════════════╡
│ High-throughput ┆ Rapid,          ┆ Methods in  ┆ 2006-10-31 ┆ ['Karen         ┆ 10.1385/1-59745 │
│ quantitation of ┆ quantitative    ┆ molecular   ┆            ┆ JRees-Milton',  ┆ -167-3:267      │
│ metabolically   ┆ methods suited  ┆ biology     ┆            ┆ 'Tassos PAnasta ┆                 │
│ labeled anionic ┆ to a large      ┆ (Clifton,   ┆            ┆ ssiades']       ┆                 │
│ glycoconjugates ┆ number of       ┆ N.J.)       ┆            ┆                 ┆                 │
│ by              ┆ samples are     ┆             ┆            ┆                 ┆                 │
│ scintillation   ┆ required for    ┆             ┆            ┆                 ┆                 │
│ proximity assay ┆ studies into    ┆             ┆            ┆                 ┆                 │
│ utilizing       ┆ the             ┆             ┆            ┆                 ┆                 │
│ binding to      ┆ determination   ┆             ┆            ┆                 ┆                 │
│ cationic dyes.  ┆ of disease      ┆             ┆            ┆                 ┆                 │
│                 ┆ etiology and in ┆             ┆            ┆                 ┆                 │
│                 ┆ the evaluation  ┆             ┆            ┆                 ┆                 │
│                 ┆ of drugs and    ┆             ┆            ┆                 ┆                 │
│                 ┆ biological      ┆             ┆            ┆                 ┆                 │
│                 ┆ agents. This    ┆             ┆            ┆                 ┆                 │
│                 ┆ chapter         ┆             ┆            ┆                 ┆                 │
│                 ┆ describes an    ┆             ┆            ┆                 ┆                 │
│                 ┆ assay for       ┆             ┆            ┆                 ┆                 │
│                 ┆ anionic         ┆             ┆            ┆                 ┆                 │
│                 ┆ glycoconjugates ┆             ┆            ┆                 ┆                 │
│                 ┆ (GCs),          ┆             ┆            ┆                 ┆                 │
│                 ┆ including glyco ┆             ┆            ┆                 ┆                 │
│                 ┆ saminoglycans,  ┆             ┆            ┆                 ┆                 │
│                 ┆ which are major ┆             ┆            ┆                 ┆                 │
│                 ┆ gene products   ┆             ┆            ┆                 ┆                 │
│                 ┆ of chondrocytes ┆             ┆            ┆                 ┆                 │
│                 ┆ appearing in    ┆             ┆            ┆                 ┆                 │
│                 ┆ the             ┆             ┆            ┆                 ┆                 │
│                 ┆ extracellular   ┆             ┆            ┆                 ┆                 │
│                 ┆ matrix. The     ┆             ┆            ┆                 ┆                 │
│                 ┆ assay utilizes  ┆             ┆            ┆                 ┆                 │
│                 ┆ the             ┆             ┆            ┆                 ┆                 │
│                 ┆ electrostatic   ┆             ┆            ┆                 ┆                 │
│                 ┆ interaction     ┆             ┆            ┆                 ┆                 │
│                 ┆ between         ┆             ┆            ┆                 ┆                 │
│                 ┆ negatively      ┆             ┆            ┆                 ┆                 │
│                 ┆ charged sulfate ┆             ┆            ┆                 ┆                 │
│                 ┆ and carboxyl    ┆             ┆            ┆                 ┆                 │
│                 ┆ groups of       ┆             ┆            ┆                 ┆                 │
│                 ┆ anionic GCs     ┆             ┆            ┆                 ┆                 │
│                 ┆ synthesized and ┆             ┆            ┆                 ┆                 │
│                 ┆ secreted by     ┆             ┆            ┆                 ┆                 │
│                 ┆ chondrocytes    ┆             ┆            ┆                 ┆                 │
│                 ┆ with the        ┆             ┆            ┆                 ┆                 │
│                 ┆ cationic dye    ┆             ┆            ┆                 ┆                 │
│                 ┆ Alcian blue,    ┆             ┆            ┆                 ┆                 │
│                 ┆ immobilized to  ┆             ┆            ┆                 ┆                 │
│                 ┆ scintillant-coa ┆             ┆            ┆                 ┆                 │
│                 ┆ ted 96-well     ┆             ┆            ┆                 ┆                 │
│                 ┆ plates.         ┆             ┆            ┆                 ┆                 │
│                 ┆ Metabolic       ┆             ┆            ┆                 ┆                 │
│                 ┆ labeling with   ┆             ┆            ┆                 ┆                 │
│                 ┆ D-[1, 6-3H (N)] ┆             ┆            ┆                 ┆                 │
│                 ┆ -glucosamine    ┆             ┆            ┆                 ┆                 │
│                 ┆ allows all      ┆             ┆            ┆                 ┆                 │
│                 ┆ anionic GCs,    ┆             ┆            ┆                 ┆                 │
│                 ┆ including carti ┆             ┆            ┆                 ┆                 │
│                 ┆ lage-specific   ┆             ┆            ┆                 ┆                 │
│                 ┆ and hyperglycos ┆             ┆            ┆                 ┆                 │
│                 ┆ ylated variants ┆             ┆            ┆                 ┆                 │
│                 ┆ of fibronectin, ┆             ┆            ┆                 ┆                 │
│                 ┆ to be           ┆             ┆            ┆                 ┆                 │
│                 ┆ quantitated. If ┆             ┆            ┆                 ┆                 │
│                 ┆ Na235SO4 is     ┆             ┆            ┆                 ┆                 │
│                 ┆ used for the    ┆             ┆            ┆                 ┆                 │
│                 ┆ metabolic       ┆             ┆            ┆                 ┆                 │
│                 ┆ labeling        ┆             ┆            ┆                 ┆                 │
│                 ┆ instead, only   ┆             ┆            ┆                 ┆                 │
│                 ┆ glycosaminoglyc ┆             ┆            ┆                 ┆                 │
│                 ┆ ans and         ┆             ┆            ┆                 ┆                 │
│                 ┆ proteoglycans   ┆             ┆            ┆                 ┆                 │
│                 ┆ will be         ┆             ┆            ┆                 ┆                 │
│                 ┆ quantitated.    ┆             ┆            ┆                 ┆                 │
│                 ┆ The samples are ┆             ┆            ┆                 ┆                 │
│                 ┆ counted using a ┆             ┆            ┆                 ┆                 │
│                 ┆ multi-detector  ┆             ┆            ┆                 ┆                 │
│                 ┆ instrument for  ┆             ┆            ┆                 ┆                 │
│                 ┆ scintillation   ┆             ┆            ┆                 ┆                 │
│                 ┆ proximity       ┆             ┆            ┆                 ┆                 │
│                 ┆ assays, such as ┆             ┆            ┆                 ┆                 │
│                 ┆ the Wallac 1450 ┆             ┆            ┆                 ┆                 │
│                 ┆ Microbeta       ┆             ┆            ┆                 ┆                 │
│                 ┆ Trilux,         ┆             ┆            ┆                 ┆                 │
│                 ┆ designed for    ┆             ┆            ┆                 ┆                 │
│                 ┆ detection of    ┆             ┆            ┆                 ┆                 │
│                 ┆ samples in      ┆             ┆            ┆                 ┆                 │
│                 ┆ 96-well plates  ┆             ┆            ┆                 ┆                 │
│                 ┆ and, as such,   ┆             ┆            ┆                 ┆                 │
│                 ┆ can be a        ┆             ┆            ┆                 ┆                 │
│                 ┆ high-throughput ┆             ┆            ┆                 ┆                 │
│                 ┆ system. The     ┆             ┆            ┆                 ┆                 │
│                 ┆ bound anionic   ┆             ┆            ┆                 ┆                 │
│                 ┆ GCs can be      ┆             ┆            ┆                 ┆                 │
│                 ┆ visualized by   ┆             ┆            ┆                 ┆                 │
│                 ┆ sodium dodecyl  ┆             ┆            ┆                 ┆                 │
│                 ┆ sulfate-polyacr ┆             ┆            ┆                 ┆                 │
│                 ┆ ylamide gel     ┆             ┆            ┆                 ┆                 │
│                 ┆ electrophoresis ┆             ┆            ┆                 ┆                 │
│                 ┆ after           ┆             ┆            ┆                 ┆                 │
│                 ┆ quantitation by ┆             ┆            ┆                 ┆                 │
│                 ┆ elution with    ┆             ┆            ┆                 ┆                 │
│                 ┆ denaturing      ┆             ┆            ┆                 ┆                 │
│                 ┆ buffers. The    ┆             ┆            ┆                 ┆                 │
│                 ┆ method can be   ┆             ┆            ┆                 ┆                 │
│                 ┆ modified to     ┆             ┆            ┆                 ┆                 │
│                 ┆ include         ┆             ┆            ┆                 ┆                 │
│                 ┆ predigestion of ┆             ┆            ┆                 ┆                 │
│                 ┆ the sample with ┆             ┆            ┆                 ┆                 │
│                 ┆ a specific      ┆             ┆            ┆                 ┆                 │
│                 ┆ lyase, e.g.,    ┆             ┆            ┆                 ┆                 │
│                 ┆ chondroitinase  ┆             ┆            ┆                 ┆                 │
│                 ┆ ABC or          ┆             ┆            ┆                 ┆                 │
│                 ┆ testicular      ┆             ┆            ┆                 ┆                 │
│                 ┆ hyaluronidase.  ┆             ┆            ┆                 ┆                 │
│                 ┆ To separate     ┆             ┆            ┆                 ┆                 │
│                 ┆ polyanions from ┆             ┆            ┆                 ┆                 │
│                 ┆ other digested  ┆             ┆            ┆                 ┆                 │
│                 ┆ material after  ┆             ┆            ┆                 ┆                 │
│                 ┆ ethanol         ┆             ┆            ┆                 ┆                 │
│                 ┆ precipitation,  ┆             ┆            ┆                 ┆                 │
│                 ┆ the sample can  ┆             ┆            ┆                 ┆                 │
│                 ┆ be assayed as   ┆             ┆            ┆                 ┆                 │
│                 ┆ described in    ┆             ┆            ┆                 ┆                 │
│                 ┆ this chapter    ┆             ┆            ┆                 ┆                 │
│                 ┆ for a           ┆             ┆            ┆                 ┆                 │
│                 ┆ particular      ┆             ┆            ┆                 ┆                 │
│                 ┆ subtype of      ┆             ┆            ┆                 ┆                 │
│                 ┆ anionic GC.     ┆             ┆            ┆                 ┆                 │
│                 ┆ This assay      ┆             ┆            ┆                 ┆                 │
│                 ┆ addresses the   ┆             ┆            ┆                 ┆                 │
│                 ┆ need for        ┆             ┆            ┆                 ┆                 │
│                 ┆ high-throughput ┆             ┆            ┆                 ┆                 │
│                 ┆ applications in ┆             ┆            ┆                 ┆                 │
│                 ┆ arthritis and   ┆             ┆            ┆                 ┆                 │
│                 ┆ other medical   ┆             ┆            ┆                 ┆                 │
│                 ┆ and biological  ┆             ┆            ┆                 ┆                 │
│                 ┆ problems.       ┆             ┆            ┆                 ┆                 │
│ Pulsed          ┆ null            ┆ Orthopedics ┆ 2006-10-26 ┆ ['Michael       ┆ 10.3928/0147744 │
│ electrical      ┆                 ┆             ┆            ┆ AMont', 'David  ┆ 7-20061001-13   │
│ stimulation to  ┆                 ┆             ┆            ┆ SHungerford',   ┆                 │
│ defer TKA in    ┆                 ┆             ┆            ┆ 'Jacques        ┆                 │
│ patients with   ┆                 ┆             ┆            ┆ RCaldwell',     ┆                 │
│ knee            ┆                 ┆             ┆            ┆ 'Phillip        ┆                 │
│ osteoarthritis. ┆                 ┆             ┆            ┆ SRagland',      ┆                 │
│                 ┆                 ┆             ┆            ┆ 'Kent           ┆                 │
│                 ┆                 ┆             ┆            ┆ CHoffman', 'Y   ┆                 │
│                 ┆                 ┆             ┆            ┆ DavidHe',       ┆                 │
│                 ┆                 ┆             ┆            ┆ 'Lynne CJones', ┆                 │
│                 ┆                 ┆             ┆            ┆ 'Thomas         ┆                 │
│                 ┆                 ┆             ┆            ┆ MZizic']        ┆                 │
└─────────────────┴─────────────────┴─────────────┴────────────┴─────────────────┴─────────────────┘

In [22]:
def extract_keyword(text):
    if text is None:
        return []
    r = Rake()
    r.extract_keywords_from_text(str(text))
    return list(dict.fromkeys(r.get_ranked_phrases())) # adding a check to remove duplicates because there seems to be a lot

test_keyword = test.with_columns([
    pl.col('abstract').map_elements(extract_keyword, return_dtype = pl.List(pl.String))
])

In [23]:
test_keyword

shape: (5, 6)
┌─────────────────┬────────────────┬────────────────┬────────────┬────────────────┬────────────────┐
│ title           ┆ abstract       ┆ journal        ┆ date       ┆ authors        ┆ doi            │
│ ---             ┆ ---            ┆ ---            ┆ ---        ┆ ---            ┆ ---            │
│ str             ┆ list[str]      ┆ str            ┆ str        ┆ str            ┆ str            │
╞═════════════════╪════════════════╪════════════════╪════════════╪════════════════╪════════════════╡
│ Anti-tumor      ┆ ["infliximab   ┆ Rheumatology   ┆ 2006-10-20 ┆ ['YasunoriKage ┆ 10.1007/s00296 │
│ necrosis        ┆ treatment      ┆ international  ┆            ┆ yama',         ┆ -006-0241-1    │
│ factor-alp…     ┆ signifi…       ┆                ┆            ┆ 'EijiTori…     ┆                │
│ [Quantification ┆ ["could also   ┆ Beijing da xue ┆ 2006-10-28 ┆ ['Zhan-kunChen ┆ null           │
│ of expression … ┆ remarkably     ┆ xue bao. Yi    ┆            ┆ ',             ┆                │
│                 ┆ dimini…        ┆ xue…           ┆            ┆ 'Hou-shanLv']  ┆                │
│ Interleukin-7   ┆ ["7 induces    ┆ Annals of the  ┆ 2006-10-14 ┆ ['S A          ┆ 10.1136/ard.20 │
│ induced         ┆ tumour         ┆ rheumatic      ┆            ┆ YHartgring',   ┆ 06.058479      │
│ immunopa…       ┆ necrosis fa…   ┆ diseas…        ┆            ┆ 'J W JBijls…   ┆                │
│ High-throughput ┆ ["wallac 1450  ┆ Methods in     ┆ 2006-10-31 ┆ ['Karen        ┆ 10.1385/1-5974 │
│ quantitation o… ┆ microbeta      ┆ molecular      ┆            ┆ JRees-Milton', ┆ 5-167-3:267    │
│                 ┆ trilux…        ┆ biology (…     ┆            ┆ 'Tassos…       ┆                │
│ Pulsed          ┆ null           ┆ Orthopedics    ┆ 2006-10-26 ┆ ['Michael      ┆ 10.3928/014774 │
│ electrical      ┆                ┆                ┆            ┆ AMont', 'David ┆ 47-20061001-13 │
│ stimulation …   ┆                ┆                ┆            ┆ SHung…         ┆                │
└─────────────────┴────────────────┴────────────────┴────────────┴────────────────┴────────────────┘

In [24]:
# view length of each abstract
test_keyword.with_columns(
    pl.col('abstract').list.len()
)

shape: (5, 6)
┌──────────────────┬──────────┬──────────────────┬────────────┬──────────────────┬─────────────────┐
│ title            ┆ abstract ┆ journal          ┆ date       ┆ authors          ┆ doi             │
│ ---              ┆ ---      ┆ ---              ┆ ---        ┆ ---              ┆ ---             │
│ str              ┆ u32      ┆ str              ┆ str        ┆ str              ┆ str             │
╞══════════════════╪══════════╪══════════════════╪════════════╪══════════════════╪═════════════════╡
│ Anti-tumor       ┆ 41       ┆ Rheumatology     ┆ 2006-10-20 ┆ ['YasunoriKageya ┆ 10.1007/s00296- │
│ necrosis         ┆          ┆ international    ┆            ┆ ma', 'EijiTori…  ┆ 006-0241-1      │
│ factor-alp…      ┆          ┆                  ┆            ┆                  ┆                 │
│ [Quantification  ┆ 79       ┆ Beijing da xue   ┆ 2006-10-28 ┆ ['Zhan-kunChen', ┆ null            │
│ of expression …  ┆          ┆ xue bao. Yi xue… ┆            ┆ 'Hou-shanLv']    ┆                 │
│ Interleukin-7    ┆ 72       ┆ Annals of the    ┆ 2006-10-14 ┆ ['S A            ┆ 10.1136/ard.200 │
│ induced          ┆          ┆ rheumatic        ┆            ┆ YHartgring', 'J  ┆ 6.058479        │
│ immunopa…        ┆          ┆ diseas…          ┆            ┆ W JBijls…        ┆                 │
│ High-throughput  ┆ 85       ┆ Methods in       ┆ 2006-10-31 ┆ ['Karen          ┆ 10.1385/1-59745 │
│ quantitation o…  ┆          ┆ molecular        ┆            ┆ JRees-Milton',   ┆ -167-3:267      │
│                  ┆          ┆ biology (…       ┆            ┆ 'Tassos…         ┆                 │
│ Pulsed           ┆ null     ┆ Orthopedics      ┆ 2006-10-26 ┆ ['Michael        ┆ 10.3928/0147744 │
│ electrical       ┆          ┆                  ┆            ┆ AMont', 'David   ┆ 7-20061001-13   │
│ stimulation …    ┆          ┆                  ┆            ┆ SHung…           ┆                 │
└──────────────────┴──────────┴──────────────────┴────────────┴──────────────────┴─────────────────┘

In [26]:
# abstract is now a string in a list so we need to add fmt table cell list len...

with pl.Config(fmt_str_lengths=2000, fmt_table_cell_list_len=100, tbl_rows=2):
    print(test_keyword.head(2))

shape: (2, 6)
┌─────────────────┬────────────────┬────────────────┬────────────┬────────────────┬────────────────┐
│ title           ┆ abstract       ┆ journal        ┆ date       ┆ authors        ┆ doi            │
│ ---             ┆ ---            ┆ ---            ┆ ---        ┆ ---            ┆ ---            │
│ str             ┆ list[str]      ┆ str            ┆ str        ┆ str            ┆ str            │
╞═════════════════╪════════════════╪════════════════╪════════════╪════════════════╪════════════════╡
│ Anti-tumor      ┆ ["infliximab   ┆ Rheumatology   ┆ 2006-10-20 ┆ ['YasunoriKage ┆ 10.1007/s00296 │
│ necrosis        ┆ treatment      ┆ international  ┆            ┆ yama',         ┆ -006-0241-1    │
│ factor-alpha    ┆ significantly  ┆                ┆            ┆ 'EijiTorikai', ┆                │
│ antibody        ┆ lowered",      ┆                ┆            ┆ 'AkiraNagano'] ┆                │
│ treatment       ┆ "gamma         ┆                ┆            ┆                ┆                │
│ reduces serum   ┆ inducible      ┆                ┆            ┆                ┆                │
│ CXCL16 levels   ┆ protein",      ┆                ┆            ┆                ┆                │
│ in patients     ┆ "crucial       ┆                ┆            ┆                ┆                │
│ with rheumatoid ┆ chemokines     ┆                ┆            ┆                ┆                │
│ arthritis.      ┆ regulated",    ┆                ┆            ┆                ┆                │
│                 ┆ "infliximab    ┆                ┆            ┆                ┆                │
│                 ┆ significantly  ┆                ┆            ┆                ┆                │
│                 ┆ decreased",    ┆                ┆            ┆                ┆                │
│                 ┆ "serum         ┆                ┆            ┆                ┆                │
│                 ┆ chemokins      ┆                ┆            ┆                ┆                │
│                 ┆ levels",       ┆                ┆            ┆                ┆                │
│                 ┆ "decrease sign ┆                ┆            ┆                ┆                │
│                 ┆ ificantly",    ┆                ┆            ┆                ┆                │
│                 ┆ "serum         ┆                ┆            ┆                ┆                │
│                 ┆ levels",       ┆                ┆            ┆                ┆                │
│                 ┆ "infliximab    ┆                ┆            ┆                ┆                │
│                 ┆ treatment",    ┆                ┆            ┆                ┆                │
│                 ┆ "higher        ┆                ┆            ┆                ┆                │
│                 ┆ levels",       ┆                ┆            ┆                ┆                │
│                 ┆ "initial       ┆                ┆            ┆                ┆                │
│                 ┆ treatment",    ┆                ┆            ┆                ┆                │
│                 ┆ "rheumatoid    ┆                ┆            ┆                ┆                │
│                 ┆ arthritis",    ┆                ┆            ┆                ┆                │
│                 ┆ "30 weeks",    ┆                ┆            ┆                ┆                │
│                 ┆ "23 patients", ┆                ┆            ┆                ┆                │
│                 ┆ "serum         ┆                ┆            ┆                ┆                │
│                 ┆ fractalkine",  ┆                ┆            ┆                ┆                │
│                 ┆ "ra ),", "10   ┆                ┆            ┆                ┆                │
│                 ┆ levels",       ┆                ┆            ┆                ┆                │
│                 ┆ "serum         ┆                ┆            ┆                ┆                │
│                 ┆ cxcl16", "ra   ┆                ┆            ┆                ┆                │
│                 ┆ patients",     ┆                ┆            ┆                ┆                │
│                 ┆ "infliximab",  ┆                ┆            ┆                ┆                │
│                 ┆ "treatment",   ┆                ┆            ┆                ┆                │
│                 ┆ "patients",    ┆                ┆            ┆                ┆                │
│                 ┆ "ra",          ┆                ┆            ┆                ┆                │
│                 ┆ "fractalkine", ┆                ┆            ┆                ┆                │
│                 ┆ "10",          ┆                ┆            ┆                ┆                │
│                 ┆ "cxcl16",      ┆                ┆            ┆                ┆                │
│                 ┆ "study",       ┆                ┆            ┆                ┆                │
│                 ┆ "studied",     ┆                ┆            ┆                ┆                │
│                 ┆ "period",      ┆                ┆            ┆                ┆                │
│                 ┆ "one",         ┆                ┆            ┆                ┆                │
│                 ┆ "measured",    ┆                ┆            ┆                ┆                │
│                 ┆ "ip",          ┆                ┆            ┆                ┆                │
│                 ┆ "interferon",  ┆                ┆            ┆                ┆                │
│                 ┆ "elisa",       ┆                ┆            ┆                ┆                │
│                 ┆ "effects",     ┆                ┆            ┆                ┆                │
│                 ┆ "cxcl10",      ┆                ┆            ┆                ┆                │
│                 ┆ "cx3cl1",      ┆                ┆            ┆                ┆                │
│                 ┆ "change",      ┆                ┆            ┆                ┆                │
│                 ┆ "baseline",    ┆                ┆            ┆                ┆                │
│                 ┆ "analyze",     ┆                ┆            ┆                ┆                │
│                 ┆ "aim", "14"]   ┆                ┆            ┆                ┆                │
│ [Quantification ┆ ["could also   ┆ Beijing da xue ┆ 2006-10-28 ┆ ['Zhan-kunChen ┆ null           │
│ of expression   ┆ remarkably     ┆ xue bao. Yi    ┆            ┆ ',             ┆                │
│ of leukotriene  ┆ diminish       ┆ xue ban =      ┆            ┆ 'Hou-shanLv']  ┆                │
│ B4 inducing     ┆ ltb4", "lox    ┆ Journal of     ┆            ┆                ┆                │
│ tumor necrosis  ┆ exciting       ┆ Peking         ┆            ┆                ┆                │
│ factor-alpha    ┆ protein flap   ┆ University.    ┆            ┆                ┆                │
│ and interleukin ┆ inhibitor",    ┆ Health         ┆            ┆                ┆                │
│ -1beta at mRNA  ┆ "rheumatoid    ┆ sciences       ┆            ┆                ┆                │
│ level in        ┆ arthritis      ┆                ┆            ┆                ┆                │
│ synovial        ┆ could induce   ┆                ┆            ┆                ┆                │
│ membrane cells  ┆ expressions",  ┆                ┆            ┆                ┆                │
│ of rheumatoid   ┆ "lit           ┆                ┆            ┆                ┆                │
│ arthritis by    ┆ significantly  ┆                ┆            ┆                ┆                │
│ real-time       ┆ increased mrna ┆                ┆            ┆                ┆                │
│ quantitative    ┆ expressions",  ┆                ┆            ┆                ┆                │
│ PCR].           ┆ "41 %- 71 %)", ┆                ┆            ┆                ┆                │
│                 ┆ "primary       ┆                ┆            ┆                ┆                │
│                 ┆ cultured       ┆                ┆            ┆                ┆                │
│                 ┆ synovial       ┆                ┆            ┆                ┆                │
│                 ┆ cells", "15 %- ┆                ┆            ┆                ┆                │
│                 ┆ 66 %)",        ┆                ┆            ┆                ┆                │
│                 ┆ "synovial      ┆                ┆            ┆                ┆                │
│                 ┆ membrane       ┆                ┆            ┆                ┆                │
│                 ┆ cells",        ┆                ┆            ┆                ┆                │
│                 ┆ "synovial      ┆                ┆            ┆                ┆                │
│                 ┆ membrance      ┆                ┆            ┆                ┆                │
│                 ┆ cells",        ┆                ┆            ┆                ┆                │
│                 ┆ "lipoxygenase  ┆                ┆            ┆                ┆                │
│                 ┆ activating     ┆                ┆            ┆                ┆                │
│                 ┆ protein",      ┆                ┆            ┆                ┆                │
│                 ┆ "leukotriene   ┆                ┆            ┆                ┆                │
│                 ┆ a4 hydrolase", ┆                ┆            ┆                ┆                │
│                 ┆ "10 (- 9", "10 ┆                ┆            ┆                ┆                │
│                 ┆ (- 8", "time   ┆                ┆            ┆                ┆                │
│                 ┆ quantitative   ┆                ┆            ┆                ┆                │
│                 ┆ pcr", "induced ┆                ┆            ┆                ┆                │
│                 ┆ mrna           ┆                ┆            ┆                ┆                │
│                 ┆ expressions",  ┆                ┆            ┆                ┆                │
│                 ┆ "16 +/- 0",    ┆                ┆            ┆                ┆                │
│                 ┆ "02 +/- 0",    ┆                ┆            ┆                ┆                │
│                 ┆ "secrete ltb4  ┆                ┆            ┆                ┆                │
│                 ┆ dose",         ┆                ┆            ┆                ┆                │
│                 ┆ "rheumatoid    ┆                ┆            ┆                ┆                │
│                 ┆ arthritis",    ┆                ┆            ┆                ┆                │
│                 ┆ "ltb4 inducing ┆                ┆            ┆                ┆                │
│                 ┆ il", "induce   ┆                ┆            ┆                ┆                │
│                 ┆ dose", "86     ┆                ┆            ┆                ┆                │
│                 ┆ %)", "15       ┆                ┆            ┆                ┆                │
│                 ┆ times",        ┆                ┆            ┆                ┆                │
│                 ┆ "regulated     ┆                ┆            ┆                ┆                │
│                 ┆ expressions",  ┆                ┆            ┆                ┆                │
│                 ┆ "10 micromol", ┆                ┆            ┆                ┆                │
│                 ┆ "mrna level",  ┆                ┆            ┆                ┆                │
│                 ┆ "lit           ┆                ┆            ┆                ┆                │
│                 ┆ respectively", ┆                ┆            ┆                ┆                │
│                 ┆ "exogenous     ┆                ┆            ┆                ┆                │
│                 ┆ ltb4", "ra     ┆                ┆            ┆                ┆                │
│                 ┆ patients",     ┆                ┆            ┆                ┆                │
│                 ┆ "quantified    ┆                ┆            ┆                ┆                │
│                 ┆ successfully", ┆                ┆            ┆                ┆                │
│                 ┆ "investigate   ┆                ┆            ┆                ┆                │
│                 ┆ quantification ┆                ┆            ┆                ┆                │
│                 ┆ ", "endogenous ┆                ┆            ┆                ┆                │
│                 ┆ product",      ┆                ┆            ┆                ┆                │
│                 ┆ "dependent     ┆                ┆            ┆                ┆                │
│                 ┆ increase",     ┆                ┆            ┆                ┆                │
│                 ┆ "beneficial    ┆                ┆            ┆                ┆                │
│                 ┆ help", "79     ┆                ┆            ┆                ┆                │
│                 ┆ %).", "145     ┆                ┆            ┆                ┆                │
│                 ┆ times", "12    ┆                ┆            ┆                ┆                │
│                 ┆ times", "100   ┆                ┆            ┆                ┆                │
│                 ┆ mg", "1 time", ┆                ┆            ┆                ┆                │
│                 ┆ "mrna          ┆                ┆            ┆                ┆                │
│                 ┆ expression",   ┆                ┆            ┆                ┆                │
│                 ┆ "01            ┆                ┆            ┆                ┆                │
│                 ┆ respectively", ┆                ┆            ┆                ┆                │
│                 ┆ "treated       ┆                ┆            ┆                ┆                │
│                 ┆ synoviocytes", ┆                ┆            ┆                ┆                │
│                 ┆ "basic tnf",   ┆                ┆            ┆                ┆                │
│                 ┆ "expressions", ┆                ┆            ┆                ┆                │
│                 ┆ "lit",         ┆                ┆            ┆                ┆                │
│                 ┆ "inhibitor",   ┆                ┆            ┆                ┆                │
│                 ┆ "ltb4", "0",   ┆                ┆            ┆                ┆                │
│                 ┆ "respectively" ┆                ┆            ┆                ┆                │
│                 ┆ , "treated",   ┆                ┆            ┆                ┆                │
│                 ┆ "1",           ┆                ┆            ┆                ┆                │
│                 ┆ "expression",  ┆                ┆            ┆                ┆                │
│                 ┆ "il", "tnf",   ┆                ┆            ┆                ┆                │
│                 ┆ "shown",       ┆                ┆            ┆                ┆                │
│                 ┆ "real",        ┆                ┆            ┆                ┆                │
│                 ┆ "quantify",    ┆                ┆            ┆                ┆                │
│                 ┆ "presence",    ┆                ┆            ┆                ┆                │
│                 ┆ "mol", "mk",   ┆                ┆            ┆                ┆                │
│                 ┆ "methodology", ┆                ┆            ┆                ┆                │
│                 ┆ "markedly",    ┆                ┆            ┆                ┆                │
│                 ┆ "l", "kinds",  ┆                ┆            ┆                ┆                │
│                 ┆ "inhibited",   ┆                ┆            ┆                ┆                │
│                 ┆ "gapdh",       ┆                ┆            ┆                ┆                │
│                 ┆ "following",   ┆                ┆            ┆                ┆                │
│                 ┆ "detected",    ┆                ┆            ┆                ┆                │
│                 ┆ "dependently", ┆                ┆            ┆                ┆                │
│                 ┆ "cytokines",   ┆                ┆            ┆                ┆                │
│                 ┆ "beta",        ┆                ┆            ┆                ┆                │
│                 ┆ "bestatin",    ┆                ┆            ┆                ┆                │
│                 ┆ "alpha",       ┆                ┆            ┆                ┆                │
│                 ┆ "addition",    ┆                ┆            ┆                ┆                │
│                 ┆ "886", "7",    ┆                ┆            ┆                ┆                │
│                 ┆ "5", "1beta",  ┆                ┆            ┆                ┆                │
│                 ┆ "00"]          ┆                ┆            ┆                ┆                │
└─────────────────┴────────────────┴────────────────┴────────────┴────────────────┴────────────────┘

### Save cleaned lazyframe as a csv and then use it to extract keywords

In [60]:
dt_drop_raw_df.sink_csv('pubmed_cleaned_drop_author.csv')

### Extracting keywords for entire dataframe

In [61]:
rcd = pl.scan_csv("/Users/shantibrodnick/Downloads/510Capstone/GenderDisparityinResearch/notebooks/Article_Data_APIs/data/pubmed_cleaned_drop_author.csv")

In [62]:
rcd.select(pl.len()).collect().item()

10206788

In [63]:
def extract_keyword(text):
    if text is None:
        return []
    r = Rake()
    r.extract_keywords_from_text(str(text))
    return list(dict.fromkeys(r.get_ranked_phrases())) 

keyword_rcd = rcd.with_columns([
    pl.col('abstract').map_elements(extract_keyword, return_dtype = pl.List(pl.String))
])

In [64]:
keyword_rcd.select(pl.len()).collect().item()

10206788

In [69]:
keyword_rcd_test = keyword_rcd.head(15).collect()

In [71]:
keyword_rcd_test

shape: (15, 5)
┌─────────────────────┬─────────────────────┬────────────────────┬────────────┬────────────────────┐
│ title               ┆ abstract            ┆ journal            ┆ date       ┆ doi                │
│ ---                 ┆ ---                 ┆ ---                ┆ ---        ┆ ---                │
│ str                 ┆ list[str]           ┆ str                ┆ str        ┆ str                │
╞═════════════════════╪═════════════════════╪════════════════════╪════════════╪════════════════════╡
│ Anti-tumor necrosis ┆ ["infliximab        ┆ Rheumatology       ┆ 2006-10-20 ┆ 10.1007/s00296-006 │
│ factor-alp…         ┆ treatment signifi…  ┆ international      ┆            ┆ -0241-1            │
│ [Quantification of  ┆ ["could also        ┆ Beijing da xue xue ┆ 2006-10-28 ┆ null               │
│ expression …        ┆ remarkably dimini…  ┆ bao. Yi xue…       ┆            ┆                    │
│ Interleukin-7       ┆ ["7 induces tumour  ┆ Annals of the      ┆ 2006-10-14 ┆ 10.1136/ard.2006.0 │
│ induced immunopa…   ┆ necrosis fa…        ┆ rheumatic diseas…  ┆            ┆ 58479              │
│ High-throughput     ┆ ["wallac 1450       ┆ Methods in         ┆ 2006-10-31 ┆ 10.1385/1-59745-16 │
│ quantitation o…     ┆ microbeta trilux…   ┆ molecular biology  ┆            ┆ 7-3:267            │
│                     ┆                     ┆ (…                 ┆            ┆                    │
│ Pulsed electrical   ┆ null                ┆ Orthopedics        ┆ 2006-10-26 ┆ 10.3928/01477447-2 │
│ stimulation …       ┆                     ┆                    ┆            ┆ 0061001-13         │
│ …                   ┆ …                   ┆ …                  ┆ …          ┆ …                  │
│ Heat shock proteins ┆ ["antigen specific  ┆ Annals of the      ┆ 2006-10-14 ┆ 10.1136/ard.2006.0 │
│ induce T c…         ┆ immunothera…        ┆ rheumatic diseas…  ┆            ┆ 58495              │
│ Detection of novel  ┆ ["synuclein         ┆ FASEB journal :    ┆ 2006-10-03 ┆ 10.1096/fj.05-5422 │
│ intracellul…        ┆ oligomerization us… ┆ official publi…    ┆            ┆ com                │
│ AMG 531, a thrombop ┆ ["amg 531 per       ┆ The New England    ┆ 2006-10-20 ┆ 10.1056/NEJMoa0546 │
│ oiesis-stim…        ┆ kilogram per wee…   ┆ journal of med…    ┆            ┆ 26                 │
│ Glucocorticoid      ┆ ["novel selective   ┆ Biotechnology      ┆ 2006-10-19 ┆ 10.1016/S1387-2656 │
│ action and the …    ┆ glucocortico…       ┆ annual review      ┆            ┆ (06)12008-6        │
│ Early diagnosis of  ┆ ["european spondylo ┆ Nature clinical    ┆ 2006-10-04 ┆ 10.1038/ncprheum02 │
│ spondyloart…        ┆ arthropathy…        ┆ practice. Rheu…    ┆            ┆ 96                 │
└─────────────────────┴─────────────────────┴────────────────────┴────────────┴────────────────────┘

In [70]:
keyword_rcd_test.with_columns(
    pl.col('abstract').list.len()
)

shape: (15, 5)
┌────────────────────────┬──────────┬────────────────────────┬────────────┬────────────────────────┐
│ title                  ┆ abstract ┆ journal                ┆ date       ┆ doi                    │
│ ---                    ┆ ---      ┆ ---                    ┆ ---        ┆ ---                    │
│ str                    ┆ u32      ┆ str                    ┆ str        ┆ str                    │
╞════════════════════════╪══════════╪════════════════════════╪════════════╪════════════════════════╡
│ Anti-tumor necrosis    ┆ 41       ┆ Rheumatology           ┆ 2006-10-20 ┆ 10.1007/s00296-006-024 │
│ factor-alp…            ┆          ┆ international          ┆            ┆ 1-1                    │
│ [Quantification of     ┆ 79       ┆ Beijing da xue xue     ┆ 2006-10-28 ┆ null                   │
│ expression …           ┆          ┆ bao. Yi xue…           ┆            ┆                        │
│ Interleukin-7 induced  ┆ 72       ┆ Annals of the          ┆ 2006-10-14 ┆ 10.1136/ard.2006.05847 │
│ immunopa…              ┆          ┆ rheumatic diseas…      ┆            ┆ 9                      │
│ High-throughput        ┆ 85       ┆ Methods in molecular   ┆ 2006-10-31 ┆ 10.1385/1-59745-167-3: │
│ quantitation o…        ┆          ┆ biology (…             ┆            ┆ 267                    │
│ Pulsed electrical      ┆ null     ┆ Orthopedics            ┆ 2006-10-26 ┆ 10.3928/01477447-20061 │
│ stimulation …          ┆          ┆                        ┆            ┆ 001-13                 │
│ …                      ┆ …        ┆ …                      ┆ …          ┆ …                      │
│ Heat shock proteins    ┆ 73       ┆ Annals of the          ┆ 2006-10-14 ┆ 10.1136/ard.2006.05849 │
│ induce T c…            ┆          ┆ rheumatic diseas…      ┆            ┆ 5                      │
│ Detection of novel     ┆ 48       ┆ FASEB journal :        ┆ 2006-10-03 ┆ 10.1096/fj.05-5422com  │
│ intracellul…           ┆          ┆ official publi…        ┆            ┆                        │
│ AMG 531, a             ┆ 96       ┆ The New England        ┆ 2006-10-20 ┆ 10.1056/NEJMoa054626   │
│ thrombopoiesis-stim…   ┆          ┆ journal of med…        ┆            ┆                        │
│ Glucocorticoid action  ┆ 55       ┆ Biotechnology annual   ┆ 2006-10-19 ┆ 10.1016/S1387-2656(06) │
│ and the …              ┆          ┆ review                 ┆            ┆ 12008-6                │
│ Early diagnosis of     ┆ 81       ┆ Nature clinical        ┆ 2006-10-04 ┆ 10.1038/ncprheum0296   │
│ spondyloart…           ┆          ┆ practice. Rheu…        ┆            ┆                        │
└────────────────────────┴──────────┴────────────────────────┴────────────┴────────────────────────┘

In [ ]:
# Check estimated size
keyword_rcd.collect().estimated_size("mb")
# 10.2 GB

10279.678154945374

# Try and pull gender or something like that out of the full abstract